import { OpenAPIHono } from '@hono/zod-openapi';
import { streamSSE } from 'hono/streaming';
import { container } from '@/container.js';
import { getFolderScopedIds } from '@/lib/folder-scopes.js';
import { openApiValidationHook } from '@/lib/openapi.js';
import { getResourceScopedIds, hasScope, hasScopeBase, hasScopeForCreation } from '@/lib/permissions.js';
import { AppError } from '@/middleware/error-handler.js';
import {
  authMiddleware,
  rejectImpersonation,
  requireScope,
  requireScopeForResource,
} from '@/modules/auth/auth.middleware.js';
import {
  CreateResourceFolderSchema,
  MoveResourceFolderSchema,
  MoveResourcesToFolderSchema,
  ReorderResourceFoldersSchema,
  ReorderResourcesSchema,
  UpdateResourceFolderSchema,
} from '@/modules/resource-folders/resource-folder.schemas.js';
import {
  createBucketRoute,
  createObjectStorageConnectionRoute,
  createObjectStorageFolderRoute,
  createPrefixRoute,
  deleteBucketRoute,
  deleteObjectStorageConnectionRoute,
  deleteObjectStorageFolderRoute,
  deleteObjectsRoute,
  downloadObjectRoute,
  getObjectStorageConnectionBySlugRoute,
  getObjectStorageConnectionRoute,
  getObjectStorageHealthHistoryRoute,
  listBucketsRoute,
  listObjectStorageConnectionsRoute,
  listObjectStorageFoldersRoute,
  listObjectsRoute,
  moveObjectStorageFolderRoute,
  moveObjectStorageToFolderRoute,
  objectMetadataRoute,
  objectStorageMonitoringStreamRoute,
  presignObjectRoute,
  reorderObjectStorageFoldersRoute,
  reorderObjectStorageRoute,
  revealObjectStorageCredentialsRoute,
  testObjectStorageConnectionRoute,
  updateObjectStorageConnectionRoute,
  updateObjectStorageFolderRoute,
  uploadObjectRoute,
} from './object-storage.docs.js';
import {
  CreateBucketSchema,
  CreateObjectStorageConnectionSchema,
  CreatePrefixSchema,
  DeleteObjectsSchema,
  ListObjectsQuerySchema,
  ObjectMetadataQuerySchema,
  ObjectStorageListQuerySchema,
  PresignObjectSchema,
  UpdateObjectStorageConnectionSchema,
} from './object-storage.schemas.js';
import { ObjectStorageService } from './object-storage.service.js';
import { ObjectStorageFolderService } from './object-storage-folders.service.js';
import { ObjectStorageMonitoringService } from './object-storage-monitoring.service.js';

/** Existing API, RBAC, schema and service identities supplied to the private router. */
export const storageRouteRuntime = {
  OpenAPIHono,
  streamSSE,
  container,
  openApiValidationHook,
  getResourceScopedIds,
  getFolderScopedIds,
  hasScope,
  hasScopeBase,
  hasScopeForCreation,
  AppError,
  authMiddleware,
  requireScope,
  requireScopeForResource,
  rejectImpersonation,
  CreateResourceFolderSchema,
  MoveResourceFolderSchema,
  MoveResourcesToFolderSchema,
  ReorderResourceFoldersSchema,
  ReorderResourcesSchema,
  UpdateResourceFolderSchema,
  createBucketRoute,
  createObjectStorageConnectionRoute,
  createObjectStorageFolderRoute,
  createPrefixRoute,
  deleteBucketRoute,
  deleteObjectStorageConnectionRoute,
  deleteObjectStorageFolderRoute,
  deleteObjectsRoute,
  downloadObjectRoute,
  getObjectStorageConnectionBySlugRoute,
  getObjectStorageConnectionRoute,
  getObjectStorageHealthHistoryRoute,
  listBucketsRoute,
  listObjectStorageConnectionsRoute,
  listObjectStorageFoldersRoute,
  listObjectsRoute,
  moveObjectStorageFolderRoute,
  moveObjectStorageToFolderRoute,
  objectMetadataRoute,
  objectStorageMonitoringStreamRoute,
  presignObjectRoute,
  reorderObjectStorageFoldersRoute,
  reorderObjectStorageRoute,
  revealObjectStorageCredentialsRoute,
  testObjectStorageConnectionRoute,
  updateObjectStorageConnectionRoute,
  updateObjectStorageFolderRoute,
  uploadObjectRoute,
  CreateBucketSchema,
  CreateObjectStorageConnectionSchema,
  CreatePrefixSchema,
  DeleteObjectsSchema,
  ListObjectsQuerySchema,
  ObjectMetadataQuerySchema,
  ObjectStorageListQuerySchema,
  PresignObjectSchema,
  UpdateObjectStorageConnectionSchema,
  ObjectStorageService,
  ObjectStorageFolderService,
  ObjectStorageMonitoringService,
};
