// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: relay/v1/relay.proto

package relayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedGrant) Reset() {
	*x = SignedGrant{}
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedGrant) ProtoMessage() {}

func (x *SignedGrant) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedGrant.ProtoReflect.Descriptor instead.
func (*SignedGrant) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{0}
}

func (x *SignedGrant) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignedGrant) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedGrant) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type EndpointControl struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EndpointControl_Register
	//	*EndpointControl_Renew
	//	*EndpointControl_Registered
	//	*EndpointControl_Incoming
	//	*EndpointControl_Error
	Payload       isEndpointControl_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointControl) Reset() {
	*x = EndpointControl{}
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointControl) ProtoMessage() {}

func (x *EndpointControl) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointControl.ProtoReflect.Descriptor instead.
func (*EndpointControl) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointControl) GetPayload() isEndpointControl_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EndpointControl) GetRegister() *RegisterEndpoint {
	if x != nil {
		if x, ok := x.Payload.(*EndpointControl_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *EndpointControl) GetRenew() *RenewEndpoint {
	if x != nil {
		if x, ok := x.Payload.(*EndpointControl_Renew); ok {
			return x.Renew
		}
	}
	return nil
}

func (x *EndpointControl) GetRegistered() *EndpointRegistered {
	if x != nil {
		if x, ok := x.Payload.(*EndpointControl_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *EndpointControl) GetIncoming() *IncomingTunnel {
	if x != nil {
		if x, ok := x.Payload.(*EndpointControl_Incoming); ok {
			return x.Incoming
		}
	}
	return nil
}

func (x *EndpointControl) GetError() *RelayError {
	if x != nil {
		if x, ok := x.Payload.(*EndpointControl_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEndpointControl_Payload interface {
	isEndpointControl_Payload()
}

type EndpointControl_Register struct {
	Register *RegisterEndpoint `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type EndpointControl_Renew struct {
	Renew *RenewEndpoint `protobuf:"bytes,2,opt,name=renew,proto3,oneof"`
}

type EndpointControl_Registered struct {
	Registered *EndpointRegistered `protobuf:"bytes,3,opt,name=registered,proto3,oneof"`
}

type EndpointControl_Incoming struct {
	Incoming *IncomingTunnel `protobuf:"bytes,4,opt,name=incoming,proto3,oneof"`
}

type EndpointControl_Error struct {
	Error *RelayError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

func (*EndpointControl_Register) isEndpointControl_Payload() {}

func (*EndpointControl_Renew) isEndpointControl_Payload() {}

func (*EndpointControl_Registered) isEndpointControl_Payload() {}

func (*EndpointControl_Incoming) isEndpointControl_Payload() {}

func (*EndpointControl_Error) isEndpointControl_Payload() {}

type RegisterEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *SignedGrant           `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEndpoint) Reset() {
	*x = RegisterEndpoint{}
	mi := &file_relay_v1_relay_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEndpoint) ProtoMessage() {}

func (x *RegisterEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEndpoint.ProtoReflect.Descriptor instead.
func (*RegisterEndpoint) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterEndpoint) GetGrant() *SignedGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

type RenewEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *SignedGrant           `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewEndpoint) Reset() {
	*x = RenewEndpoint{}
	mi := &file_relay_v1_relay_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewEndpoint) ProtoMessage() {}

func (x *RenewEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewEndpoint.ProtoReflect.Descriptor instead.
func (*RenewEndpoint) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{3}
}

func (x *RenewEndpoint) GetGrant() *SignedGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

type EndpointRegistered struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EndpointId         string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	GrantExpiresAtUnix int64                  `protobuf:"varint,2,opt,name=grant_expires_at_unix,json=grantExpiresAtUnix,proto3" json:"grant_expires_at_unix,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EndpointRegistered) Reset() {
	*x = EndpointRegistered{}
	mi := &file_relay_v1_relay_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRegistered) ProtoMessage() {}

func (x *EndpointRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRegistered.ProtoReflect.Descriptor instead.
func (*EndpointRegistered) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{4}
}

func (x *EndpointRegistered) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *EndpointRegistered) GetGrantExpiresAtUnix() int64 {
	if x != nil {
		return x.GrantExpiresAtUnix
	}
	return 0
}

type IncomingTunnel struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AcceptToken         string                 `protobuf:"bytes,2,opt,name=accept_token,json=acceptToken,proto3" json:"accept_token,omitempty"`
	AcceptExpiresAtUnix int64                  `protobuf:"varint,3,opt,name=accept_expires_at_unix,json=acceptExpiresAtUnix,proto3" json:"accept_expires_at_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IncomingTunnel) Reset() {
	*x = IncomingTunnel{}
	mi := &file_relay_v1_relay_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingTunnel) ProtoMessage() {}

func (x *IncomingTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingTunnel.ProtoReflect.Descriptor instead.
func (*IncomingTunnel) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{5}
}

func (x *IncomingTunnel) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IncomingTunnel) GetAcceptToken() string {
	if x != nil {
		return x.AcceptToken
	}
	return ""
}

func (x *IncomingTunnel) GetAcceptExpiresAtUnix() int64 {
	if x != nil {
		return x.AcceptExpiresAtUnix
	}
	return 0
}

type TunnelFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelFrame_Open
	//	*TunnelFrame_Accept
	//	*TunnelFrame_Ready
	//	*TunnelFrame_Data
	//	*TunnelFrame_HalfClose
	//	*TunnelFrame_Close
	//	*TunnelFrame_Error
	Payload       isTunnelFrame_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelFrame) Reset() {
	*x = TunnelFrame{}
	mi := &file_relay_v1_relay_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelFrame) ProtoMessage() {}

func (x *TunnelFrame) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelFrame.ProtoReflect.Descriptor instead.
func (*TunnelFrame) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelFrame) GetPayload() isTunnelFrame_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelFrame) GetOpen() *OpenTunnel {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Open); ok {
			return x.Open
		}
	}
	return nil
}

func (x *TunnelFrame) GetAccept() *AcceptTunnel {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Accept); ok {
			return x.Accept
		}
	}
	return nil
}

func (x *TunnelFrame) GetReady() *TunnelReady {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *TunnelFrame) GetData() *TunnelData {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelFrame) GetHalfClose() *TunnelHalfClose {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_HalfClose); ok {
			return x.HalfClose
		}
	}
	return nil
}

func (x *TunnelFrame) GetClose() *TunnelClose {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Close); ok {
			return x.Close
		}
	}
	return nil
}

func (x *TunnelFrame) GetError() *RelayError {
	if x != nil {
		if x, ok := x.Payload.(*TunnelFrame_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isTunnelFrame_Payload interface {
	isTunnelFrame_Payload()
}

type TunnelFrame_Open struct {
	Open *OpenTunnel `protobuf:"bytes,1,opt,name=open,proto3,oneof"`
}

type TunnelFrame_Accept struct {
	Accept *AcceptTunnel `protobuf:"bytes,2,opt,name=accept,proto3,oneof"`
}

type TunnelFrame_Ready struct {
	Ready *TunnelReady `protobuf:"bytes,3,opt,name=ready,proto3,oneof"`
}

type TunnelFrame_Data struct {
	Data *TunnelData `protobuf:"bytes,4,opt,name=data,proto3,oneof"`
}

type TunnelFrame_HalfClose struct {
	HalfClose *TunnelHalfClose `protobuf:"bytes,5,opt,name=half_close,json=halfClose,proto3,oneof"`
}

type TunnelFrame_Close struct {
	Close *TunnelClose `protobuf:"bytes,6,opt,name=close,proto3,oneof"`
}

type TunnelFrame_Error struct {
	Error *RelayError `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*TunnelFrame_Open) isTunnelFrame_Payload() {}

func (*TunnelFrame_Accept) isTunnelFrame_Payload() {}

func (*TunnelFrame_Ready) isTunnelFrame_Payload() {}

func (*TunnelFrame_Data) isTunnelFrame_Payload() {}

func (*TunnelFrame_HalfClose) isTunnelFrame_Payload() {}

func (*TunnelFrame_Close) isTunnelFrame_Payload() {}

func (*TunnelFrame_Error) isTunnelFrame_Payload() {}

type OpenTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *SignedGrant           `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnel) Reset() {
	*x = OpenTunnel{}
	mi := &file_relay_v1_relay_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnel) ProtoMessage() {}

func (x *OpenTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnel.ProtoReflect.Descriptor instead.
func (*OpenTunnel) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{7}
}

func (x *OpenTunnel) GetGrant() *SignedGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

type AcceptTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptToken   string                 `protobuf:"bytes,1,opt,name=accept_token,json=acceptToken,proto3" json:"accept_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptTunnel) Reset() {
	*x = AcceptTunnel{}
	mi := &file_relay_v1_relay_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptTunnel) ProtoMessage() {}

func (x *AcceptTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptTunnel.ProtoReflect.Descriptor instead.
func (*AcceptTunnel) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{8}
}

func (x *AcceptTunnel) GetAcceptToken() string {
	if x != nil {
		return x.AcceptToken
	}
	return ""
}

type TunnelReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxFrameBytes uint32                 `protobuf:"varint,1,opt,name=max_frame_bytes,json=maxFrameBytes,proto3" json:"max_frame_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelReady) Reset() {
	*x = TunnelReady{}
	mi := &file_relay_v1_relay_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelReady) ProtoMessage() {}

func (x *TunnelReady) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelReady.ProtoReflect.Descriptor instead.
func (*TunnelReady) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{9}
}

func (x *TunnelReady) GetMaxFrameBytes() uint32 {
	if x != nil {
		return x.MaxFrameBytes
	}
	return 0
}

type TunnelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	mi := &file_relay_v1_relay_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{10}
}

func (x *TunnelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type TunnelHalfClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelHalfClose) Reset() {
	*x = TunnelHalfClose{}
	mi := &file_relay_v1_relay_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelHalfClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelHalfClose) ProtoMessage() {}

func (x *TunnelHalfClose) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelHalfClose.ProtoReflect.Descriptor instead.
func (*TunnelHalfClose) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{11}
}

type TunnelClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelClose) Reset() {
	*x = TunnelClose{}
	mi := &file_relay_v1_relay_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelClose) ProtoMessage() {}

func (x *TunnelClose) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelClose.ProtoReflect.Descriptor instead.
func (*TunnelClose) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{12}
}

type RelayError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayError) Reset() {
	*x = RelayError{}
	mi := &file_relay_v1_relay_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayError) ProtoMessage() {}

func (x *RelayError) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayError.ProtoReflect.Descriptor instead.
func (*RelayError) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{13}
}

func (x *RelayError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RelayError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_relay_v1_relay_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{14}
}

func (x *PublicKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *PublicKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type EndpointPolicy struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EndpointId            string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Generation            uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	SubjectKind           string                 `protobuf:"bytes,3,opt,name=subject_kind,json=subjectKind,proto3" json:"subject_kind,omitempty"`
	SubjectId             string                 `protobuf:"bytes,4,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	CertificateSha256     string                 `protobuf:"bytes,5,opt,name=certificate_sha256,json=certificateSha256,proto3" json:"certificate_sha256,omitempty"`
	MaxConcurrentSessions uint32                 `protobuf:"varint,6,opt,name=max_concurrent_sessions,json=maxConcurrentSessions,proto3" json:"max_concurrent_sessions,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EndpointPolicy) Reset() {
	*x = EndpointPolicy{}
	mi := &file_relay_v1_relay_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointPolicy) ProtoMessage() {}

func (x *EndpointPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointPolicy.ProtoReflect.Descriptor instead.
func (*EndpointPolicy) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{15}
}

func (x *EndpointPolicy) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *EndpointPolicy) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *EndpointPolicy) GetSubjectKind() string {
	if x != nil {
		return x.SubjectKind
	}
	return ""
}

func (x *EndpointPolicy) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *EndpointPolicy) GetCertificateSha256() string {
	if x != nil {
		return x.CertificateSha256
	}
	return ""
}

func (x *EndpointPolicy) GetMaxConcurrentSessions() uint32 {
	if x != nil {
		return x.MaxConcurrentSessions
	}
	return 0
}

type RoutePolicy struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RouteId                 string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	Generation              uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	SourceKind              string                 `protobuf:"bytes,3,opt,name=source_kind,json=sourceKind,proto3" json:"source_kind,omitempty"`
	SourceId                string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceCertificateSha256 string                 `protobuf:"bytes,5,opt,name=source_certificate_sha256,json=sourceCertificateSha256,proto3" json:"source_certificate_sha256,omitempty"`
	TargetEndpointId        string                 `protobuf:"bytes,6,opt,name=target_endpoint_id,json=targetEndpointId,proto3" json:"target_endpoint_id,omitempty"`
	MaxConcurrentSessions   uint32                 `protobuf:"varint,7,opt,name=max_concurrent_sessions,json=maxConcurrentSessions,proto3" json:"max_concurrent_sessions,omitempty"`
	MaxFrameBytes           uint32                 `protobuf:"varint,8,opt,name=max_frame_bytes,json=maxFrameBytes,proto3" json:"max_frame_bytes,omitempty"`
	// Proxy Secure Links intentionally have no fixed idle timeout. Existing
	// routes keep the relay default when this field is false.
	DisableIdleTimeout bool `protobuf:"varint,9,opt,name=disable_idle_timeout,json=disableIdleTimeout,proto3" json:"disable_idle_timeout,omitempty"`
	// Product classification used only for overload admission and reporting.
	// The relay remains unaware of concrete Gateway resource identifiers.
	TrafficClass  string `protobuf:"bytes,10,opt,name=traffic_class,json=trafficClass,proto3" json:"traffic_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePolicy) Reset() {
	*x = RoutePolicy{}
	mi := &file_relay_v1_relay_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicy) ProtoMessage() {}

func (x *RoutePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicy.ProtoReflect.Descriptor instead.
func (*RoutePolicy) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{16}
}

func (x *RoutePolicy) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RoutePolicy) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *RoutePolicy) GetSourceKind() string {
	if x != nil {
		return x.SourceKind
	}
	return ""
}

func (x *RoutePolicy) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RoutePolicy) GetSourceCertificateSha256() string {
	if x != nil {
		return x.SourceCertificateSha256
	}
	return ""
}

func (x *RoutePolicy) GetTargetEndpointId() string {
	if x != nil {
		return x.TargetEndpointId
	}
	return ""
}

func (x *RoutePolicy) GetMaxConcurrentSessions() uint32 {
	if x != nil {
		return x.MaxConcurrentSessions
	}
	return 0
}

func (x *RoutePolicy) GetMaxFrameBytes() uint32 {
	if x != nil {
		return x.MaxFrameBytes
	}
	return 0
}

func (x *RoutePolicy) GetDisableIdleTimeout() bool {
	if x != nil {
		return x.DisableIdleTimeout
	}
	return false
}

func (x *RoutePolicy) GetTrafficClass() string {
	if x != nil {
		return x.TrafficClass
	}
	return ""
}

type AdmissionPolicy struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Enabled                    bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ProxyTargetPressurePercent uint32                 `protobuf:"varint,2,opt,name=proxy_target_pressure_percent,json=proxyTargetPressurePercent,proto3" json:"proxy_target_pressure_percent,omitempty"`
	DatabaseReservePercent     uint32                 `protobuf:"varint,3,opt,name=database_reserve_percent,json=databaseReservePercent,proto3" json:"database_reserve_percent,omitempty"`
	HardPressurePercent        uint32                 `protobuf:"varint,4,opt,name=hard_pressure_percent,json=hardPressurePercent,proto3" json:"hard_pressure_percent,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *AdmissionPolicy) Reset() {
	*x = AdmissionPolicy{}
	mi := &file_relay_v1_relay_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionPolicy) ProtoMessage() {}

func (x *AdmissionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionPolicy.ProtoReflect.Descriptor instead.
func (*AdmissionPolicy) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{17}
}

func (x *AdmissionPolicy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AdmissionPolicy) GetProxyTargetPressurePercent() uint32 {
	if x != nil {
		return x.ProxyTargetPressurePercent
	}
	return 0
}

func (x *AdmissionPolicy) GetDatabaseReservePercent() uint32 {
	if x != nil {
		return x.DatabaseReservePercent
	}
	return 0
}

func (x *AdmissionPolicy) GetHardPressurePercent() uint32 {
	if x != nil {
		return x.HardPressurePercent
	}
	return 0
}

type ApplySnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Revision          uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	GatewayInstanceId string                 `protobuf:"bytes,2,opt,name=gateway_instance_id,json=gatewayInstanceId,proto3" json:"gateway_instance_id,omitempty"`
	PublicKeys        []*PublicKey           `protobuf:"bytes,3,rep,name=public_keys,json=publicKeys,proto3" json:"public_keys,omitempty"`
	Endpoints         []*EndpointPolicy      `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Routes            []*RoutePolicy         `protobuf:"bytes,5,rep,name=routes,proto3" json:"routes,omitempty"`
	AdmissionPolicy   *AdmissionPolicy       `protobuf:"bytes,6,opt,name=admission_policy,json=admissionPolicy,proto3" json:"admission_policy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ApplySnapshotRequest) Reset() {
	*x = ApplySnapshotRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySnapshotRequest) ProtoMessage() {}

func (x *ApplySnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySnapshotRequest.ProtoReflect.Descriptor instead.
func (*ApplySnapshotRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{18}
}

func (x *ApplySnapshotRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *ApplySnapshotRequest) GetGatewayInstanceId() string {
	if x != nil {
		return x.GatewayInstanceId
	}
	return ""
}

func (x *ApplySnapshotRequest) GetPublicKeys() []*PublicKey {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

func (x *ApplySnapshotRequest) GetEndpoints() []*EndpointPolicy {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *ApplySnapshotRequest) GetRoutes() []*RoutePolicy {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ApplySnapshotRequest) GetAdmissionPolicy() *AdmissionPolicy {
	if x != nil {
		return x.AdmissionPolicy
	}
	return nil
}

type ApplySnapshotResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppliedRevision uint64                 `protobuf:"varint,1,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	Unchanged       bool                   `protobuf:"varint,2,opt,name=unchanged,proto3" json:"unchanged,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplySnapshotResponse) Reset() {
	*x = ApplySnapshotResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplySnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplySnapshotResponse) ProtoMessage() {}

func (x *ApplySnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplySnapshotResponse.ProtoReflect.Descriptor instead.
func (*ApplySnapshotResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{19}
}

func (x *ApplySnapshotResponse) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *ApplySnapshotResponse) GetUnchanged() bool {
	if x != nil {
		return x.Unchanged
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{20}
}

type HealthResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BuildVersion           string                 `protobuf:"bytes,1,opt,name=build_version,json=buildVersion,proto3" json:"build_version,omitempty"`
	ProtocolMajor          uint32                 `protobuf:"varint,2,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	AppliedRevision        uint64                 `protobuf:"varint,3,opt,name=applied_revision,json=appliedRevision,proto3" json:"applied_revision,omitempty"`
	KeyIds                 []string               `protobuf:"bytes,4,rep,name=key_ids,json=keyIds,proto3" json:"key_ids,omitempty"`
	RegisteredEndpoints    uint64                 `protobuf:"varint,5,opt,name=registered_endpoints,json=registeredEndpoints,proto3" json:"registered_endpoints,omitempty"`
	ActiveTunnels          uint64                 `protobuf:"varint,6,opt,name=active_tunnels,json=activeTunnels,proto3" json:"active_tunnels,omitempty"`
	Liveness               bool                   `protobuf:"varint,7,opt,name=liveness,proto3" json:"liveness,omitempty"`
	Readiness              bool                   `protobuf:"varint,8,opt,name=readiness,proto3" json:"readiness,omitempty"`
	Reason                 string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	ActiveProxyTunnels     uint64                 `protobuf:"varint,10,opt,name=active_proxy_tunnels,json=activeProxyTunnels,proto3" json:"active_proxy_tunnels,omitempty"`
	ActiveDatabaseTunnels  uint64                 `protobuf:"varint,11,opt,name=active_database_tunnels,json=activeDatabaseTunnels,proto3" json:"active_database_tunnels,omitempty"`
	ThrottledProxyTotal    uint64                 `protobuf:"varint,12,opt,name=throttled_proxy_total,json=throttledProxyTotal,proto3" json:"throttled_proxy_total,omitempty"`
	ThrottledDatabaseTotal uint64                 `protobuf:"varint,13,opt,name=throttled_database_total,json=throttledDatabaseTotal,proto3" json:"throttled_database_total,omitempty"`
	PressurePercent        uint32                 `protobuf:"varint,14,opt,name=pressure_percent,json=pressurePercent,proto3" json:"pressure_percent,omitempty"`
	CpuPressurePercent     uint32                 `protobuf:"varint,15,opt,name=cpu_pressure_percent,json=cpuPressurePercent,proto3" json:"cpu_pressure_percent,omitempty"`
	MemoryPressurePercent  uint32                 `protobuf:"varint,16,opt,name=memory_pressure_percent,json=memoryPressurePercent,proto3" json:"memory_pressure_percent,omitempty"`
	FdPressurePercent      uint32                 `protobuf:"varint,17,opt,name=fd_pressure_percent,json=fdPressurePercent,proto3" json:"fd_pressure_percent,omitempty"`
	AdmissionState         string                 `protobuf:"bytes,18,opt,name=admission_state,json=admissionState,proto3" json:"admission_state,omitempty"`
	MemoryRssBytes         uint64                 `protobuf:"varint,19,opt,name=memory_rss_bytes,json=memoryRssBytes,proto3" json:"memory_rss_bytes,omitempty"`
	HeapInUseBytes         uint64                 `protobuf:"varint,20,opt,name=heap_in_use_bytes,json=heapInUseBytes,proto3" json:"heap_in_use_bytes,omitempty"`
	MemoryLimitBytes       uint64                 `protobuf:"varint,21,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	OpenFileDescriptors    uint64                 `protobuf:"varint,22,opt,name=open_file_descriptors,json=openFileDescriptors,proto3" json:"open_file_descriptors,omitempty"`
	FileDescriptorLimit    uint64                 `protobuf:"varint,23,opt,name=file_descriptor_limit,json=fileDescriptorLimit,proto3" json:"file_descriptor_limit,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{21}
}

func (x *HealthResponse) GetBuildVersion() string {
	if x != nil {
		return x.BuildVersion
	}
	return ""
}

func (x *HealthResponse) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HealthResponse) GetAppliedRevision() uint64 {
	if x != nil {
		return x.AppliedRevision
	}
	return 0
}

func (x *HealthResponse) GetKeyIds() []string {
	if x != nil {
		return x.KeyIds
	}
	return nil
}

func (x *HealthResponse) GetRegisteredEndpoints() uint64 {
	if x != nil {
		return x.RegisteredEndpoints
	}
	return 0
}

func (x *HealthResponse) GetActiveTunnels() uint64 {
	if x != nil {
		return x.ActiveTunnels
	}
	return 0
}

func (x *HealthResponse) GetLiveness() bool {
	if x != nil {
		return x.Liveness
	}
	return false
}

func (x *HealthResponse) GetReadiness() bool {
	if x != nil {
		return x.Readiness
	}
	return false
}

func (x *HealthResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HealthResponse) GetActiveProxyTunnels() uint64 {
	if x != nil {
		return x.ActiveProxyTunnels
	}
	return 0
}

func (x *HealthResponse) GetActiveDatabaseTunnels() uint64 {
	if x != nil {
		return x.ActiveDatabaseTunnels
	}
	return 0
}

func (x *HealthResponse) GetThrottledProxyTotal() uint64 {
	if x != nil {
		return x.ThrottledProxyTotal
	}
	return 0
}

func (x *HealthResponse) GetThrottledDatabaseTotal() uint64 {
	if x != nil {
		return x.ThrottledDatabaseTotal
	}
	return 0
}

func (x *HealthResponse) GetPressurePercent() uint32 {
	if x != nil {
		return x.PressurePercent
	}
	return 0
}

func (x *HealthResponse) GetCpuPressurePercent() uint32 {
	if x != nil {
		return x.CpuPressurePercent
	}
	return 0
}

func (x *HealthResponse) GetMemoryPressurePercent() uint32 {
	if x != nil {
		return x.MemoryPressurePercent
	}
	return 0
}

func (x *HealthResponse) GetFdPressurePercent() uint32 {
	if x != nil {
		return x.FdPressurePercent
	}
	return 0
}

func (x *HealthResponse) GetAdmissionState() string {
	if x != nil {
		return x.AdmissionState
	}
	return ""
}

func (x *HealthResponse) GetMemoryRssBytes() uint64 {
	if x != nil {
		return x.MemoryRssBytes
	}
	return 0
}

func (x *HealthResponse) GetHeapInUseBytes() uint64 {
	if x != nil {
		return x.HeapInUseBytes
	}
	return 0
}

func (x *HealthResponse) GetMemoryLimitBytes() uint64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

func (x *HealthResponse) GetOpenFileDescriptors() uint64 {
	if x != nil {
		return x.OpenFileDescriptors
	}
	return 0
}

func (x *HealthResponse) GetFileDescriptorLimit() uint64 {
	if x != nil {
		return x.FileDescriptorLimit
	}
	return 0
}

type RouteRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRuntimeRequest) Reset() {
	*x = RouteRuntimeRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRuntimeRequest) ProtoMessage() {}

func (x *RouteRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRuntimeRequest.ProtoReflect.Descriptor instead.
func (*RouteRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{22}
}

func (x *RouteRuntimeRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

type RouteRuntimeResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	RouteId                      string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	ActiveTunnels                uint64                 `protobuf:"varint,2,opt,name=active_tunnels,json=activeTunnels,proto3" json:"active_tunnels,omitempty"`
	OpenedTotal                  uint64                 `protobuf:"varint,3,opt,name=opened_total,json=openedTotal,proto3" json:"opened_total,omitempty"`
	CompletedTotal               uint64                 `protobuf:"varint,4,opt,name=completed_total,json=completedTotal,proto3" json:"completed_total,omitempty"`
	FailedTotal                  uint64                 `protobuf:"varint,5,opt,name=failed_total,json=failedTotal,proto3" json:"failed_total,omitempty"`
	ThrottledTotal               uint64                 `protobuf:"varint,6,opt,name=throttled_total,json=throttledTotal,proto3" json:"throttled_total,omitempty"`
	SourceToTargetBytes          uint64                 `protobuf:"varint,7,opt,name=source_to_target_bytes,json=sourceToTargetBytes,proto3" json:"source_to_target_bytes,omitempty"`
	TargetToSourceBytes          uint64                 `protobuf:"varint,8,opt,name=target_to_source_bytes,json=targetToSourceBytes,proto3" json:"target_to_source_bytes,omitempty"`
	SetupLatencyP95Microseconds  uint64                 `protobuf:"varint,9,opt,name=setup_latency_p95_microseconds,json=setupLatencyP95Microseconds,proto3" json:"setup_latency_p95_microseconds,omitempty"`
	AverageDurationMilliseconds  uint64                 `protobuf:"varint,10,opt,name=average_duration_milliseconds,json=averageDurationMilliseconds,proto3" json:"average_duration_milliseconds,omitempty"`
	LastActivityUnixMilliseconds int64                  `protobuf:"varint,11,opt,name=last_activity_unix_milliseconds,json=lastActivityUnixMilliseconds,proto3" json:"last_activity_unix_milliseconds,omitempty"`
	MetricsSinceUnixMilliseconds int64                  `protobuf:"varint,12,opt,name=metrics_since_unix_milliseconds,json=metricsSinceUnixMilliseconds,proto3" json:"metrics_since_unix_milliseconds,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RouteRuntimeResponse) Reset() {
	*x = RouteRuntimeResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRuntimeResponse) ProtoMessage() {}

func (x *RouteRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRuntimeResponse.ProtoReflect.Descriptor instead.
func (*RouteRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{23}
}

func (x *RouteRuntimeResponse) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *RouteRuntimeResponse) GetActiveTunnels() uint64 {
	if x != nil {
		return x.ActiveTunnels
	}
	return 0
}

func (x *RouteRuntimeResponse) GetOpenedTotal() uint64 {
	if x != nil {
		return x.OpenedTotal
	}
	return 0
}

func (x *RouteRuntimeResponse) GetCompletedTotal() uint64 {
	if x != nil {
		return x.CompletedTotal
	}
	return 0
}

func (x *RouteRuntimeResponse) GetFailedTotal() uint64 {
	if x != nil {
		return x.FailedTotal
	}
	return 0
}

func (x *RouteRuntimeResponse) GetThrottledTotal() uint64 {
	if x != nil {
		return x.ThrottledTotal
	}
	return 0
}

func (x *RouteRuntimeResponse) GetSourceToTargetBytes() uint64 {
	if x != nil {
		return x.SourceToTargetBytes
	}
	return 0
}

func (x *RouteRuntimeResponse) GetTargetToSourceBytes() uint64 {
	if x != nil {
		return x.TargetToSourceBytes
	}
	return 0
}

func (x *RouteRuntimeResponse) GetSetupLatencyP95Microseconds() uint64 {
	if x != nil {
		return x.SetupLatencyP95Microseconds
	}
	return 0
}

func (x *RouteRuntimeResponse) GetAverageDurationMilliseconds() uint64 {
	if x != nil {
		return x.AverageDurationMilliseconds
	}
	return 0
}

func (x *RouteRuntimeResponse) GetLastActivityUnixMilliseconds() int64 {
	if x != nil {
		return x.LastActivityUnixMilliseconds
	}
	return 0
}

func (x *RouteRuntimeResponse) GetMetricsSinceUnixMilliseconds() int64 {
	if x != nil {
		return x.MetricsSinceUnixMilliseconds
	}
	return 0
}

type ReloadIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadIdentityRequest) Reset() {
	*x = ReloadIdentityRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadIdentityRequest) ProtoMessage() {}

func (x *ReloadIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadIdentityRequest.ProtoReflect.Descriptor instead.
func (*ReloadIdentityRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{24}
}

func (x *ReloadIdentityRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type ReloadIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reloaded      bool                   `protobuf:"varint,1,opt,name=reloaded,proto3" json:"reloaded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadIdentityResponse) Reset() {
	*x = ReloadIdentityResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadIdentityResponse) ProtoMessage() {}

func (x *ReloadIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadIdentityResponse.ProtoReflect.Descriptor instead.
func (*ReloadIdentityResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{25}
}

func (x *ReloadIdentityResponse) GetReloaded() bool {
	if x != nil {
		return x.Reloaded
	}
	return false
}

type CommitIdentityRotationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitIdentityRotationRequest) Reset() {
	*x = CommitIdentityRotationRequest{}
	mi := &file_relay_v1_relay_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitIdentityRotationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitIdentityRotationRequest) ProtoMessage() {}

func (x *CommitIdentityRotationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitIdentityRotationRequest.ProtoReflect.Descriptor instead.
func (*CommitIdentityRotationRequest) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{26}
}

func (x *CommitIdentityRotationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type CommitIdentityRotationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Committed     bool                   `protobuf:"varint,1,opt,name=committed,proto3" json:"committed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitIdentityRotationResponse) Reset() {
	*x = CommitIdentityRotationResponse{}
	mi := &file_relay_v1_relay_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitIdentityRotationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitIdentityRotationResponse) ProtoMessage() {}

func (x *CommitIdentityRotationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v1_relay_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitIdentityRotationResponse.ProtoReflect.Descriptor instead.
func (*CommitIdentityRotationResponse) Descriptor() ([]byte, []int) {
	return file_relay_v1_relay_proto_rawDescGZIP(), []int{27}
}

func (x *CommitIdentityRotationResponse) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

var File_relay_v1_relay_proto protoreflect.FileDescriptor

const file_relay_v1_relay_proto_rawDesc = "" +
	"\n" +
	"\x14relay/v1/relay.proto\x12\brelay.v1\"\\\n" +
	"\vSignedGrant\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xad\x02\n" +
	"\x0fEndpointControl\x128\n" +
	"\bregister\x18\x01 \x01(\v2\x1a.relay.v1.RegisterEndpointH\x00R\bregister\x12/\n" +
	"\x05renew\x18\x02 \x01(\v2\x17.relay.v1.RenewEndpointH\x00R\x05renew\x12>\n" +
	"\n" +
	"registered\x18\x03 \x01(\v2\x1c.relay.v1.EndpointRegisteredH\x00R\n" +
	"registered\x126\n" +
	"\bincoming\x18\x04 \x01(\v2\x18.relay.v1.IncomingTunnelH\x00R\bincoming\x12,\n" +
	"\x05error\x18\x05 \x01(\v2\x14.relay.v1.RelayErrorH\x00R\x05errorB\t\n" +
	"\apayload\"?\n" +
	"\x10RegisterEndpoint\x12+\n" +
	"\x05grant\x18\x01 \x01(\v2\x15.relay.v1.SignedGrantR\x05grant\"<\n" +
	"\rRenewEndpoint\x12+\n" +
	"\x05grant\x18\x01 \x01(\v2\x15.relay.v1.SignedGrantR\x05grant\"h\n" +
	"\x12EndpointRegistered\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x121\n" +
	"\x15grant_expires_at_unix\x18\x02 \x01(\x03R\x12grantExpiresAtUnix\"\x87\x01\n" +
	"\x0eIncomingTunnel\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\faccept_token\x18\x02 \x01(\tR\vacceptToken\x123\n" +
	"\x16accept_expires_at_unix\x18\x03 \x01(\x03R\x13acceptExpiresAtUnix\"\xea\x02\n" +
	"\vTunnelFrame\x12*\n" +
	"\x04open\x18\x01 \x01(\v2\x14.relay.v1.OpenTunnelH\x00R\x04open\x120\n" +
	"\x06accept\x18\x02 \x01(\v2\x16.relay.v1.AcceptTunnelH\x00R\x06accept\x12-\n" +
	"\x05ready\x18\x03 \x01(\v2\x15.relay.v1.TunnelReadyH\x00R\x05ready\x12*\n" +
	"\x04data\x18\x04 \x01(\v2\x14.relay.v1.TunnelDataH\x00R\x04data\x12:\n" +
	"\n" +
	"half_close\x18\x05 \x01(\v2\x19.relay.v1.TunnelHalfCloseH\x00R\thalfClose\x12-\n" +
	"\x05close\x18\x06 \x01(\v2\x15.relay.v1.TunnelCloseH\x00R\x05close\x12,\n" +
	"\x05error\x18\a \x01(\v2\x14.relay.v1.RelayErrorH\x00R\x05errorB\t\n" +
	"\apayload\"9\n" +
	"\n" +
	"OpenTunnel\x12+\n" +
	"\x05grant\x18\x01 \x01(\v2\x15.relay.v1.SignedGrantR\x05grant\"1\n" +
	"\fAcceptTunnel\x12!\n" +
	"\faccept_token\x18\x01 \x01(\tR\vacceptToken\"5\n" +
	"\vTunnelReady\x12&\n" +
	"\x0fmax_frame_bytes\x18\x01 \x01(\rR\rmaxFrameBytes\" \n" +
	"\n" +
	"TunnelData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x11\n" +
	"\x0fTunnelHalfClose\"\r\n" +
	"\vTunnelClose\":\n" +
	"\n" +
	"RelayError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\tPublicKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\"\xfa\x01\n" +
	"\x0eEndpointPolicy\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12!\n" +
	"\fsubject_kind\x18\x03 \x01(\tR\vsubjectKind\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x04 \x01(\tR\tsubjectId\x12-\n" +
	"\x12certificate_sha256\x18\x05 \x01(\tR\x11certificateSha256\x126\n" +
	"\x17max_concurrent_sessions\x18\x06 \x01(\rR\x15maxConcurrentSessions\"\xa7\x03\n" +
	"\vRoutePolicy\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x12\x1f\n" +
	"\vsource_kind\x18\x03 \x01(\tR\n" +
	"sourceKind\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12:\n" +
	"\x19source_certificate_sha256\x18\x05 \x01(\tR\x17sourceCertificateSha256\x12,\n" +
	"\x12target_endpoint_id\x18\x06 \x01(\tR\x10targetEndpointId\x126\n" +
	"\x17max_concurrent_sessions\x18\a \x01(\rR\x15maxConcurrentSessions\x12&\n" +
	"\x0fmax_frame_bytes\x18\b \x01(\rR\rmaxFrameBytes\x120\n" +
	"\x14disable_idle_timeout\x18\t \x01(\bR\x12disableIdleTimeout\x12#\n" +
	"\rtraffic_class\x18\n" +
	" \x01(\tR\ftrafficClass\"\xdc\x01\n" +
	"\x0fAdmissionPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12A\n" +
	"\x1dproxy_target_pressure_percent\x18\x02 \x01(\rR\x1aproxyTargetPressurePercent\x128\n" +
	"\x18database_reserve_percent\x18\x03 \x01(\rR\x16databaseReservePercent\x122\n" +
	"\x15hard_pressure_percent\x18\x04 \x01(\rR\x13hardPressurePercent\"\xc5\x02\n" +
	"\x14ApplySnapshotRequest\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x12.\n" +
	"\x13gateway_instance_id\x18\x02 \x01(\tR\x11gatewayInstanceId\x124\n" +
	"\vpublic_keys\x18\x03 \x03(\v2\x13.relay.v1.PublicKeyR\n" +
	"publicKeys\x126\n" +
	"\tendpoints\x18\x04 \x03(\v2\x18.relay.v1.EndpointPolicyR\tendpoints\x12-\n" +
	"\x06routes\x18\x05 \x03(\v2\x15.relay.v1.RoutePolicyR\x06routes\x12D\n" +
	"\x10admission_policy\x18\x06 \x01(\v2\x19.relay.v1.AdmissionPolicyR\x0fadmissionPolicy\"`\n" +
	"\x15ApplySnapshotResponse\x12)\n" +
	"\x10applied_revision\x18\x01 \x01(\x04R\x0fappliedRevision\x12\x1c\n" +
	"\tunchanged\x18\x02 \x01(\bR\tunchanged\"\x0f\n" +
	"\rHealthRequest\"\xfd\a\n" +
	"\x0eHealthResponse\x12#\n" +
	"\rbuild_version\x18\x01 \x01(\tR\fbuildVersion\x12%\n" +
	"\x0eprotocol_major\x18\x02 \x01(\rR\rprotocolMajor\x12)\n" +
	"\x10applied_revision\x18\x03 \x01(\x04R\x0fappliedRevision\x12\x17\n" +
	"\akey_ids\x18\x04 \x03(\tR\x06keyIds\x121\n" +
	"\x14registered_endpoints\x18\x05 \x01(\x04R\x13registeredEndpoints\x12%\n" +
	"\x0eactive_tunnels\x18\x06 \x01(\x04R\ractiveTunnels\x12\x1a\n" +
	"\bliveness\x18\a \x01(\bR\bliveness\x12\x1c\n" +
	"\treadiness\x18\b \x01(\bR\treadiness\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x120\n" +
	"\x14active_proxy_tunnels\x18\n" +
	" \x01(\x04R\x12activeProxyTunnels\x126\n" +
	"\x17active_database_tunnels\x18\v \x01(\x04R\x15activeDatabaseTunnels\x122\n" +
	"\x15throttled_proxy_total\x18\f \x01(\x04R\x13throttledProxyTotal\x128\n" +
	"\x18throttled_database_total\x18\r \x01(\x04R\x16throttledDatabaseTotal\x12)\n" +
	"\x10pressure_percent\x18\x0e \x01(\rR\x0fpressurePercent\x120\n" +
	"\x14cpu_pressure_percent\x18\x0f \x01(\rR\x12cpuPressurePercent\x126\n" +
	"\x17memory_pressure_percent\x18\x10 \x01(\rR\x15memoryPressurePercent\x12.\n" +
	"\x13fd_pressure_percent\x18\x11 \x01(\rR\x11fdPressurePercent\x12'\n" +
	"\x0fadmission_state\x18\x12 \x01(\tR\x0eadmissionState\x12(\n" +
	"\x10memory_rss_bytes\x18\x13 \x01(\x04R\x0ememoryRssBytes\x12)\n" +
	"\x11heap_in_use_bytes\x18\x14 \x01(\x04R\x0eheapInUseBytes\x12,\n" +
	"\x12memory_limit_bytes\x18\x15 \x01(\x04R\x10memoryLimitBytes\x122\n" +
	"\x15open_file_descriptors\x18\x16 \x01(\x04R\x13openFileDescriptors\x122\n" +
	"\x15file_descriptor_limit\x18\x17 \x01(\x04R\x13fileDescriptorLimit\"0\n" +
	"\x13RouteRuntimeRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\"\xf1\x04\n" +
	"\x14RouteRuntimeResponse\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12%\n" +
	"\x0eactive_tunnels\x18\x02 \x01(\x04R\ractiveTunnels\x12!\n" +
	"\fopened_total\x18\x03 \x01(\x04R\vopenedTotal\x12'\n" +
	"\x0fcompleted_total\x18\x04 \x01(\x04R\x0ecompletedTotal\x12!\n" +
	"\ffailed_total\x18\x05 \x01(\x04R\vfailedTotal\x12'\n" +
	"\x0fthrottled_total\x18\x06 \x01(\x04R\x0ethrottledTotal\x123\n" +
	"\x16source_to_target_bytes\x18\a \x01(\x04R\x13sourceToTargetBytes\x123\n" +
	"\x16target_to_source_bytes\x18\b \x01(\x04R\x13targetToSourceBytes\x12C\n" +
	"\x1esetup_latency_p95_microseconds\x18\t \x01(\x04R\x1bsetupLatencyP95Microseconds\x12B\n" +
	"\x1daverage_duration_milliseconds\x18\n" +
	" \x01(\x04R\x1baverageDurationMilliseconds\x12E\n" +
	"\x1flast_activity_unix_milliseconds\x18\v \x01(\x03R\x1clastActivityUnixMilliseconds\x12E\n" +
	"\x1fmetrics_since_unix_milliseconds\x18\f \x01(\x03R\x1cmetricsSinceUnixMilliseconds\":\n" +
	"\x15ReloadIdentityRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"4\n" +
	"\x16ReloadIdentityResponse\x12\x1a\n" +
	"\breloaded\x18\x01 \x01(\bR\breloaded\"B\n" +
	"\x1dCommitIdentityRotationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\">\n" +
	"\x1eCommitIdentityRotationResponse\x12\x1c\n" +
	"\tcommitted\x18\x01 \x01(\bR\tcommitted2\xde\x01\n" +
	"\fTunnelBroker\x12L\n" +
	"\x10RegisterEndpoint\x12\x19.relay.v1.EndpointControl\x1a\x19.relay.v1.EndpointControl(\x010\x01\x12>\n" +
	"\n" +
	"OpenTunnel\x12\x15.relay.v1.TunnelFrame\x1a\x15.relay.v1.TunnelFrame(\x010\x01\x12@\n" +
	"\fAcceptTunnel\x12\x15.relay.v1.TunnelFrame\x1a\x15.relay.v1.TunnelFrame(\x010\x012\xb2\x03\n" +
	"\n" +
	"RelayAdmin\x12>\n" +
	"\tGetHealth\x12\x17.relay.v1.HealthRequest\x1a\x18.relay.v1.HealthResponse\x12P\n" +
	"\x0fGetRouteRuntime\x12\x1d.relay.v1.RouteRuntimeRequest\x1a\x1e.relay.v1.RouteRuntimeResponse\x12P\n" +
	"\rApplySnapshot\x12\x1e.relay.v1.ApplySnapshotRequest\x1a\x1f.relay.v1.ApplySnapshotResponse\x12S\n" +
	"\x0eReloadIdentity\x12\x1f.relay.v1.ReloadIdentityRequest\x1a .relay.v1.ReloadIdentityResponse\x12k\n" +
	"\x16CommitIdentityRotation\x12'.relay.v1.CommitIdentityRotationRequest\x1a(.relay.v1.CommitIdentityRotationResponseB=Z;github.com/wiolett-industries/gateway/daemon-shared/relayv1b\x06proto3"

var (
	file_relay_v1_relay_proto_rawDescOnce sync.Once
	file_relay_v1_relay_proto_rawDescData []byte
)

func file_relay_v1_relay_proto_rawDescGZIP() []byte {
	file_relay_v1_relay_proto_rawDescOnce.Do(func() {
		file_relay_v1_relay_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)))
	})
	return file_relay_v1_relay_proto_rawDescData
}

var file_relay_v1_relay_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_relay_v1_relay_proto_goTypes = []any{
	(*SignedGrant)(nil),                    // 0: relay.v1.SignedGrant
	(*EndpointControl)(nil),                // 1: relay.v1.EndpointControl
	(*RegisterEndpoint)(nil),               // 2: relay.v1.RegisterEndpoint
	(*RenewEndpoint)(nil),                  // 3: relay.v1.RenewEndpoint
	(*EndpointRegistered)(nil),             // 4: relay.v1.EndpointRegistered
	(*IncomingTunnel)(nil),                 // 5: relay.v1.IncomingTunnel
	(*TunnelFrame)(nil),                    // 6: relay.v1.TunnelFrame
	(*OpenTunnel)(nil),                     // 7: relay.v1.OpenTunnel
	(*AcceptTunnel)(nil),                   // 8: relay.v1.AcceptTunnel
	(*TunnelReady)(nil),                    // 9: relay.v1.TunnelReady
	(*TunnelData)(nil),                     // 10: relay.v1.TunnelData
	(*TunnelHalfClose)(nil),                // 11: relay.v1.TunnelHalfClose
	(*TunnelClose)(nil),                    // 12: relay.v1.TunnelClose
	(*RelayError)(nil),                     // 13: relay.v1.RelayError
	(*PublicKey)(nil),                      // 14: relay.v1.PublicKey
	(*EndpointPolicy)(nil),                 // 15: relay.v1.EndpointPolicy
	(*RoutePolicy)(nil),                    // 16: relay.v1.RoutePolicy
	(*AdmissionPolicy)(nil),                // 17: relay.v1.AdmissionPolicy
	(*ApplySnapshotRequest)(nil),           // 18: relay.v1.ApplySnapshotRequest
	(*ApplySnapshotResponse)(nil),          // 19: relay.v1.ApplySnapshotResponse
	(*HealthRequest)(nil),                  // 20: relay.v1.HealthRequest
	(*HealthResponse)(nil),                 // 21: relay.v1.HealthResponse
	(*RouteRuntimeRequest)(nil),            // 22: relay.v1.RouteRuntimeRequest
	(*RouteRuntimeResponse)(nil),           // 23: relay.v1.RouteRuntimeResponse
	(*ReloadIdentityRequest)(nil),          // 24: relay.v1.ReloadIdentityRequest
	(*ReloadIdentityResponse)(nil),         // 25: relay.v1.ReloadIdentityResponse
	(*CommitIdentityRotationRequest)(nil),  // 26: relay.v1.CommitIdentityRotationRequest
	(*CommitIdentityRotationResponse)(nil), // 27: relay.v1.CommitIdentityRotationResponse
}
var file_relay_v1_relay_proto_depIdxs = []int32{
	2,  // 0: relay.v1.EndpointControl.register:type_name -> relay.v1.RegisterEndpoint
	3,  // 1: relay.v1.EndpointControl.renew:type_name -> relay.v1.RenewEndpoint
	4,  // 2: relay.v1.EndpointControl.registered:type_name -> relay.v1.EndpointRegistered
	5,  // 3: relay.v1.EndpointControl.incoming:type_name -> relay.v1.IncomingTunnel
	13, // 4: relay.v1.EndpointControl.error:type_name -> relay.v1.RelayError
	0,  // 5: relay.v1.RegisterEndpoint.grant:type_name -> relay.v1.SignedGrant
	0,  // 6: relay.v1.RenewEndpoint.grant:type_name -> relay.v1.SignedGrant
	7,  // 7: relay.v1.TunnelFrame.open:type_name -> relay.v1.OpenTunnel
	8,  // 8: relay.v1.TunnelFrame.accept:type_name -> relay.v1.AcceptTunnel
	9,  // 9: relay.v1.TunnelFrame.ready:type_name -> relay.v1.TunnelReady
	10, // 10: relay.v1.TunnelFrame.data:type_name -> relay.v1.TunnelData
	11, // 11: relay.v1.TunnelFrame.half_close:type_name -> relay.v1.TunnelHalfClose
	12, // 12: relay.v1.TunnelFrame.close:type_name -> relay.v1.TunnelClose
	13, // 13: relay.v1.TunnelFrame.error:type_name -> relay.v1.RelayError
	0,  // 14: relay.v1.OpenTunnel.grant:type_name -> relay.v1.SignedGrant
	14, // 15: relay.v1.ApplySnapshotRequest.public_keys:type_name -> relay.v1.PublicKey
	15, // 16: relay.v1.ApplySnapshotRequest.endpoints:type_name -> relay.v1.EndpointPolicy
	16, // 17: relay.v1.ApplySnapshotRequest.routes:type_name -> relay.v1.RoutePolicy
	17, // 18: relay.v1.ApplySnapshotRequest.admission_policy:type_name -> relay.v1.AdmissionPolicy
	1,  // 19: relay.v1.TunnelBroker.RegisterEndpoint:input_type -> relay.v1.EndpointControl
	6,  // 20: relay.v1.TunnelBroker.OpenTunnel:input_type -> relay.v1.TunnelFrame
	6,  // 21: relay.v1.TunnelBroker.AcceptTunnel:input_type -> relay.v1.TunnelFrame
	20, // 22: relay.v1.RelayAdmin.GetHealth:input_type -> relay.v1.HealthRequest
	22, // 23: relay.v1.RelayAdmin.GetRouteRuntime:input_type -> relay.v1.RouteRuntimeRequest
	18, // 24: relay.v1.RelayAdmin.ApplySnapshot:input_type -> relay.v1.ApplySnapshotRequest
	24, // 25: relay.v1.RelayAdmin.ReloadIdentity:input_type -> relay.v1.ReloadIdentityRequest
	26, // 26: relay.v1.RelayAdmin.CommitIdentityRotation:input_type -> relay.v1.CommitIdentityRotationRequest
	1,  // 27: relay.v1.TunnelBroker.RegisterEndpoint:output_type -> relay.v1.EndpointControl
	6,  // 28: relay.v1.TunnelBroker.OpenTunnel:output_type -> relay.v1.TunnelFrame
	6,  // 29: relay.v1.TunnelBroker.AcceptTunnel:output_type -> relay.v1.TunnelFrame
	21, // 30: relay.v1.RelayAdmin.GetHealth:output_type -> relay.v1.HealthResponse
	23, // 31: relay.v1.RelayAdmin.GetRouteRuntime:output_type -> relay.v1.RouteRuntimeResponse
	19, // 32: relay.v1.RelayAdmin.ApplySnapshot:output_type -> relay.v1.ApplySnapshotResponse
	25, // 33: relay.v1.RelayAdmin.ReloadIdentity:output_type -> relay.v1.ReloadIdentityResponse
	27, // 34: relay.v1.RelayAdmin.CommitIdentityRotation:output_type -> relay.v1.CommitIdentityRotationResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_relay_v1_relay_proto_init() }
func file_relay_v1_relay_proto_init() {
	if File_relay_v1_relay_proto != nil {
		return
	}
	file_relay_v1_relay_proto_msgTypes[1].OneofWrappers = []any{
		(*EndpointControl_Register)(nil),
		(*EndpointControl_Renew)(nil),
		(*EndpointControl_Registered)(nil),
		(*EndpointControl_Incoming)(nil),
		(*EndpointControl_Error)(nil),
	}
	file_relay_v1_relay_proto_msgTypes[6].OneofWrappers = []any{
		(*TunnelFrame_Open)(nil),
		(*TunnelFrame_Accept)(nil),
		(*TunnelFrame_Ready)(nil),
		(*TunnelFrame_Data)(nil),
		(*TunnelFrame_HalfClose)(nil),
		(*TunnelFrame_Close)(nil),
		(*TunnelFrame_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_v1_relay_proto_rawDesc), len(file_relay_v1_relay_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_relay_v1_relay_proto_goTypes,
		DependencyIndexes: file_relay_v1_relay_proto_depIdxs,
		MessageInfos:      file_relay_v1_relay_proto_msgTypes,
	}.Build()
	File_relay_v1_relay_proto = out.File
	file_relay_v1_relay_proto_goTypes = nil
	file_relay_v1_relay_proto_depIdxs = nil
}
