// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: relay/v1/relay.proto

package relayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TunnelBroker_RegisterEndpoint_FullMethodName = "/relay.v1.TunnelBroker/RegisterEndpoint"
	TunnelBroker_OpenTunnel_FullMethodName       = "/relay.v1.TunnelBroker/OpenTunnel"
	TunnelBroker_AcceptTunnel_FullMethodName     = "/relay.v1.TunnelBroker/AcceptTunnel"
)

// TunnelBrokerClient is the client API for TunnelBroker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TunnelBroker is deliberately resource agnostic. Gateway is the only
// component that maps endpoint and route identifiers to product resources.
type TunnelBrokerClient interface {
	RegisterEndpoint(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointControl, EndpointControl], error)
	OpenTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
	AcceptTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error)
}

type tunnelBrokerClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelBrokerClient(cc grpc.ClientConnInterface) TunnelBrokerClient {
	return &tunnelBrokerClient{cc}
}

func (c *tunnelBrokerClient) RegisterEndpoint(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EndpointControl, EndpointControl], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelBroker_ServiceDesc.Streams[0], TunnelBroker_RegisterEndpoint_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EndpointControl, EndpointControl]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelBroker_RegisterEndpointClient = grpc.BidiStreamingClient[EndpointControl, EndpointControl]

func (c *tunnelBrokerClient) OpenTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelBroker_ServiceDesc.Streams[1], TunnelBroker_OpenTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelBroker_OpenTunnelClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

func (c *tunnelBrokerClient) AcceptTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelFrame, TunnelFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TunnelBroker_ServiceDesc.Streams[2], TunnelBroker_AcceptTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelFrame, TunnelFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelBroker_AcceptTunnelClient = grpc.BidiStreamingClient[TunnelFrame, TunnelFrame]

// TunnelBrokerServer is the server API for TunnelBroker service.
// All implementations must embed UnimplementedTunnelBrokerServer
// for forward compatibility.
//
// TunnelBroker is deliberately resource agnostic. Gateway is the only
// component that maps endpoint and route identifiers to product resources.
type TunnelBrokerServer interface {
	RegisterEndpoint(grpc.BidiStreamingServer[EndpointControl, EndpointControl]) error
	OpenTunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	AcceptTunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error
	mustEmbedUnimplementedTunnelBrokerServer()
}

// UnimplementedTunnelBrokerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTunnelBrokerServer struct{}

func (UnimplementedTunnelBrokerServer) RegisterEndpoint(grpc.BidiStreamingServer[EndpointControl, EndpointControl]) error {
	return status.Error(codes.Unimplemented, "method RegisterEndpoint not implemented")
}
func (UnimplementedTunnelBrokerServer) OpenTunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method OpenTunnel not implemented")
}
func (UnimplementedTunnelBrokerServer) AcceptTunnel(grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]) error {
	return status.Error(codes.Unimplemented, "method AcceptTunnel not implemented")
}
func (UnimplementedTunnelBrokerServer) mustEmbedUnimplementedTunnelBrokerServer() {}
func (UnimplementedTunnelBrokerServer) testEmbeddedByValue()                      {}

// UnsafeTunnelBrokerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelBrokerServer will
// result in compilation errors.
type UnsafeTunnelBrokerServer interface {
	mustEmbedUnimplementedTunnelBrokerServer()
}

func RegisterTunnelBrokerServer(s grpc.ServiceRegistrar, srv TunnelBrokerServer) {
	// If the following call panics, it indicates UnimplementedTunnelBrokerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TunnelBroker_ServiceDesc, srv)
}

func _TunnelBroker_RegisterEndpoint_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelBrokerServer).RegisterEndpoint(&grpc.GenericServerStream[EndpointControl, EndpointControl]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelBroker_RegisterEndpointServer = grpc.BidiStreamingServer[EndpointControl, EndpointControl]

func _TunnelBroker_OpenTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelBrokerServer).OpenTunnel(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelBroker_OpenTunnelServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

func _TunnelBroker_AcceptTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelBrokerServer).AcceptTunnel(&grpc.GenericServerStream[TunnelFrame, TunnelFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TunnelBroker_AcceptTunnelServer = grpc.BidiStreamingServer[TunnelFrame, TunnelFrame]

// TunnelBroker_ServiceDesc is the grpc.ServiceDesc for TunnelBroker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelBroker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.v1.TunnelBroker",
	HandlerType: (*TunnelBrokerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterEndpoint",
			Handler:       _TunnelBroker_RegisterEndpoint_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "OpenTunnel",
			Handler:       _TunnelBroker_OpenTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "AcceptTunnel",
			Handler:       _TunnelBroker_AcceptTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "relay/v1/relay.proto",
}

const (
	RelayAdmin_GetHealth_FullMethodName              = "/relay.v1.RelayAdmin/GetHealth"
	RelayAdmin_GetRouteRuntime_FullMethodName        = "/relay.v1.RelayAdmin/GetRouteRuntime"
	RelayAdmin_ApplySnapshot_FullMethodName          = "/relay.v1.RelayAdmin/ApplySnapshot"
	RelayAdmin_ReloadIdentity_FullMethodName         = "/relay.v1.RelayAdmin/ReloadIdentity"
	RelayAdmin_CommitIdentityRotation_FullMethodName = "/relay.v1.RelayAdmin/CommitIdentityRotation"
)

// RelayAdminClient is the client API for RelayAdmin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RelayAdmin is reachable on the same listener but only by the pinned Gateway
// app service identity.
type RelayAdminClient interface {
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	GetRouteRuntime(ctx context.Context, in *RouteRuntimeRequest, opts ...grpc.CallOption) (*RouteRuntimeResponse, error)
	ApplySnapshot(ctx context.Context, in *ApplySnapshotRequest, opts ...grpc.CallOption) (*ApplySnapshotResponse, error)
	ReloadIdentity(ctx context.Context, in *ReloadIdentityRequest, opts ...grpc.CallOption) (*ReloadIdentityResponse, error)
	CommitIdentityRotation(ctx context.Context, in *CommitIdentityRotationRequest, opts ...grpc.CallOption) (*CommitIdentityRotationResponse, error)
}

type relayAdminClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayAdminClient(cc grpc.ClientConnInterface) RelayAdminClient {
	return &relayAdminClient{cc}
}

func (c *relayAdminClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, RelayAdmin_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayAdminClient) GetRouteRuntime(ctx context.Context, in *RouteRuntimeRequest, opts ...grpc.CallOption) (*RouteRuntimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteRuntimeResponse)
	err := c.cc.Invoke(ctx, RelayAdmin_GetRouteRuntime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayAdminClient) ApplySnapshot(ctx context.Context, in *ApplySnapshotRequest, opts ...grpc.CallOption) (*ApplySnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplySnapshotResponse)
	err := c.cc.Invoke(ctx, RelayAdmin_ApplySnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayAdminClient) ReloadIdentity(ctx context.Context, in *ReloadIdentityRequest, opts ...grpc.CallOption) (*ReloadIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadIdentityResponse)
	err := c.cc.Invoke(ctx, RelayAdmin_ReloadIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayAdminClient) CommitIdentityRotation(ctx context.Context, in *CommitIdentityRotationRequest, opts ...grpc.CallOption) (*CommitIdentityRotationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitIdentityRotationResponse)
	err := c.cc.Invoke(ctx, RelayAdmin_CommitIdentityRotation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayAdminServer is the server API for RelayAdmin service.
// All implementations must embed UnimplementedRelayAdminServer
// for forward compatibility.
//
// RelayAdmin is reachable on the same listener but only by the pinned Gateway
// app service identity.
type RelayAdminServer interface {
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	GetRouteRuntime(context.Context, *RouteRuntimeRequest) (*RouteRuntimeResponse, error)
	ApplySnapshot(context.Context, *ApplySnapshotRequest) (*ApplySnapshotResponse, error)
	ReloadIdentity(context.Context, *ReloadIdentityRequest) (*ReloadIdentityResponse, error)
	CommitIdentityRotation(context.Context, *CommitIdentityRotationRequest) (*CommitIdentityRotationResponse, error)
	mustEmbedUnimplementedRelayAdminServer()
}

// UnimplementedRelayAdminServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayAdminServer struct{}

func (UnimplementedRelayAdminServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedRelayAdminServer) GetRouteRuntime(context.Context, *RouteRuntimeRequest) (*RouteRuntimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRouteRuntime not implemented")
}
func (UnimplementedRelayAdminServer) ApplySnapshot(context.Context, *ApplySnapshotRequest) (*ApplySnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplySnapshot not implemented")
}
func (UnimplementedRelayAdminServer) ReloadIdentity(context.Context, *ReloadIdentityRequest) (*ReloadIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadIdentity not implemented")
}
func (UnimplementedRelayAdminServer) CommitIdentityRotation(context.Context, *CommitIdentityRotationRequest) (*CommitIdentityRotationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitIdentityRotation not implemented")
}
func (UnimplementedRelayAdminServer) mustEmbedUnimplementedRelayAdminServer() {}
func (UnimplementedRelayAdminServer) testEmbeddedByValue()                    {}

// UnsafeRelayAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayAdminServer will
// result in compilation errors.
type UnsafeRelayAdminServer interface {
	mustEmbedUnimplementedRelayAdminServer()
}

func RegisterRelayAdminServer(s grpc.ServiceRegistrar, srv RelayAdminServer) {
	// If the following call panics, it indicates UnimplementedRelayAdminServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayAdmin_ServiceDesc, srv)
}

func _RelayAdmin_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayAdminServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayAdmin_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayAdminServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayAdmin_GetRouteRuntime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRuntimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayAdminServer).GetRouteRuntime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayAdmin_GetRouteRuntime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayAdminServer).GetRouteRuntime(ctx, req.(*RouteRuntimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayAdmin_ApplySnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayAdminServer).ApplySnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayAdmin_ApplySnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayAdminServer).ApplySnapshot(ctx, req.(*ApplySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayAdmin_ReloadIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayAdminServer).ReloadIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayAdmin_ReloadIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayAdminServer).ReloadIdentity(ctx, req.(*ReloadIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayAdmin_CommitIdentityRotation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitIdentityRotationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayAdminServer).CommitIdentityRotation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayAdmin_CommitIdentityRotation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayAdminServer).CommitIdentityRotation(ctx, req.(*CommitIdentityRotationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayAdmin_ServiceDesc is the grpc.ServiceDesc for RelayAdmin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayAdmin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "relay.v1.RelayAdmin",
	HandlerType: (*RelayAdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _RelayAdmin_GetHealth_Handler,
		},
		{
			MethodName: "GetRouteRuntime",
			Handler:    _RelayAdmin_GetRouteRuntime_Handler,
		},
		{
			MethodName: "ApplySnapshot",
			Handler:    _RelayAdmin_ApplySnapshot_Handler,
		},
		{
			MethodName: "ReloadIdentity",
			Handler:    _RelayAdmin_ReloadIdentity_Handler,
		},
		{
			MethodName: "CommitIdentityRotation",
			Handler:    _RelayAdmin_CommitIdentityRotation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "relay/v1/relay.proto",
}
