import type { ManagedStorageClusterRow } from '@/db/schema/managed-storage.js';
export declare function safeManagedStorageView(row: ManagedStorageClusterRow): {
  id: string;
  name: string;
  slug: string;
  nodeId: string;
  engine: 'minio' | 'seaweedfs';
  version: string;
  imageRef: string;
  storageSizeBytes: number;
  publishedPort: number;
  publishS3: boolean;
  relayEnabled: boolean;
  tlsEnabled: boolean;
  runtimeConfig: import('@/db/schema/managed-storage.js').ManagedStorageRuntimeConfig;
  sftpEnabled: boolean;
  sftpPort: number | null;
  ftpEnabled: boolean;
  ftpPort: number | null;
  ftpPassivePortStart: number | null;
  ftpPassivePortCount: number | null;
  status: 'stopped' | 'error' | 'ready' | 'creating' | 'updating' | 'deleting';
  pendingOperation: import('@/db/schema/managed-storage.js').ManagedStoragePendingOperation | null;
  lastError: string | null;
  objectStorageConnectionId: string | null;
  createdAt: Date;
  updatedAt: Date;
  createdById: string;
  updatedById: string | null;
};
