import { OpenAPIHono } from '@hono/zod-openapi';
import { container } from '@/container.js';
import { openApiValidationHook } from '@/lib/openapi.js';
import { getResourceScopedIds, hasScope, hasScopeBase, hasScopeForCreation } from '@/lib/permissions.js';
import { AppError } from '@/middleware/error-handler.js';
import { authMiddleware, rejectImpersonation, requireScopeBase } from '@/modules/auth/auth.middleware.js';
import { RenewManagedCertificateSchema } from '@/modules/managed-workloads/certificate-renewal.docs.js';
import { ObjectStorageFolderService } from '@/modules/object-storage/object-storage-folders.service.js';
import {
  createManagedStorageAccessKeyRoute,
  createManagedStorageBindingRoute,
  createManagedStorageRoute,
  deleteManagedStorageBindingRoute,
  deleteManagedStorageRoute,
  freezeManagedStorageWritesRoute,
  getManagedStorageCaCertificateRoute,
  getManagedStorageCertificateRoute,
  getManagedStorageRoute,
  importManagedStorageAccessKeysRoute,
  listManagedStorageAccessKeysRoute,
  listManagedStorageBindingsRoute,
  listManagedStorageCatalogRoute,
  listManagedStorageRoute,
  moveManagedStorageBindingRoute,
  rehomeManagedStorageBackupHistoryRoute,
  removeManagedStorageAccessKeyRoute,
  renewManagedStorageCertificateRoute,
  restartManagedStorageRoute,
  retryManagedStorageProvisioningRoute,
  revealManagedStorageCredentialsRoute,
  unfreezeManagedStorageWritesRoute,
  updateManagedStorageRoute,
} from './managed-storage.docs.js';
import {
  CreateManagedStorageAccessKeySchema,
  CreateManagedStorageBindingSchema,
  CreateManagedStorageSchema,
  DeleteManagedStorageBindingSchema,
  ImportManagedStorageAccessKeysSchema,
  MoveManagedStorageBindingSchema,
  RehomeManagedStorageBackupHistorySchema,
  UpdateManagedStorageSchema,
} from './managed-storage.schemas.js';
import { ManagedStorageService } from './managed-storage.service.js';
import { ManagedStorageBindingsService } from './managed-storage-bindings.service.js';
export const managedStorageRouteRuntime = {
  OpenAPIHono,
  container,
  openApiValidationHook,
  getResourceScopedIds,
  hasScope,
  hasScopeBase,
  hasScopeForCreation,
  AppError,
  authMiddleware,
  rejectImpersonation,
  requireScopeBase,
  createManagedStorageAccessKeyRoute,
  createManagedStorageBindingRoute,
  createManagedStorageRoute,
  deleteManagedStorageBindingRoute,
  deleteManagedStorageRoute,
  getManagedStorageCaCertificateRoute,
  getManagedStorageCertificateRoute,
  getManagedStorageRoute,
  listManagedStorageAccessKeysRoute,
  listManagedStorageBindingsRoute,
  listManagedStorageCatalogRoute,
  listManagedStorageRoute,
  removeManagedStorageAccessKeyRoute,
  restartManagedStorageRoute,
  retryManagedStorageProvisioningRoute,
  renewManagedStorageCertificateRoute,
  revealManagedStorageCredentialsRoute,
  updateManagedStorageRoute,
  CreateManagedStorageAccessKeySchema,
  CreateManagedStorageBindingSchema,
  CreateManagedStorageSchema,
  DeleteManagedStorageBindingSchema,
  UpdateManagedStorageSchema,
  RenewManagedCertificateSchema,
  ManagedStorageService,
  ManagedStorageBindingsService,
  ObjectStorageFolderService,
  moveManagedStorageBindingRoute,
  importManagedStorageAccessKeysRoute,
  freezeManagedStorageWritesRoute,
  unfreezeManagedStorageWritesRoute,
  rehomeManagedStorageBackupHistoryRoute,
  MoveManagedStorageBindingSchema,
  ImportManagedStorageAccessKeysSchema,
  RehomeManagedStorageBackupHistorySchema,
};
