import { OpenAPIHono } from '@hono/zod-openapi';
import { streamSSE } from 'hono/streaming';
import { container } from '@/container.js';
import { getFolderScopedIds } from '@/lib/folder-scopes.js';
import { openApiValidationHook } from '@/lib/openapi.js';
import {
  getResourceScopedIds,
  hasScope,
  hasScopeBase,
  hasScopeForCreation,
  hasScopeForResource,
} from '@/lib/permissions.js';
import { AppError } from '@/middleware/error-handler.js';
import {
  authMiddleware,
  rejectImpersonation,
  requireScope,
  requireScopeBase,
  requireScopeForResource,
} from '@/modules/auth/auth.middleware.js';
import { decodeComposeServiceTarget } from '@/modules/docker/compose/compose-managed-bindings.js';
import { DockerManagementService } from '@/modules/docker/docker.service.js';
import { assertDockerResourceScope } from '@/modules/docker/docker-access.middleware.js';
import { isGatewayInternalContainer } from '@/modules/docker/docker-internal-containers.js';
import {
  CreateResourceFolderSchema,
  MoveResourceFolderSchema,
  MoveResourcesToFolderSchema,
  ReorderResourceFoldersSchema,
  ReorderResourcesSchema,
  UpdateResourceFolderSchema,
} from '@/modules/resource-folders/resource-folder.schemas.js';
import { DatabaseFolderService } from './database-folders.service.js';
import { DatabaseMonitoringService } from './database-monitoring.service.js';
import {
  addPostgresColumnRoute,
  browsePostgresRowsRoute,
  browseSqlRowsRoute,
  createDatabaseConnectionRoute,
  createDatabaseFolderRoute,
  createManagedDatabaseBindingRoute,
  createManagedDatabaseRoute,
  databaseMonitoringStreamRoute,
  deleteDatabaseConnectionRoute,
  deleteDatabaseFolderRoute,
  deleteManagedDatabaseBindingRoute,
  deleteManagedDatabaseRoute,
  deletePostgresColumnRoute,
  deletePostgresRowRoute,
  deleteRedisKeyRoute,
  deleteSqlRowRoute,
  disableManagedPostgresExtensionRoute,
  enableManagedPostgresExtensionRoute,
  executePostgresQueryRoute,
  executeRedisCommandRoute,
  executeSqlRoute,
  expireRedisKeyRoute,
  getDatabaseConnectionBySlugRoute,
  getDatabaseConnectionRoute,
  getDatabaseHealthHistoryRoute,
  getManagedDatabaseBindingRuntimeRoute,
  getManagedDatabaseRoute,
  getRedisKeyRoute,
  insertPostgresRowRoute,
  insertSqlRowRoute,
  listDatabaseConnectionsRoute,
  listDatabaseFoldersRoute,
  listManagedDatabaseBindingsRoute,
  listManagedDatabaseCatalogRoute,
  listManagedDatabasesRoute,
  listManagedPostgresExtensionsRoute,
  listPostgresSchemasRoute,
  listPostgresTablesRoute,
  listSqlNamespacesRoute,
  listSqlObjectsRoute,
  moveDatabaseFolderRoute,
  moveDatabasesToFolderRoute,
  pauseManagedDatabaseRoute,
  postgresTableMetadataRoute,
  reorderDatabaseFoldersRoute,
  reorderDatabasesRoute,
  restartManagedDatabaseRoute,
  retryManagedDatabaseProvisioningRoute,
  revealDatabaseCredentialsRoute,
  revealManagedDatabaseBindingCredentialsRoute,
  revealManagedDatabaseCredentialsRoute,
  rotateManagedDatabaseCertificateRoute,
  rotateManagedDatabaseDirectCredentialsRoute,
  scanRedisKeysRoute,
  setRedisKeyRoute,
  sqlTableMetadataRoute,
  testDatabaseConnectionRoute,
  unpauseManagedDatabaseRoute,
  updateDatabaseConnectionRoute,
  updateDatabaseFolderRoute,
  updateManagedDatabaseRoute,
  updatePostgresColumnTypeRoute,
  updatePostgresRowRoute,
  updateSqlRowRoute,
} from './databases.docs.js';
import {
  AddPostgresColumnSchema,
  BrowsePostgresRowsQuerySchema,
  BrowseSqlRowsQuerySchema,
  CreateDatabaseConnectionSchema,
  CreateManagedDatabaseBindingSchema,
  CreateManagedDatabaseSchema,
  DatabaseListQuerySchema,
  DeleteManagedDatabaseBindingSchema,
  DeletePostgresColumnSchema,
  DeleteSqlRowSchema,
  ExecutePostgresSqlSchema,
  ExecuteRedisCommandSchema,
  ExecuteSqlSchema,
  InsertSqlRowSchema,
  PostgresObjectSchema,
  RedisExpireKeySchema,
  RedisGetKeyQuerySchema,
  RedisScanKeysQuerySchema,
  RedisSetKeySchema,
  SqlTableQuerySchema,
  UpdateDatabaseConnectionSchema,
  UpdateManagedDatabaseSchema,
  UpdatePostgresColumnTypeSchema,
  UpdateSqlRowSchema,
} from './databases.schemas.js';
import { DatabaseConnectionService } from './databases.service.js';
import { ManagedDatabaseBindingService } from './managed-database-bindings.service.js';
import { ManagedDatabaseService } from './managed-databases.service.js';

export type { MiddlewareHandler } from 'hono';
export const databaseRouteRuntime = {
  OpenAPIHono,
  streamSSE,
  container,
  getFolderScopedIds,
  openApiValidationHook,
  getResourceScopedIds,
  hasScope,
  hasScopeBase,
  hasScopeForCreation,
  hasScopeForResource,
  AppError,
  authMiddleware,
  rejectImpersonation,
  requireScope,
  requireScopeBase,
  requireScopeForResource,
  decodeComposeServiceTarget,
  DockerManagementService,
  assertDockerResourceScope,
  isGatewayInternalContainer,
  CreateResourceFolderSchema,
  MoveResourceFolderSchema,
  MoveResourcesToFolderSchema,
  ReorderResourceFoldersSchema,
  ReorderResourcesSchema,
  UpdateResourceFolderSchema,
  DatabaseFolderService,
  DatabaseMonitoringService,
  addPostgresColumnRoute,
  browsePostgresRowsRoute,
  browseSqlRowsRoute,
  createDatabaseConnectionRoute,
  createDatabaseFolderRoute,
  createManagedDatabaseBindingRoute,
  createManagedDatabaseRoute,
  databaseMonitoringStreamRoute,
  deleteDatabaseConnectionRoute,
  deleteDatabaseFolderRoute,
  deleteManagedDatabaseBindingRoute,
  deleteManagedDatabaseRoute,
  deletePostgresColumnRoute,
  deletePostgresRowRoute,
  deleteRedisKeyRoute,
  deleteSqlRowRoute,
  disableManagedPostgresExtensionRoute,
  enableManagedPostgresExtensionRoute,
  executePostgresQueryRoute,
  executeRedisCommandRoute,
  executeSqlRoute,
  expireRedisKeyRoute,
  getDatabaseConnectionBySlugRoute,
  getDatabaseConnectionRoute,
  getDatabaseHealthHistoryRoute,
  getManagedDatabaseBindingRuntimeRoute,
  getManagedDatabaseRoute,
  getRedisKeyRoute,
  insertPostgresRowRoute,
  insertSqlRowRoute,
  listDatabaseConnectionsRoute,
  listDatabaseFoldersRoute,
  listManagedDatabaseBindingsRoute,
  listManagedDatabaseCatalogRoute,
  listManagedDatabasesRoute,
  listManagedPostgresExtensionsRoute,
  listPostgresSchemasRoute,
  listPostgresTablesRoute,
  listSqlNamespacesRoute,
  listSqlObjectsRoute,
  moveDatabaseFolderRoute,
  moveDatabasesToFolderRoute,
  pauseManagedDatabaseRoute,
  postgresTableMetadataRoute,
  reorderDatabaseFoldersRoute,
  reorderDatabasesRoute,
  restartManagedDatabaseRoute,
  retryManagedDatabaseProvisioningRoute,
  revealDatabaseCredentialsRoute,
  revealManagedDatabaseBindingCredentialsRoute,
  revealManagedDatabaseCredentialsRoute,
  rotateManagedDatabaseCertificateRoute,
  rotateManagedDatabaseDirectCredentialsRoute,
  scanRedisKeysRoute,
  setRedisKeyRoute,
  sqlTableMetadataRoute,
  testDatabaseConnectionRoute,
  unpauseManagedDatabaseRoute,
  updateDatabaseConnectionRoute,
  updateDatabaseFolderRoute,
  updateManagedDatabaseRoute,
  updatePostgresColumnTypeRoute,
  updatePostgresRowRoute,
  updateSqlRowRoute,
  AddPostgresColumnSchema,
  BrowsePostgresRowsQuerySchema,
  BrowseSqlRowsQuerySchema,
  CreateDatabaseConnectionSchema,
  CreateManagedDatabaseBindingSchema,
  CreateManagedDatabaseSchema,
  DatabaseListQuerySchema,
  DeleteManagedDatabaseBindingSchema,
  DeletePostgresColumnSchema,
  DeleteSqlRowSchema,
  ExecutePostgresSqlSchema,
  ExecuteRedisCommandSchema,
  ExecuteSqlSchema,
  InsertSqlRowSchema,
  PostgresObjectSchema,
  RedisExpireKeySchema,
  RedisGetKeyQuerySchema,
  RedisScanKeysQuerySchema,
  RedisSetKeySchema,
  SqlTableQuerySchema,
  UpdateDatabaseConnectionSchema,
  UpdateManagedDatabaseSchema,
  UpdatePostgresColumnTypeSchema,
  UpdateSqlRowSchema,
  DatabaseConnectionService,
  ManagedDatabaseBindingService,
  ManagedDatabaseService,
};
