/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b275c6ecd602e7014498f665492f9111)
interface __BaseEnv_Env {
	GITHUB_OWNER: "the-square-labs";
	GITHUB_GATEWAY_REPO: "gateway";
	GITHUB_INFERENCE_CORE_REPO: "inference-core";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_OWNER" | "GITHUB_GATEWAY_REPO" | "GITHUB_INFERENCE_CORE_REPO">> {}
}
