ALTER TABLE "docker_source_bindings" DROP CONSTRAINT "docker_source_bindings_target_shape_check";--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "application_root" text DEFAULT '.' NOT NULL;--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "package_manager" varchar(16);--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "package_manager_version" varchar(64);--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "node_version" varchar(16);--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "build_script" varchar(128);--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "artifact_directory" text;--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "publish_tag" varchar(63);--> statement-breakpoint
ALTER TABLE "docker_builds" ADD COLUMN "source_config_generation" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "page_project_id" uuid;--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "config_generation" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "application_root" text DEFAULT '.' NOT NULL;--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "package_manager" varchar(16);--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "package_manager_version" varchar(64);--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "node_version" varchar(16);--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "build_script" varchar(128);--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "artifact_directory" text;--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD COLUMN "publish_tag" varchar(63);--> statement-breakpoint
CREATE UNIQUE INDEX "docker_source_bindings_page_project_unique" ON "docker_source_bindings" USING btree ("page_project_id") WHERE "docker_source_bindings"."target_kind" = 'pages_project';--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD CONSTRAINT "docker_source_bindings_pages_build_config_check" CHECK (("docker_source_bindings"."target_kind" = 'pages_project' AND "docker_source_bindings"."package_manager" IN ('npm', 'pnpm', 'yarn') AND "docker_source_bindings"."node_version" IN ('20', '22', '24') AND "docker_source_bindings"."build_script" IS NOT NULL AND length(trim("docker_source_bindings"."build_script")) > 0 AND "docker_source_bindings"."artifact_directory" IS NOT NULL AND length(trim("docker_source_bindings"."artifact_directory")) > 0 AND "docker_source_bindings"."publish_tag" IS NOT NULL) OR ("docker_source_bindings"."target_kind" <> 'pages_project' AND "docker_source_bindings"."package_manager" IS NULL AND "docker_source_bindings"."package_manager_version" IS NULL AND "docker_source_bindings"."node_version" IS NULL AND "docker_source_bindings"."build_script" IS NULL AND "docker_source_bindings"."artifact_directory" IS NULL AND "docker_source_bindings"."publish_tag" IS NULL));--> statement-breakpoint
ALTER TABLE "docker_source_bindings" ADD CONSTRAINT "docker_source_bindings_target_shape_check" CHECK (("docker_source_bindings"."target_kind" = 'container' AND "docker_source_bindings"."node_id" IS NOT NULL AND "docker_source_bindings"."container_name" IS NOT NULL AND "docker_source_bindings"."deployment_id" IS NULL AND "docker_source_bindings"."compose_project_id" IS NULL AND "docker_source_bindings"."page_project_id" IS NULL AND "docker_source_bindings"."compose_file_path" IS NULL) OR ("docker_source_bindings"."target_kind" = 'deployment' AND "docker_source_bindings"."node_id" IS NULL AND "docker_source_bindings"."container_name" IS NULL AND "docker_source_bindings"."deployment_id" IS NOT NULL AND "docker_source_bindings"."compose_project_id" IS NULL AND "docker_source_bindings"."page_project_id" IS NULL AND "docker_source_bindings"."compose_file_path" IS NULL) OR ("docker_source_bindings"."target_kind" = 'compose_project' AND "docker_source_bindings"."node_id" IS NULL AND "docker_source_bindings"."container_name" IS NULL AND "docker_source_bindings"."deployment_id" IS NULL AND "docker_source_bindings"."compose_project_id" IS NOT NULL AND "docker_source_bindings"."page_project_id" IS NULL AND "docker_source_bindings"."compose_file_path" IS NOT NULL) OR ("docker_source_bindings"."target_kind" = 'pages_project' AND "docker_source_bindings"."node_id" IS NULL AND "docker_source_bindings"."container_name" IS NULL AND "docker_source_bindings"."deployment_id" IS NULL AND "docker_source_bindings"."compose_project_id" IS NULL AND "docker_source_bindings"."page_project_id" IS NOT NULL AND "docker_source_bindings"."compose_file_path" IS NULL));