import { OpenAPIHono } from '@hono/zod-openapi';
import { container } from '@/container.js';
import { openApiValidationHook } from '@/lib/openapi.js';
import { AppError } from '@/middleware/error-handler.js';
import { authMiddleware, requireScope } from '@/modules/auth/auth.middleware.js';
import {
  createStatusPageIncidentRoute,
  createStatusPageIncidentUpdateRoute,
  createStatusPageServiceRoute,
  deleteStatusPageIncidentRoute,
  deleteStatusPageServiceRoute,
  getStatusPagePreviewRoute,
  getStatusPageSettingsRoute,
  listStatusPageIncidentsRoute,
  listStatusPageProxyTemplatesRoute,
  listStatusPageServicesRoute,
  promoteStatusPageIncidentRoute,
  publicStatusPageRoute,
  reorderStatusPageServicesRoute,
  resolveStatusPageIncidentRoute,
  updateStatusPageIncidentRoute,
  updateStatusPageServiceRoute,
  updateStatusPageSettingsRoute,
} from './status-page.docs.js';
import {
  CreateStatusPageIncidentSchema,
  CreateStatusPageIncidentUpdateSchema,
  CreateStatusPageServiceSchema,
  IncidentListQuerySchema,
  ReorderStatusPageServicesSchema,
  StatusPageSettingsSchema,
  UpdateStatusPageIncidentSchema,
  UpdateStatusPageServiceSchema,
} from './status-page.schemas.js';
import { StatusPageService } from './status-page.service.js';
export const statusPageRouteRuntime = {
  OpenAPIHono,
  container,
  openApiValidationHook,
  AppError,
  authMiddleware,
  requireScope,
  createStatusPageIncidentRoute,
  createStatusPageIncidentUpdateRoute,
  createStatusPageServiceRoute,
  deleteStatusPageIncidentRoute,
  deleteStatusPageServiceRoute,
  getStatusPagePreviewRoute,
  getStatusPageSettingsRoute,
  listStatusPageIncidentsRoute,
  listStatusPageProxyTemplatesRoute,
  listStatusPageServicesRoute,
  promoteStatusPageIncidentRoute,
  publicStatusPageRoute,
  reorderStatusPageServicesRoute,
  resolveStatusPageIncidentRoute,
  updateStatusPageIncidentRoute,
  updateStatusPageServiceRoute,
  updateStatusPageSettingsRoute,
  CreateStatusPageIncidentSchema,
  CreateStatusPageIncidentUpdateSchema,
  CreateStatusPageServiceSchema,
  IncidentListQuerySchema,
  ReorderStatusPageServicesSchema,
  StatusPageSettingsSchema,
  UpdateStatusPageIncidentSchema,
  UpdateStatusPageServiceSchema,
  StatusPageService,
};
