import { and, asc, desc, eq, inArray, isNotNull, isNull, sql } from 'drizzle-orm';
import {
  aiConversationInputs,
  aiConversationMessages,
  aiConversations,
  aiPlanRevisions,
  aiPlans,
  aiRunCredentialChallenges,
  aiRunQuestions,
  aiRunSetupInteractions,
  aiRuns,
  aiRunToolCalls,
  aiRunToolRounds,
} from '@/db/schema/index.js';
import { AppError } from '@/middleware/error-handler.js';
import {
  ACTIVE_PLAN_STATUSES,
  ACTIVE_RUN_STATUSES,
  findRunByCommand,
  getActiveRunForUpdate,
  getOwnedConversation,
  nextMessageSequence,
  PRE_EXECUTION_PLAN_STATUSES,
  toConversationMessage,
} from './ai-run.shared.js';

export const aiRunCommercialRuntime = {
  and,
  asc,
  desc,
  eq,
  inArray,
  aiConversationInputs,
  aiConversationMessages,
  aiConversations,
  aiPlans,
  aiRunCredentialChallenges,
  aiRunQuestions,
  aiRunSetupInteractions,
  aiRuns,
  aiRunToolCalls,
  aiRunToolRounds,
  AppError,
  ACTIVE_RUN_STATUSES,
  findRunByCommand,
  getActiveRunForUpdate,
  getOwnedConversation,
  nextMessageSequence,
  toConversationMessage,
  isNotNull,
  isNull,
  sql,
  aiPlanRevisions,
  ACTIVE_PLAN_STATUSES,
  PRE_EXECUTION_PLAN_STATUSES,
};
