import { FOLDER_TOOL_REQUIREMENT_SCOPES } from './ai.folder-tool-scopes.js';

export const AI_BROAD_ONLY_TOOL_SCOPES = new Set<string>();
export const AI_DIRECT_DATABASE_VIEW_TOOLS = new Set(['list_databases', 'get_database_connection']);
export const AI_DIRECT_RAW_READ_TOOLS = new Set(['get_proxy_rendered_config']);
export const AI_DIRECT_DATABASE_VIEW_AND_QUERY_TOOLS = new Set([
  'query_postgres_read',
  'execute_postgres_sql',
  'browse_redis_keys',
  'get_redis_key',
  'set_redis_key',
  'execute_redis_command',
  'manage_postgres_data',
  'manage_redis_data',
]);

export const AI_TOOL_ANY_SCOPE_REQUIREMENTS: Readonly<Record<string, readonly string[]>> = {
  find_resource: [
    'feat:ai:use',
    'nodes:details',
    'proxy:view',
    'proxy:templates:view',
    'ssl:cert:view',
    'domains:view',
    'acl:view',
    'pki:ca:view:root',
    'pki:ca:view:intermediate',
    'pki:cert:view',
    'pki:templates:view',
    'docker:containers:view',
    'docker:images:view',
    'docker:volumes:view',
    'docker:networks:view',
    'docker:registries:view',
    'databases:view',
    'logs:environments:view',
    'logs:schemas:view',
    'status-page:view',
    'notifications:view',
  ],
  list_cas: ['pki:ca:view:root', 'pki:ca:view:intermediate'],
  get_ca: ['pki:ca:view:root', 'pki:ca:view:intermediate'],
  delete_ca: ['pki:ca:revoke:root', 'pki:ca:revoke:intermediate'],
  manage_ca: ['pki:ca:create:root', 'pki:ca:create:intermediate'],
  manage_certificate: ['pki:cert:view', 'pki:cert:issue', 'pki:cert:export'],
  manage_template: ['pki:templates:view', 'pki:templates:edit'],
  manage_proxy_template: [
    'proxy:templates:view',
    'proxy:templates:create',
    'proxy:templates:edit',
    'proxy:templates:delete',
  ],
  manage_ssl_certificate: ['ssl:cert:view', 'ssl:cert:issue', 'ssl:cert:delete'],
  manage_domain: ['domains:view', 'domains:edit'],
  manage_access_list: ['acl:view', 'acl:edit'],
  manage_docker_registry: [
    'docker:registries:view',
    'docker:registries:create',
    'docker:registries:edit',
    'docker:registries:delete',
  ],
  manage_docker_volume: ['docker:volumes:create', 'docker:volumes:delete'],
  manage_docker_network: ['docker:networks:create', 'docker:networks:edit', 'docker:networks:delete'],
  manage_docker_container_config: [
    'docker:containers:view',
    'docker:containers:environment',
    'docker:containers:files',
    'docker:containers:secrets',
    'docker:containers:webhooks',
    'docker:containers:config',
    'docker:containers:edit',
  ],
  manage_database_connection: [
    'databases:view',
    'databases:create',
    'databases:edit',
    'databases:delete',
    'databases:credentials:reveal',
  ],
  manage_postgres_data: ['databases:query:read', 'databases:query:write'],
  manage_redis_data: ['databases:query:read', 'databases:query:write', 'databases:query:admin'],
  manage_logging: [
    'logs:environments:view',
    'logs:environments:create',
    'logs:environments:edit',
    'logs:environments:delete',
    'logs:tokens:view',
    'logs:tokens:create',
    'logs:tokens:delete',
    'logs:schemas:view',
    'logs:schemas:create',
    'logs:schemas:edit',
    'logs:schemas:delete',
    'logs:read',
    'logs:manage',
  ],
  manage_status_page: [
    'status-page:view',
    'status-page:manage',
    'status-page:incidents:create',
    'status-page:incidents:update',
    'status-page:incidents:resolve',
    'status-page:incidents:delete',
  ],
  manage_inference_provider: ['inference:providers:view', 'inference:providers:manage'],
  manage_inference_token: ['inference:tokens:manage'],
  list_resource_folders: [...FOLDER_TOOL_REQUIREMENT_SCOPES],
  manage_resource_folder: [...FOLDER_TOOL_REQUIREMENT_SCOPES],
  manage_node_config: ['nodes:config:view', 'nodes:config:edit'],
  manage_node_file: ['nodes:files:read', 'nodes:files:write'],
};
