import { MCP_TOKEN_SCOPES } from '@/lib/scopes.js';
import { FOLDER_TOOL_REQUIREMENT_SCOPES } from './ai.folder-tool-scopes.js';

export const AI_BROAD_ONLY_TOOL_SCOPES = new Set<string>();
export const AI_DIRECT_DATABASE_VIEW_TOOLS = new Set(['list_databases', 'get_database_connection']);
export const AI_DIRECT_RAW_READ_TOOLS = new Set(['get_route_rendered_config']);
export const AI_DIRECT_DATABASE_VIEW_AND_QUERY_TOOLS = new Set([
  'query_postgres_read',
  'execute_postgres_sql',
  'browse_redis_keys',
  'get_redis_key',
  'set_redis_key',
  'execute_redis_command',
  'manage_postgres_data',
  'manage_redis_data',
]);

export const AI_TOOL_ANY_SCOPE_REQUIREMENTS: Readonly<Record<string, readonly string[]>> = {
  manage_database_backups: [
    'databases:backups:view',
    'databases:backups:manage',
    'databases:backups:run',
    'databases:backups:restore',
  ],
  manage_storage_connection: [
    'storage:view',
    'storage:create',
    'storage:edit',
    'storage:delete',
    'storage:credentials:reveal',
  ],
  manage_storage_objects: ['storage:objects:read', 'storage:objects:write', 'storage:objects:admin'],
  manage_managed_storage: [
    'storage:view',
    'storage:create',
    'storage:edit',
    'storage:delete',
    'storage:iam',
    'storage:credentials:reveal',
  ],
  read_gateway_documentation: MCP_TOKEN_SCOPES,
  manage_docker_compose: [
    'docker:compose:view',
    'docker:compose:create',
    'docker:compose:manage',
    'docker:compose:delete',
  ],
  manage_docker_source: [
    'docker:containers:view',
    'docker:containers:create',
    'docker:containers:edit',
    'docker:containers:manage',
    'docker:compose:view',
    'docker:compose:create',
    'docker:compose:manage',
    'pages:view',
    'pages:edit',
    'pages:deploy',
  ],
  manage_docker_build: [
    'docker:containers:view',
    'docker:containers:manage',
    'docker:compose:view',
    'docker:compose:manage',
    'pages:view',
    'pages:deploy',
  ],
  list_docker_builds: ['docker:containers:view', 'docker:compose:view', 'pages:view'],
  find_resource: [
    'ai:workspace:use',
    'nodes:details',
    'proxy:view',
    'proxy:templates:view',
    'ssl:cert:view',
    'domains:view',
    'acl:view',
    'pki:ca:view:root',
    'pki:ca:view:intermediate',
    'pki:cert:view',
    'pki:templates:view',
    'docker:containers:view',
    'docker:images:view',
    'docker:volumes:view',
    'docker:networks:view',
    'docker:registries:view',
    'databases:view',
    'pages:view',
    'logs:environments:view',
    'logs:schemas:view',
    'status-page:view',
    'notifications:view',
  ],
  list_cas: ['pki:ca:view:root', 'pki:ca:view:intermediate', 'pki:cert:issue'],
  get_ca: ['pki:ca:view:root', 'pki:ca:view:intermediate'],
  delete_ca: ['pki:ca:revoke:root', 'pki:ca:revoke:intermediate'],
  manage_ca: ['pki:ca:create:root', 'pki:ca:create:intermediate', 'pki:ca:revoke:root', 'pki:ca:revoke:intermediate'],
  manage_certificate: ['pki:cert:view', 'pki:cert:issue', 'pki:cert:export'],
  manage_template: ['pki:templates:view', 'pki:templates:edit'],
  manage_proxy_template: [
    'proxy:templates:view',
    'proxy:templates:create',
    'proxy:templates:edit',
    'proxy:templates:delete',
  ],
  manage_ssl_certificate: ['ssl:cert:view', 'ssl:cert:issue', 'ssl:cert:delete'],
  manage_domain: ['domains:view', 'domains:edit', 'domains:create'],
  manage_access_list: ['acl:view', 'acl:edit'],
  manage_docker_registry: [
    'docker:registries:view',
    'docker:registries:create',
    'docker:registries:edit',
    'docker:registries:delete',
  ],
  manage_docker_volume: [
    'docker:volumes:create',
    'docker:volumes:delete',
    'docker:volumes:view',
    'docker:volumes:files:read',
    'docker:volumes:files:write',
    'docker:containers:mounts',
  ],
  // The handlers enforce the exact per-provider route scope.
  list_integration_connectors: [
    'integrations:gitlab:view',
    'integrations:gitlab:manage',
    'integrations:github:view',
    'integrations:git:view',
    'integrations:cloudflare:view',
    'integrations:ssh:view',
  ],
  sync_integration_connector: [
    'integrations:gitlab:sync',
    'integrations:gitlab:manage',
    'integrations:cloudflare:sync',
    'integrations:cloudflare:manage',
    'integrations:github:sync',
    'integrations:github:manage',
    'integrations:git:sync',
    'integrations:git:manage',
    'integrations:ssh:manage',
  ],
  manage_docker_network: ['docker:networks:create', 'docker:networks:edit', 'docker:networks:delete'],
  manage_docker_deployment: ['docker:containers:create', 'docker:containers:edit', 'docker:containers:delete'],
  manage_docker_container_config: [
    'docker:containers:view',
    'docker:containers:environment',
    'docker:containers:files:read',
    'docker:containers:files:write',
    'docker:containers:secrets',
    'docker:containers:webhooks',
    'docker:containers:config',
    'docker:containers:edit',
  ],
  // Docker creation routes use requireScopeBase; the services check the node or folder destination.
  create_docker_container: ['docker:containers:create'],
  duplicate_docker_container: ['docker:containers:create'],
  pull_docker_image: ['docker:images:pull'],
  upload_docker_container_archive: ['docker:containers:create'],
  manage_docker_container: [
    'docker:containers:view',
    'docker:containers:edit',
    'docker:containers:manage',
    'docker:containers:create',
  ],
  download_docker_archive: ['docker:containers:export', 'docker:volumes:export'],
  // The Availability service authorizes the workload; mutations also need docker:availability:manage.
  manage_docker_availability: ['docker:availability:manage', 'docker:containers:view', 'docker:compose:view'],
  // Migration routes: preflight/start are authorized by the service, reads need docker:tasks, changes :manage.
  manage_docker_migration: ['docker:containers:migrate', 'docker:tasks', 'docker:tasks:manage'],
  manage_database_connection: [
    'databases:view',
    'databases:create',
    'databases:edit',
    'databases:delete',
    'databases:credentials:reveal',
  ],
  manage_managed_database: [
    'databases:view',
    'databases:create',
    'databases:edit',
    'databases:delete',
    'databases:credentials:reveal',
  ],
  manage_pages: [
    'pages:view',
    'pages:create',
    'pages:edit',
    'pages:delete',
    'pages:deployments:manage',
    'pages:tags:manage',
    'pages:tokens:manage',
    'pages:settings:view',
    'pages:settings:edit',
    'pages:folders:manage',
  ],
  manage_additional_route: ['proxy:view', 'proxy:edit'],
  manage_additional_secure_link: ['proxy:view', 'proxy:edit'],
  // The handler checks the destination with hasScopeForCreation, like POST /proxy-hosts.
  create_route: ['proxy:create'],
  manage_route: ['proxy:view', 'proxy:advanced', 'proxy:raw:write', 'proxy:maintenance:bypass'],
  manage_postgres_data: ['databases:query:read', 'databases:query:write'],
  manage_redis_data: ['databases:query:read', 'databases:query:write', 'databases:query:admin'],
  manage_logging: [
    'logs:environments:view',
    'logs:environments:create',
    'logs:environments:edit',
    'logs:environments:delete',
    'logs:tokens:view',
    'logs:tokens:create',
    'logs:tokens:delete',
    'logs:schemas:view',
    'logs:schemas:create',
    'logs:schemas:edit',
    'logs:schemas:delete',
    'logs:read',
    'logs:manage',
    'housekeeping:view',
  ],
  manage_status_page: [
    'status-page:view',
    'status-page:manage',
    'status-page:incidents:create',
    'status-page:incidents:update',
    'status-page:incidents:resolve',
    'status-page:incidents:delete',
  ],
  manage_inference_provider: ['inference:providers:view', 'inference:providers:manage'],
  manage_inference_token: ['feat:ai:use'],
  manage_inference_usage: ['feat:ai:use', 'inference:usage:view'],
  // Notification routes accept the granular notifications:* scopes as alternatives to view/manage.
  list_alert_rules: ['notifications:alerts:view', 'notifications:view', 'notifications:manage'],
  get_alert_rule: ['notifications:alerts:view', 'notifications:view', 'notifications:manage'],
  create_alert_rule: ['notifications:alerts:create', 'notifications:manage'],
  update_alert_rule: ['notifications:alerts:edit', 'notifications:manage'],
  delete_alert_rule: ['notifications:alerts:delete', 'notifications:manage'],
  list_webhooks: ['notifications:webhooks:view', 'notifications:view', 'notifications:manage'],
  create_webhook: ['notifications:webhooks:create', 'notifications:manage'],
  update_webhook: ['notifications:webhooks:edit', 'notifications:manage'],
  delete_webhook: ['notifications:webhooks:delete', 'notifications:manage'],
  test_webhook: ['notifications:webhooks:edit', 'notifications:manage'],
  list_webhook_deliveries: ['notifications:deliveries:view', 'notifications:view', 'notifications:manage'],
  get_delivery_stats: ['notifications:deliveries:view', 'notifications:view', 'notifications:manage'],
  manage_notifications: [
    'notifications:view',
    'notifications:manage',
    'notifications:alerts:view',
    'notifications:alerts:create',
    'notifications:alerts:edit',
    'notifications:alerts:delete',
    'notifications:webhooks:view',
    'notifications:webhooks:create',
    'notifications:webhooks:edit',
    'notifications:webhooks:delete',
    'notifications:deliveries:view',
  ],
  gitlab_sync_connector: ['integrations:gitlab:sync', 'integrations:gitlab:manage'],
  // The handler enforces the exact per-provider route scope.
  manage_integration_connector: [
    'integrations:gitlab:view',
    'integrations:gitlab:manage',
    'integrations:github:view',
    'integrations:github:manage',
    'integrations:git:view',
    'integrations:git:manage',
    'integrations:cloudflare:view',
    'integrations:cloudflare:manage',
    'integrations:ssh:view',
    'integrations:ssh:manage',
  ],
  // The hosting services enforce each operation's exact scopes, like the hosting routes.
  manage_hosting: [
    'integrations:hosting:view',
    'integrations:hosting:manage',
    'hosting:resources:view',
    'hosting:resources:create',
    'hosting:resources:power',
    'hosting:resources:resize',
    'hosting:resources:delete',
    'hosting:resources:recover',
    'hosting:snapshots:view',
    'hosting:snapshots:create',
    'hosting:snapshots:delete',
    'hosting:snapshots:restore',
    'hosting:snapshots:folders:manage',
    'hosting:billing:view',
    'nodes:details',
  ],
  list_resource_folders: [...FOLDER_TOOL_REQUIREMENT_SCOPES],
  manage_resource_folder: [...FOLDER_TOOL_REQUIREMENT_SCOPES],
  manage_node_config: ['nodes:config:view', 'nodes:config:edit'],
  // The handlers enforce the exact per-node or admin:system scope of each route.
  manage_node: ['nodes:details', 'nodes:rename', 'nodes:create', 'nodes:logs', 'nodes:config:edit'],
  manage_user: ['admin:users', 'admin:system'],
  manage_relay_pool: ['settings:gateway:view', 'admin:system'],
  manage_node_file: ['nodes:files:read', 'nodes:files:write'],
};
