import type { AIToolDefinition } from './ai.types.js';

export const RESOURCE_SETUP_AI_TOOLS: AIToolDefinition[] = [
  {
    name: 'manage_pages',
    description:
      'Inspect and manage Pages profiles, Projects, Deployments, Tags, and runtime configuration. Pages must be licensed and enabled for runtime-changing operations. Artifact bytes are uploaded through the resumable deploy API, not this metadata tool.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'profile_get',
            'profile_options',
            'profile_configure',
            'profile_disable',
            'project_list',
            'project_get',
            'project_create',
            'project_update',
            'project_migrate',
            'project_delete',
            'deployment_list',
            'deployment_get',
            'deployment_pin',
            'deployment_delete',
            'tag_list',
            'tag_move',
            'tag_delete',
            'config_list',
            'config_save_default',
            'config_save_tag',
            'config_reset_tag',
          ],
        },
        projectId: { type: 'string', description: 'Page Project UUID.' },
        deploymentId: { type: 'string', description: 'Page Deployment UUID.' },
        tagId: { type: 'string', description: 'Page Tag UUID for runtime config overrides.' },
        tag: { type: 'string', description: 'Mutable Tag name for move/delete.' },
        page: { type: 'number' },
        limit: { type: 'number' },
        search: { type: 'string' },
        folderId: { type: 'string' },
        name: { type: 'string' },
        description: { type: 'string' },
        nodeId: { type: 'string' },
        targetNodeId: { type: 'string' },
        appearanceColor: { type: 'string' },
        maxDeployments: { type: 'number' },
        storageQuotaBytes: { type: 'number' },
        pinned: { type: 'boolean' },
        source: { type: 'string', description: 'Valid JSON object source assigned to window.runtime.config.' },
        expectedGeneration: { type: 'number' },
        enabled: { type: 'boolean' },
        domainId: { type: 'string' },
        certificateId: { type: 'string' },
        labelTemplate: { type: 'string' },
        acknowledgeSameRegistrableDomain: { type: 'boolean' },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Pages',
    requiredScope: 'pages:view',
    invalidateStores: ['pages', 'proxy-hosts'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_additional_route',
    description:
      'List, inspect, create, update, retry, or delete one path-based Additional Route on a managed ingress Route. Docker targets automatically provision route-owned Secure Links; Pages targets reference a Page Project Tag.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['list', 'get', 'create', 'update', 'retry', 'delete'] },
        proxyHostId: { type: 'string' },
        routeId: { type: 'string' },
        path: { type: 'string' },
        enabled: { type: 'boolean' },
        targetKind: { type: 'string', enum: ['manual', 'docker_container', 'docker_deployment', 'pages'] },
        forwardHost: { type: 'string' },
        forwardPort: { type: 'number' },
        forwardScheme: { type: 'string', enum: ['http', 'https'] },
        dockerNodeId: { type: 'string' },
        dockerContainerName: { type: 'string' },
        dockerDeploymentId: { type: 'string' },
        dockerContainerPort: { type: 'number' },
        pageProjectId: { type: 'string' },
        pageTagId: { type: 'string' },
        advancedConfig: { type: 'string' },
        stripPrefix: { type: 'boolean' },
        websocketSupport: { type: 'boolean' },
        requestBuffering: { type: 'boolean' },
        responseBuffering: { type: 'boolean' },
        connectTimeoutSeconds: { type: 'number' },
        readTimeoutSeconds: { type: 'number' },
        sendTimeoutSeconds: { type: 'number' },
      },
      required: ['operation', 'proxyHostId'],
    },
    destructive: true,
    category: 'Ingress',
    requiredScope: 'proxy:view',
    invalidateStores: ['proxy-hosts'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_additional_secure_link',
    description:
      'List, create, retry, or delete user-managed Additional Secure Link Bindings for a managed ingress Route. Route-owned bindings are managed only through manage_additional_route and cannot be deleted here.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['list', 'create', 'retry', 'delete'] },
        proxyHostId: { type: 'string' },
        bindingId: { type: 'string' },
        name: { type: 'string' },
        upstreamKind: { type: 'string', enum: ['docker_container', 'docker_deployment'] },
        forwardScheme: { type: 'string', enum: ['http', 'https'] },
        dockerNodeId: { type: 'string' },
        dockerContainerName: { type: 'string' },
        dockerDeploymentId: { type: 'string' },
        dockerContainerPort: { type: 'number' },
      },
      required: ['operation', 'proxyHostId'],
    },
    destructive: true,
    category: 'Ingress',
    requiredScope: 'proxy:view',
    invalidateStores: ['proxy-hosts'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_managed_database',
    description:
      'Provision and manage Gateway-managed Postgres, Redis, or ClickHouse instances and their workload bindings. Read the catalog before create, poll get until ready, and create a binding only after the database is ready. This tool never reveals credentials.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'catalog',
            'list',
            'get',
            'create',
            'retry',
            'delete',
            'list_bindings',
            'create_binding',
            'delete_binding',
          ],
        },
        databaseId: { type: 'string', description: 'Managed database instance ID.' },
        bindingId: { type: 'string', description: 'Managed database binding ID.' },
        name: { type: 'string' },
        type: { type: 'string', enum: ['postgres', 'redis', 'clickhouse'] },
        version: { type: 'string', description: 'Exact version returned by catalog.' },
        nodeId: { type: 'string', description: 'Database node ID for create, or optional list filter.' },
        storageSizeGb: { type: 'number' },
        cpuCores: { type: 'number' },
        memoryMb: { type: 'number' },
        swapMb: { type: 'number' },
        tags: { type: 'array', items: { type: 'string' } },
        publishTcp: {
          type: 'boolean',
          description: 'Keep false unless the user explicitly needs external TCP access.',
        },
        publishNativeTcp: { type: 'boolean' },
        publishedPort: { type: 'number' },
        publishedNativePort: { type: 'number' },
        tlsEnabled: { type: 'boolean' },
        databaseName: { type: 'string' },
        ownerUsername: { type: 'string' },
        targetNodeId: { type: 'string' },
        targetType: { type: 'string', enum: ['container', 'deployment'] },
        targetResourceId: { type: 'string' },
        environment: {
          type: 'object',
          description:
            'Optional environment variable names for connectionUri, host, port, database, username, and password.',
        },
        replaceExistingEnvironment: { type: 'boolean' },
        targetEnvironment: {
          type: 'object',
          description: 'Complete ordinary-container environment draft when the binding changes it.',
        },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Managed Databases',
    requiredScope: 'databases:view',
    invalidateStores: ['databases', 'containers'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_docker_migration',
    description:
      'Preflight, start, inspect, cancel, or retry cleanup for a Gateway Docker container/deployment migration. Always preflight first and pass its exact fingerprint to start. A migration requires an existing source workload and a distinct target Docker node.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['preflight', 'start', 'get', 'cancel', 'retry_cleanup'] },
        migrationId: { type: 'string' },
        resource: {
          type: 'object',
          properties: {
            type: { type: 'string', enum: ['container', 'deployment'] },
            containerName: { type: 'string' },
            deploymentId: { type: 'string' },
          },
          required: ['type'],
        },
        sourceNodeId: { type: 'string' },
        targetNodeId: { type: 'string' },
        keepSource: { type: 'boolean' },
        preflightFingerprint: { type: 'string' },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Docker Migration',
    requiredScope: 'docker:containers:migrate',
    invalidateStores: ['containers', 'docker-deployments', 'docker-tasks'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_logging_backend',
    description:
      'Inspect or configure the structured-logging ClickHouse backend. On an empty Gateway, enable_local provisions the Gateway-managed local ClickHouse backend before creating logging environments or schemas. Use configure_external only with user-supplied connection details.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['get', 'enable_local', 'configure_external', 'disable'] },
        url: { type: 'string' },
        username: { type: 'string' },
        password: { type: 'string' },
        database: { type: 'string' },
        table: { type: 'string' },
        requestTimeoutMs: { type: 'number' },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Logging Backend',
    requiredScope: 'settings:gateway:view',
    invalidateStores: ['settings', 'logging'],
    historyRetention: { mode: 'summary_only' },
  },
];
