import type { AIToolDefinition } from './ai.types.js';

export const HOSTING_AI_TOOLS: AIToolDefinition[] = [
  {
    name: 'manage_hosting',
    description:
      'Manage hosting provider accounts and the VMs they run, with the same checks as the hosting API (each operation enforces its own integrations:hosting:*, hosting:*, and node scopes). Accounts: connector_list, connector_get, connector_configuration, connector_preview (test credentials before saving; input = create body), connector_discover (input = discovery body), connector_create (input = create body), connector_update (input = update body), connector_delete, connector_test, connector_sync, catalog, resources, adoption_candidates, adopt (input {resourceId, nodeId}), operations_list, account_summary (balance and costs; needs hosting:billing:view). Nodes: node_bindings, node_get, node_firewall_get, node_firewall_update (input = firewall body). Provisioning: provision (input = order body with the confirmedPrice from catalog; the provider charges the account credit), operation_get, operation_reconcile, operation_retry_install (input {idempotencyKey, sshConnectorId?}). VMs: resource_action (input {action: start|shutdown|reboot|resize|delete|recover, idempotencyKey, expectedIncarnation, confirmed: true, ...}), snapshots_list, snapshot_folders, snapshot_action (input {action: create|delete|restore, confirmed: true, ...}), snapshot_folder_action (folderOperation create|rename|delete|reorder-folders|move-resources|reorder-resources, folderId, input). Account top-up is not available (payment actions were removed from the API).',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'connector_list',
            'connector_get',
            'connector_configuration',
            'connector_preview',
            'connector_discover',
            'connector_create',
            'connector_update',
            'connector_delete',
            'connector_test',
            'connector_sync',
            'catalog',
            'resources',
            'adoption_candidates',
            'adopt',
            'operations_list',
            'account_summary',
            'node_bindings',
            'node_get',
            'node_firewall_get',
            'node_firewall_update',
            'provision',
            'operation_get',
            'operation_reconcile',
            'operation_retry_install',
            'resource_action',
            'snapshots_list',
            'snapshot_folders',
            'snapshot_action',
            'snapshot_folder_action',
          ],
        },
        connectorId: { type: 'string', description: 'Hosting account (connector) UUID' },
        nodeId: { type: 'string', description: 'Gateway node UUID bound to a hosting VM' },
        operationId: { type: 'string', description: 'Hosting operation UUID' },
        resourceId: { type: 'string', description: 'Hosting VM (resource) UUID' },
        folderId: { type: 'string', description: 'Snapshot folder UUID for snapshot_folder_action' },
        folderOperation: {
          type: 'string',
          enum: ['create', 'rename', 'delete', 'reorder-folders', 'move-resources', 'reorder-resources'],
        },
        input: { type: 'object', description: 'Request body of the matching hosting API call' },
      },
      required: ['operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Hosting',
    requiredScope: 'integrations:hosting:view',
    invalidateStores: ['integrations', 'nodes'],
  },
];
