import type { AIToolDefinition } from './ai.types.js';

const integrationConnectorProviderSchema = {
  type: 'string',
  enum: ['gitlab', 'github', 'git', 'cloudflare', 'ssh'],
  description: 'Connector provider: gitlab, github, git (generic Git), cloudflare, or ssh (external SSH).',
};

const allowlistEntrySchema = {
  type: 'object',
  properties: {
    entryType: { type: 'string', enum: ['group', 'project'] },
    remoteId: { type: 'string' },
    fullPath: { type: 'string' },
    name: { type: 'string' },
    webUrl: { type: ['string', 'null'] },
  },
  required: ['entryType', 'remoteId', 'fullPath'],
};

const gitLabSettingsSchema = {
  type: 'object',
  properties: {
    autoSyncEnabled: { type: 'boolean' },
    autoSyncIntervalSeconds: { type: 'number' },
    cloneShallow: { type: 'boolean' },
    cloneDepth: { type: 'number' },
    cloneLfs: { type: 'boolean' },
    cloneSubmodules: { type: 'boolean' },
    cloneMaxSizeMb: { type: 'number' },
    cloneTimeoutSeconds: { type: 'number' },
  },
};

const cloudflareSettingsSchema = {
  type: 'object',
  properties: {
    autoSyncEnabled: { type: 'boolean' },
    autoSyncIntervalSeconds: { type: 'number' },
    defaultTtl: { type: 'number' },
    defaultProxied: { type: 'boolean' },
  },
};

const repositoryFields = {
  name: { type: 'string', description: 'Connector name.' },
  baseUrl: { type: 'string', description: 'Provider or Git host base URL.' },
  repositoryUrls: {
    type: 'array',
    items: { type: 'string' },
    description: 'One or more repository URLs available through this connector.',
  },
};

export const INTEGRATION_AI_TOOLS: AIToolDefinition[] = [
  {
    name: 'github_list_connectors',
    description: 'List GitHub connectors without exposing credentials.',
    parameters: { type: 'object', properties: {} },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:view',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'git_list_connectors',
    description: 'List generic Git connectors without exposing credentials.',
    parameters: { type: 'object', properties: {} },
    destructive: false,
    category: 'Git',
    requiredScope: 'integrations:git:view',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'github_list_repositories',
    description:
      'List repositories visible to the authorized GitHub account. Use an exact connector UUID from github_list_connectors.',
    parameters: {
      type: 'object',
      properties: { connectorId: { type: 'string' } },
      required: ['connectorId'],
    },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'github_list_repository_tree',
    description:
      'List files or directories in an allowed GitHub repository. Use an exact connector UUID from github_list_connectors and an allowed repository URL.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        path: { type: 'string' },
        ref: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl'],
    },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'github_read_repository_file',
    description:
      'Read one text file up to 256 KiB from an allowed GitHub repository. Use an exact connector UUID and repository URL.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        path: { type: 'string' },
        ref: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl', 'path'],
    },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'recent_full', maxBytes: 262144 },
  },
  {
    name: 'github_list_branches',
    description: 'List branches in a GitHub repository visible through the selected connector.',
    parameters: {
      type: 'object',
      properties: { connectorId: { type: 'string' }, repositoryUrl: { type: 'string' } },
      required: ['connectorId', 'repositoryUrl'],
    },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'github_list_workflow_runs',
    description: 'List recent GitHub Actions workflow runs for an allowed repository.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        branch: { type: 'string' },
        status: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl'],
    },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'github_list_actions_variables',
    description:
      'List GitHub Actions repository variables and their current values. Variable values are secrets, so this needs integrations:github:repo:write.',
    parameters: {
      type: 'object',
      properties: { connectorId: { type: 'string' }, repositoryUrl: { type: 'string' } },
      required: ['connectorId', 'repositoryUrl'],
    },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:write',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'github_list_actions_secrets',
    description: 'List GitHub Actions repository secret names and timestamps. Secret values are never returned.',
    parameters: {
      type: 'object',
      properties: { connectorId: { type: 'string' }, repositoryUrl: { type: 'string' } },
      required: ['connectorId', 'repositoryUrl'],
    },
    destructive: false,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'github_upsert_repository_file',
    description:
      'Create or update one text file up to 512 KiB in an allowed GitHub repository. Use for an explicitly requested, approved repository or CI configuration change.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        path: { type: 'string' },
        branch: { type: 'string' },
        message: { type: 'string' },
        content: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl', 'path', 'branch', 'message', 'content'],
    },
    destructive: true,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:write',
    invalidateStores: ['integrations'],
    effect: 'write',
    approvalClass: 'update',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'github_upsert_actions_variable',
    description: 'Create or update one GitHub Actions repository variable after explicit approval.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        name: { type: 'string' },
        value: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl', 'name', 'value'],
    },
    destructive: true,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:write',
    invalidateStores: [],
    effect: 'write',
    approvalClass: 'update',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'github_upsert_actions_secret',
    description:
      'Create or update one GitHub Actions repository secret after explicit approval. The value is encrypted for GitHub and never returned.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        name: { type: 'string' },
        value: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl', 'name', 'value'],
    },
    destructive: true,
    category: 'GitHub',
    requiredScope: 'integrations:github:repo:write',
    invalidateStores: [],
    effect: 'write',
    approvalClass: 'update',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'git_list_remote_refs',
    description:
      'Check an allowed generic Git repository and list its advertised branches and tags without exposing connector credentials.',
    parameters: {
      type: 'object',
      properties: { connectorId: { type: 'string' }, repositoryUrl: { type: 'string' } },
      required: ['connectorId', 'repositoryUrl'],
    },
    destructive: false,
    category: 'Git',
    requiredScope: 'integrations:git:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'git_list_repository_tree',
    description:
      'List files and directories from an allowed generic Git repository using a temporary shallow checkout.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        path: { type: 'string' },
        ref: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl'],
    },
    destructive: false,
    category: 'Git',
    requiredScope: 'integrations:git:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'git_read_repository_file',
    description: 'Read one text file up to 256 KiB from an allowed generic Git repository.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        path: { type: 'string' },
        ref: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl', 'path'],
    },
    destructive: false,
    category: 'Git',
    requiredScope: 'integrations:git:repo:read',
    invalidateStores: [],
    historyRetention: { mode: 'recent_full', maxBytes: 262144 },
  },
  {
    name: 'git_upsert_repository_file',
    description:
      'Create or update one text file in an existing branch of an allowed generic Git repository and push the commit after explicit approval.',
    parameters: {
      type: 'object',
      properties: {
        connectorId: { type: 'string' },
        repositoryUrl: { type: 'string' },
        path: { type: 'string' },
        branch: { type: 'string' },
        message: { type: 'string' },
        content: { type: 'string' },
      },
      required: ['connectorId', 'repositoryUrl', 'path', 'branch', 'message', 'content'],
    },
    destructive: true,
    category: 'Git',
    requiredScope: 'integrations:git:repo:write',
    invalidateStores: [],
    effect: 'write',
    approvalClass: 'update',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'create_github_token_connector',
    description:
      'Create an account-wide GitHub PAT connector only when the user already supplied its name, GitHub base URL, and token. If credentials are missing, use open_connector_setup instead. OAuth always uses open_connector_setup.',
    parameters: {
      type: 'object',
      properties: {
        name: { type: 'string', description: 'Connector name.' },
        baseUrl: { type: 'string', description: 'GitHub base URL.' },
        token: { type: 'string', description: 'GitHub personal access token.' },
        enabled: { type: 'boolean', description: 'Default true.' },
      },
      required: ['name', 'baseUrl', 'token'],
    },
    destructive: true,
    category: 'GitHub',
    requiredScope: 'integrations:github:manage',
    invalidateStores: ['integrations'],
    effect: 'write',
    approvalClass: 'create',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'create_git_connector',
    description:
      'Create a generic HTTPS Git connector only when the user already supplied every field, including username and token/password. If anything is missing, use open_connector_setup instead.',
    parameters: {
      type: 'object',
      properties: {
        ...repositoryFields,
        username: { type: 'string', description: 'Git HTTP username.' },
        token: { type: 'string', description: 'Git access token or HTTP password.' },
        allowlistEntries: { type: 'array', items: allowlistEntrySchema, description: 'Explicit repository entries.' },
        enabled: { type: 'boolean', description: 'Default true.' },
      },
      required: ['name', 'baseUrl', 'repositoryUrls', 'username', 'token'],
    },
    destructive: true,
    category: 'Git',
    requiredScope: 'integrations:git:manage',
    invalidateStores: ['integrations'],
    effect: 'write',
    approvalClass: 'create',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'create_gitlab_connector',
    description:
      'Create an instance-scoped GitLab connector only when name, base URL, and PAT are already known. If credentials are missing or the user may prefer repository-scoped generic Git, ask first and then use open_connector_setup.',
    parameters: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        baseUrl: { type: 'string' },
        token: { type: 'string' },
        enabled: { type: 'boolean', description: 'Default true.' },
        allowlistMode: {
          type: 'string',
          enum: ['selected', 'all_visible'],
          description: 'Default all_visible, or selected when allowlistEntries are given.',
        },
        allowlistEntries: { type: 'array', items: allowlistEntrySchema },
        settings: gitLabSettingsSchema,
      },
      required: ['name', 'baseUrl', 'token'],
    },
    destructive: true,
    category: 'GitLab',
    requiredScope: 'integrations:gitlab:manage',
    invalidateStores: ['integrations'],
    effect: 'write',
    approvalClass: 'create',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'create_cloudflare_connector',
    description:
      'Create a Cloudflare connector only when the user already supplied its name and API token. If the token is missing, use open_connector_setup instead.',
    parameters: {
      type: 'object',
      properties: {
        name: { type: 'string' },
        token: { type: 'string' },
        enabled: { type: 'boolean', description: 'Default true.' },
        settings: cloudflareSettingsSchema,
      },
      required: ['name', 'token'],
    },
    destructive: true,
    category: 'Cloudflare',
    requiredScope: 'integrations:cloudflare:manage',
    invalidateStores: ['integrations'],
    effect: 'write',
    approvalClass: 'create',
    historyRetention: { mode: 'never_full' },
  },
  {
    name: 'list_integration_connectors',
    description:
      'List integration connectors (GitLab, GitHub, generic Git, Cloudflare, external SSH) with their IDs, enabled state, and last sync or test status. Never returns credentials. Without provider, lists every provider the caller may view and skips the rest; providers that cannot be listed (for example unlicensed GitLab) appear under unavailableProviders. Pass the returned provider and id to sync_integration_connector.',
    parameters: {
      type: 'object',
      properties: {
        provider: integrationConnectorProviderSchema,
        enabled: { type: 'boolean', description: 'Return only enabled (true) or only disabled (false) connectors.' },
      },
    },
    destructive: false,
    category: 'Integrations',
    requiredScope: 'integrations:cloudflare:view',
    invalidateStores: [],
    effect: 'read',
    approvalClass: 'read',
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'sync_integration_connector',
    description:
      'Resync one integration connector now, with the same permission checks as its REST sync route: integrations:<provider>:manage (cloudflare also accepts integrations:cloudflare:sync). gitlab refreshes visible projects and registries. cloudflare refreshes zones and capabilities. github and git re-validate the connector credential and repository allowlist. ssh re-tests the external SSH connection and requires integrations:ssh:manage. Per-user Git credentials are never used or changed. Get provider and connectorId from list_integration_connectors.',
    parameters: {
      type: 'object',
      properties: {
        provider: integrationConnectorProviderSchema,
        connectorId: {
          type: 'string',
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
          description: 'Exact connector UUID returned by list_integration_connectors.',
        },
      },
      required: ['provider', 'connectorId'],
    },
    destructive: false,
    category: 'Integrations',
    requiredScope: 'integrations:gitlab:manage',
    invalidateStores: [],
    effect: 'write',
    approvalClass: 'update',
    targetIdentity: { resourceType: 'integration-connector', arguments: ['connectorId'] },
    historyRetention: { mode: 'persistent_context' },
  },
  {
    name: 'manage_integration_connector',
    description:
      'Manage one integration connector with the same permission checks as its REST route. Operations by provider: gitlab: get, update, delete, test, preview_test, rotate_token, capabilities, allowlist_search, allowlist_options, allowlist_refresh, allowlist_preview_search. cloudflare: get, update, delete, test, preview_test, rotate_token, list_zones. github and git: update, delete, test, preview_test. ssh: update (name only), delete, test, discover_host_key. preview_test, allowlist_preview_search, and discover_host_key take no connectorId. Update fields: name, baseUrl, enabled, token, username, allowlistMode, allowlistEntries, settings (each provider accepts its own subset). Credentials are never returned. Per-user Git credentials are not managed here.',
    parameters: {
      type: 'object',
      properties: {
        provider: integrationConnectorProviderSchema,
        operation: {
          type: 'string',
          enum: [
            'get',
            'update',
            'delete',
            'test',
            'preview_test',
            'rotate_token',
            'capabilities',
            'list_zones',
            'allowlist_search',
            'allowlist_options',
            'allowlist_refresh',
            'allowlist_preview_search',
            'discover_host_key',
          ],
        },
        connectorId: { type: 'string', description: 'Connector UUID from list_integration_connectors.' },
        name: { type: 'string' },
        baseUrl: { type: 'string' },
        enabled: { type: 'boolean' },
        token: { type: 'string', description: 'New or candidate credential (update, rotate_token, preview_test).' },
        username: { type: ['string', 'null'], description: 'Git HTTP username.' },
        repositoryUrl: { type: 'string', description: 'Repository URL for git preview_test.' },
        allowlistMode: { type: 'string', enum: ['selected', 'all_visible'] },
        allowlistEntries: { type: 'array', items: allowlistEntrySchema },
        settings: { type: 'object', description: 'GitLab or Cloudflare connector settings.' },
        query: { type: 'string', description: 'Search text for allowlist_search and allowlist_preview_search.' },
        host: { type: 'string', description: 'SSH host for discover_host_key.' },
        port: { type: 'number', description: 'SSH port for discover_host_key (default 22).' },
        jumpConnectorId: { type: ['string', 'null'], description: 'Jump SSH connector for discover_host_key.' },
      },
      required: ['provider', 'operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Integrations',
    requiredScope: 'integrations:cloudflare:view',
    invalidateStores: ['integrations'],
    targetIdentity: { resourceType: 'integration-connector', arguments: ['connectorId'] },
    historyRetention: { mode: 'persistent_context' },
  },
];
