import type { AIToolDefinition } from './ai.types.js';

export const RESOURCE_SETUP_AI_TOOLS: AIToolDefinition[] = [
  {
    name: 'upload_pages_artifact',
    description:
      'Upload a static Pages project archive through authenticated MCP using a resumable begin/chunk/finalize workflow. Authentication comes from the MCP connection; never pass a token or Authorization value. Chunks contain at most 1 MiB of decoded base64 data.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['begin', 'chunk', 'finalize'] },
        projectId: { type: 'string', description: 'Page Project UUID for begin.' },
        declaredSizeBytes: { type: 'number', description: 'Exact compressed archive size in bytes for begin.' },
        sha256: { type: 'string', description: 'Lowercase SHA-256 of the complete compressed archive for begin.' },
        idempotencyKey: { type: 'string' },
        tag: { type: 'string', description: 'Optional mutable Tag to publish after finalize.' },
        source: {
          type: 'object',
          properties: {
            provider: { type: 'string' },
            repository: { type: 'string' },
            commitSha: { type: 'string' },
            ref: { type: 'string' },
            mergeRequest: { type: 'string' },
            actor: { type: 'string' },
          },
          additionalProperties: false,
        },
        uploadId: { type: 'string', description: 'Upload UUID returned by begin.' },
        offset: { type: 'number', description: 'Current byte offset for chunk.' },
        contentBase64: {
          type: 'string',
          maxLength: 1_398_104,
          description: 'Base64-encoded archive chunk, at most 1 MiB decoded.',
        },
      },
      required: ['operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Pages',
    requiredScope: 'pages:deploy',
    invalidateStores: [],
    historyRetention: { mode: 'never_full' },
    mcpOnly: true,
  },
  {
    name: 'manage_pages',
    description:
      'Inspect and manage Pages profiles, Projects, Deployments, Tags, deploy tokens, runtime configuration, and Git sources. project_placement_options lists nodes a Project can be created on or migrated to; project_migrate also needs pages:create for the target node, and source_upsert needs pages:edit and pages:deploy. Pages must be licensed and enabled for runtime-changing operations. Artifact bytes use the MCP-only upload_pages_artifact tool or the REST resumable deploy API, not this metadata tool.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'profile_get',
            'profile_options',
            'profile_configure',
            'profile_disable',
            'project_list',
            'project_get',
            'project_get_by_slug',
            'project_placement_options',
            'project_create',
            'project_update',
            'project_migrate',
            'project_delete',
            'deployment_list',
            'deployment_get',
            'deployment_pin',
            'deployment_delete',
            'tag_list',
            'tag_move',
            'tag_delete',
            'token_list',
            'token_create',
            'token_revoke',
            'config_list',
            'config_save_default',
            'config_save_tag',
            'config_reset_tag',
            'source_get',
            'source_repositories',
            'source_discover',
            'source_upsert',
            'source_remove',
            'source_build',
            'source_secret_list',
            'source_secret_upsert',
            'source_secret_delete',
          ],
        },
        projectId: { type: 'string', description: 'Page Project UUID.' },
        slug: { type: 'string', description: 'Page Project slug for project_get_by_slug.' },
        deploymentId: { type: 'string', description: 'Page Deployment UUID.' },
        tagId: { type: 'string', description: 'Page Tag UUID for runtime config overrides.' },
        tokenId: { type: 'string', description: 'Page deploy token UUID.' },
        tag: { type: 'string', description: 'Mutable Tag name for move/delete.' },
        page: { type: 'number' },
        limit: { type: 'number' },
        search: { type: 'string' },
        folderId: { type: 'string' },
        name: { type: 'string' },
        description: { type: 'string' },
        nodeId: { type: 'string' },
        targetNodeId: { type: 'string' },
        appearanceColor: { type: 'string' },
        maxDeployments: { type: 'number' },
        storageQuotaBytes: { type: 'number' },
        pinned: { type: 'boolean' },
        allowedTagPatterns: { type: 'array', items: { type: 'string' } },
        allowUserTag: { type: 'boolean' },
        expiresAt: { type: 'string', description: 'Optional ISO 8601 expiration timestamp.' },
        source: { type: 'string', description: 'Valid JSON object source assigned to window.runtime.config.' },
        expectedGeneration: { type: 'number' },
        enabled: { type: 'boolean' },
        domainId: { type: 'string' },
        certificateId: { type: 'string' },
        labelTemplate: { type: 'string' },
        acknowledgeSameRegistrableDomain: { type: 'boolean' },
        sourceConnectorId: { type: 'string', description: 'Allowlisted Git connector UUID.' },
        repositoryProjectId: { type: 'string', description: 'Allowlisted remote repository project UUID.' },
        branch: { type: 'string' },
        applicationRoot: { type: 'string' },
        packageManager: { type: 'string', enum: ['npm', 'pnpm', 'yarn'] },
        packageManagerVersion: { type: 'string' },
        nodeVersion: { type: 'string', enum: ['20', '22', '24'] },
        buildScript: { type: 'string' },
        artifactDirectory: { type: 'string' },
        publishTag: { type: 'string' },
        autoBuild: { type: 'boolean' },
        autoDeploy: { type: 'boolean' },
        buildArgs: { type: 'object', description: 'Public build variables.' },
        buildSecretNames: { type: 'array', items: { type: 'string' } },
        policy: { type: 'object' },
        commitSha: { type: 'string' },
        force: { type: 'boolean' },
        secretName: { type: 'string' },
        secretValue: { type: 'string', description: 'Write-only Build Secret value.' },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Pages',
    requiredScope: 'pages:view',
    invalidateStores: [],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_route',
    description:
      'Route inspection, maintenance access, and config validation. Operations: get_config (full Route settings; Page targets and advanced config follow the caller scopes, stored raw config needs proxy:raw:read), get_by_slug, health_history, secure_link_status, access_logs (newest nginx access and error log lines, up to tail 200), maintenance_access_code (5-minute code that lets a browser view the Route during maintenance; needs proxy:maintenance:bypass), validate_config (check an advanced snippet or, with mode raw, a raw nginx config; needs proxy:advanced or proxy:raw:write, scoped to routeId when given). Change Routes with update_route, set_route_maintenance, update_route_raw_config, and toggle_route_raw_mode.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'get_config',
            'get_by_slug',
            'health_history',
            'secure_link_status',
            'access_logs',
            'maintenance_access_code',
            'validate_config',
          ],
        },
        tail: { type: 'number', description: 'Number of log lines for access_logs (default 100, max 200)' },
        routeId: { type: 'string', description: 'Route UUID; optional for validate_config' },
        slug: { type: 'string', description: 'Route slug for get_by_slug' },
        snippet: { type: 'string', description: 'Advanced snippet or raw nginx config for validate_config' },
        mode: { type: 'string', enum: ['advanced', 'raw'], description: 'validate_config mode (default: advanced)' },
      },
      required: ['operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Ingress',
    requiredScope: 'proxy:view',
    invalidateStores: [],
  },
  {
    name: 'manage_additional_route',
    description:
      'List, inspect, create, update, retry, or delete one path-based Additional Route on a managed ingress Route. Docker targets automatically provision route-owned Secure Links; Pages targets reference a Page Project Tag.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['list', 'get', 'create', 'update', 'retry', 'delete'] },
        routeId: { type: 'string', description: 'Parent Route UUID' },
        additionalRouteId: { type: 'string', description: 'Additional Route UUID for get/update/retry/delete' },
        path: { type: 'string' },
        enabled: { type: 'boolean' },
        targetKind: { type: 'string', enum: ['manual', 'docker_container', 'docker_deployment', 'pages'] },
        forwardHost: { type: 'string' },
        forwardPort: { type: 'number' },
        forwardScheme: { type: 'string', enum: ['http', 'https'] },
        dockerNodeId: { type: 'string' },
        dockerContainerName: { type: 'string' },
        dockerComposeProjectId: { type: 'string' },
        dockerComposeServiceName: { type: 'string' },
        dockerDeploymentId: { type: 'string' },
        dockerContainerPort: { type: 'number' },
        pageProjectId: { type: 'string' },
        pageTagId: { type: 'string' },
        advancedConfig: { type: 'string' },
        stripPrefix: { type: 'boolean' },
        websocketSupport: { type: 'boolean' },
        requestBuffering: { type: 'boolean' },
        responseBuffering: { type: 'boolean' },
        connectTimeoutSeconds: { type: 'number' },
        readTimeoutSeconds: { type: 'number' },
        sendTimeoutSeconds: { type: 'number' },
      },
      required: ['operation', 'routeId'],
    },
    destructive: true,
    category: 'Ingress',
    requiredScope: 'proxy:view',
    invalidateStores: ['proxy-hosts'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_additional_secure_link',
    description:
      'List, create, retry, or delete Additional Secure Links from a Route to Docker workloads or managed S3 storage. For managed_storage pass managedStorageId; the private relay needs no shared network or published S3 port, and S3 authentication remains required. Route-owned bindings are managed only through manage_additional_route.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['list', 'create', 'retry', 'delete'] },
        routeId: { type: 'string', description: 'Parent Route UUID' },
        bindingId: { type: 'string' },
        name: { type: 'string' },
        upstreamKind: { type: 'string', enum: ['docker_container', 'docker_deployment', 'managed_storage'] },
        managedStorageId: { type: 'string', description: 'Managed storage UUID for managed_storage target.' },
        forwardScheme: { type: 'string', enum: ['http', 'https'] },
        dockerNodeId: { type: 'string' },
        dockerContainerName: { type: 'string' },
        dockerComposeProjectId: { type: 'string' },
        dockerComposeServiceName: { type: 'string' },
        dockerDeploymentId: { type: 'string' },
        dockerContainerPort: { type: 'number' },
      },
      required: ['operation', 'routeId'],
    },
    destructive: true,
    category: 'Ingress',
    requiredScope: 'proxy:view',
    invalidateStores: ['proxy-hosts'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_managed_database',
    description:
      'Provision and manage Gateway-managed Postgres, Redis, or ClickHouse instances and their workload bindings. Read the catalog before create, poll get until ready, and create a binding only after the database is ready. reveal_credentials and rotate_credentials return the direct-access credentials of a published instance (databases:credentials:reveal; rotation also needs databases:edit); reveal_binding_credentials returns the credentials of one binding and also needs the target workload binding scopes. logs returns recent container log lines; get_binding_runtime reports the link runtime of one binding. Credential operations are refused while impersonating.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'catalog',
            'list',
            'get',
            'create',
            'update',
            'retry',
            'restart',
            'pause',
            'unpause',
            'rotate_certificate',
            'delete',
            'list_bindings',
            'create_binding',
            'delete_binding',
            'reveal_credentials',
            'rotate_credentials',
            'logs',
            'get_binding_runtime',
            'reveal_binding_credentials',
          ],
        },
        databaseId: { type: 'string', description: 'Managed database instance ID.' },
        bindingId: { type: 'string', description: 'Managed database binding ID.' },
        name: { type: 'string' },
        folderId: { type: ['string', 'null'], description: 'Optional destination folder UUID for create.' },
        tailLines: { type: 'number', description: 'Log lines for logs, 1-5000 (default 500).' },
        timestamps: { type: 'boolean', description: 'Prefix log lines with timestamps (default true).' },
        type: { type: 'string', enum: ['postgres', 'redis', 'clickhouse'] },
        version: { type: 'string', description: 'Exact version returned by catalog.' },
        nodeId: { type: 'string', description: 'Database node ID for create, or optional list filter.' },
        storageSizeGb: { type: 'number' },
        cpuCores: { type: 'number' },
        memoryMb: { type: 'number' },
        swapMb: { type: 'number' },
        tags: { type: 'array', items: { type: 'string' } },
        publishTcp: {
          type: 'boolean',
          description: 'Keep false unless the user explicitly needs external TCP access.',
        },
        publishNativeTcp: { type: 'boolean' },
        publishedPort: { type: 'number' },
        publishedNativePort: { type: 'number' },
        tlsEnabled: { type: 'boolean' },
        clickhouseConfigXml: { type: 'string' },
        redisConfig: { type: 'object' },
        databaseName: { type: 'string' },
        ownerUsername: { type: 'string' },
        targetNodeId: { type: 'string' },
        targetType: { type: 'string', enum: ['container', 'deployment', 'compose_service'] },
        targetResourceId: { type: 'string' },
        environment: {
          type: 'object',
          description:
            'Optional environment variable names for connectionUri, host, port, database, username, and password.',
        },
        replaceExistingEnvironment: { type: 'boolean' },
        targetEnvironment: {
          type: 'object',
          description: 'Complete ordinary-container environment draft when the binding changes it.',
        },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Managed Databases',
    requiredScope: 'databases:view',
    invalidateStores: ['databases', 'containers'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_docker_migration',
    description:
      'Preflight, start, list, inspect, cancel, retry cleanup, or resolve a Gateway Docker container/deployment migration. Always preflight first and pass its exact fingerprint to start. A migration requires an existing source workload and a distinct target Docker node. list filters by status and nodeId. A migration in needs_attention is resolved by naming the authoritative side (source keeps the original workload, target keeps the migrated one); resolve, cancel, and retry_cleanup need docker:tasks:manage, list and get need docker:tasks.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: ['preflight', 'start', 'list', 'get', 'cancel', 'retry_cleanup', 'resolve'],
        },
        migrationId: { type: 'string' },
        resource: {
          type: 'object',
          properties: {
            type: { type: 'string', enum: ['container', 'deployment'] },
            containerName: { type: 'string' },
            deploymentId: { type: 'string' },
          },
          required: ['type'],
        },
        sourceNodeId: { type: 'string' },
        targetNodeId: { type: 'string' },
        keepSource: { type: 'boolean' },
        preflightFingerprint: { type: 'string' },
        authoritativeSide: {
          type: 'string',
          enum: ['source', 'target'],
          description: 'resolve only. The side that keeps serving the workload.',
        },
        status: {
          type: 'string',
          enum: [
            'pending',
            'running',
            'waiting',
            'cancelling',
            'cancelled',
            'completed',
            'failed',
            'cleanup_pending',
            'needs_attention',
          ],
          description: 'list only. Status filter.',
        },
        nodeId: { type: 'string', description: 'list only. Source or target node filter.' },
        limit: { type: 'integer', minimum: 1, maximum: 100, description: 'list only. Default: 50' },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Docker Migration',
    requiredScope: 'docker:containers:migrate',
    invalidateStores: ['containers', 'docker-deployments', 'docker-tasks'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_logging_backend',
    description:
      'Inspect or configure the structured-logging ClickHouse backend. On an empty Gateway, enable_local provisions the Gateway-managed local ClickHouse backend before creating logging environments or schemas. Use configure_external only with user-supplied connection details.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['get', 'enable_local', 'configure_external', 'disable'] },
        url: { type: 'string' },
        username: { type: 'string' },
        password: { type: 'string' },
        database: { type: 'string' },
        table: { type: 'string' },
        requestTimeoutMs: { type: 'number' },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Logging Backend',
    requiredScope: 'settings:gateway:view',
    invalidateStores: ['settings', 'logging'],
    historyRetention: { mode: 'summary_only' },
  },
];
