import type { AIToolDefinition } from './ai.types.js';

const STABLE_CONTAINER_REFERENCE_DESCRIPTION =
  'Exact stable container name returned by find_resource or inspect (preferred). A runtime ID is also accepted, but never manually shorten or retype one.';

export const DOCKER_AI_TOOLS: AIToolDefinition[] = [
  {
    name: 'create_docker_container',
    description:
      'Create a new Docker container on a node from an image already present on that node, and start it when you also have docker:containers:manage on it (otherwise it stays stopped). Before first creation, use list_docker_images and pull_docker_image when the requested image is absent, then wait for the pull task to complete. Volume mounts may reference only existing Gateway-managed volumes; never provide host bind paths. Secure runtime requires a healthy Secure Runtime capability on the node and does not support GPU or device attachments. For public Docker Hub images such as nginx:alpine, omit registryId; a saved registry is not required.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        image: { type: 'string', description: 'Image reference (e.g. nginx:latest, ubuntu:24.04)' },
        registryId: {
          type: 'string',
          description:
            'Optional saved private/custom registry UUID. Omit for public Docker Hub images; never pass an empty string.',
        },
        name: { type: 'string', description: 'Container name (optional, auto-generated if omitted)' },
        folderId: { type: 'string', description: 'Authorized destination container folder UUID.' },
        ports: {
          type: 'array',
          description: 'Port mappings',
          items: {
            type: 'object',
            properties: {
              hostPort: { type: 'number' },
              containerPort: { type: 'number' },
              protocol: { type: 'string', enum: ['tcp', 'udp'], description: 'Default: tcp' },
              hostIp: { type: 'string', description: 'Host IP address to bind. Default: 0.0.0.0' },
            },
            required: ['hostPort', 'containerPort'],
          },
        },
        volumes: {
          type: 'array',
          description:
            'Existing Gateway-managed named-volume mounts. Supplying mounts also requires docker:containers:mounts for the node.',
          items: {
            type: 'object',
            properties: {
              containerPath: { type: 'string' },
              name: { type: 'string', description: 'Existing Gateway-managed volume name' },
              readOnly: { type: 'boolean' },
            },
            required: ['containerPath', 'name'],
          },
        },
        env: { type: 'object', description: 'Environment variables as key-value pairs' },
        networks: { type: 'array', items: { type: 'string' }, description: 'Network names to connect to' },
        restartPolicy: {
          type: 'string',
          enum: ['no', 'always', 'unless-stopped', 'on-failure'],
          description: 'Default: no',
        },
        runtimeProfile: {
          type: 'string',
          enum: ['default', 'secure'],
          description: 'Container isolation profile. Default: default (runc). Secure uses gVisor runsc.',
        },
        stopTimeout: {
          type: 'integer',
          minimum: 0,
          maximum: 300,
          description: 'Container stop grace period in seconds, 0-300. Default: Gateway fallback 20 seconds.',
        },
        gpu: {
          type: 'object',
          description: 'GPU devices to attach, by node GPU inventory device ID. Not supported with the secure runtime.',
          properties: { deviceIds: { type: 'array', items: { type: 'string' } } },
          required: ['deviceIds'],
          additionalProperties: false,
        },
        labels: { type: 'object', description: 'Container labels as key-value pairs' },
        command: { type: 'array', items: { type: 'string' }, description: 'Override container command' },
      },
      required: ['nodeId', 'image'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:create',
    invalidateStores: ['containers'],
  },
  {
    name: 'list_docker_containers',
    description: 'List Docker containers on a specific node with their status, image, ports, and resource usage.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID (required)' },
        search: { type: 'string', description: 'Optional search over container ID, name, image, status, and ports' },
      },
      required: ['nodeId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
  },
  {
    name: 'get_docker_container',
    description:
      'Get detailed information about a specific Docker container including config, state, mounts, and network settings.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
  },
  {
    name: 'execute_docker_container_console_command',
    description:
      'Run a one-shot command inside a Docker container console. This is destructive by policy even for read-looking commands. Use command as argv, for example ["sh","-lc","pwd && ls -la"]. Clearly dangerous commands are blocked; commands with risky patterns require explicit user approval.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        command: {
          type: 'array',
          items: { type: 'string' },
          description: 'Command argv to execute. Use ["sh","-lc","..."] for shell syntax.',
        },
        user: { type: 'string', description: 'Optional container user for docker exec.' },
      },
      required: ['nodeId', 'containerId', 'command'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:console',
    invalidateStores: ['containers'],
  },
  {
    name: 'list_docker_deployments',
    description:
      'List blue/green Docker deployments on a specific node. Use this before acting on managed deployment containers; deployment rows include activeSlot, slots, routes, status, and health.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID (required)' },
        search: { type: 'string', description: 'Optional search over deployment name, image, status, and routes' },
      },
      required: ['nodeId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
  },
  {
    name: 'get_docker_deployment',
    description:
      'Get detailed information about a blue/green Docker deployment by deployment ID. Use deploymentId, not the active slot container ID.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
      },
      required: ['nodeId', 'deploymentId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
  },
  {
    name: 'start_docker_deployment',
    description:
      'Start a stopped blue/green Docker deployment through the deployment layer. Do not start the underlying managed container directly.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
      },
      required: ['nodeId', 'deploymentId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'stop_docker_deployment',
    description:
      'Stop a blue/green Docker deployment through the deployment layer. Do not stop the underlying managed container directly.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
      },
      required: ['nodeId', 'deploymentId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'restart_docker_deployment',
    description:
      'Restart a blue/green Docker deployment through the deployment layer. Use this instead of restarting the active slot container.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
      },
      required: ['nodeId', 'deploymentId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'kill_docker_deployment',
    description:
      'Force-kill a blue/green Docker deployment through the deployment layer. Prefer stop_docker_deployment unless an immediate kill is explicitly requested.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
      },
      required: ['nodeId', 'deploymentId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'deploy_docker_deployment',
    description:
      'Deploy a new inactive slot for a blue/green Docker deployment, optionally with a full image reference or a new tag. This is the deployment-safe replacement for updating a managed slot container image.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
        image: { type: 'string', description: 'Optional full image reference to deploy' },
        tag: { type: 'string', description: 'Optional tag applied to the current deployment image repository' },
        registryId: { type: 'string', description: 'Optional Docker registry UUID for pulling the image' },
        env: { type: 'object', description: 'Optional environment overrides for the new deployment config' },
      },
      required: ['nodeId', 'deploymentId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers', 'tasks'],
  },
  {
    name: 'switch_docker_deployment_slot',
    description:
      'Switch a blue/green Docker deployment to the specified slot. Use only with the Gateway deployment ID and slot name, not a container ID.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
        slot: { type: 'string', enum: ['blue', 'green'], description: 'Target slot to make active' },
        force: { type: 'boolean', description: 'Force switch even if health checks are not healthy (default false)' },
      },
      required: ['nodeId', 'deploymentId', 'slot'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'rollback_docker_deployment',
    description: 'Rollback a blue/green Docker deployment to the inactive previous slot.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
        force: { type: 'boolean', description: 'Force rollback even if health checks are not healthy (default false)' },
      },
      required: ['nodeId', 'deploymentId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'stop_docker_deployment_slot',
    description:
      'Stop an inactive blue/green deployment slot. The active slot cannot be stopped by this tool; use stop_docker_deployment to stop the whole deployment.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID' },
        slot: { type: 'string', enum: ['blue', 'green'], description: 'Inactive slot to stop' },
      },
      required: ['nodeId', 'deploymentId', 'slot'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'start_docker_container',
    description: 'Start a stopped Docker container.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'stop_docker_container',
    description: 'Stop a running Docker container.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        timeout: {
          type: 'integer',
          minimum: 0,
          maximum: 300,
          description: 'Seconds to wait before killing. If omitted, uses the container stop grace setting, then 20.',
        },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'restart_docker_container',
    description: 'Restart a Docker container.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        timeout: {
          type: 'integer',
          minimum: 0,
          maximum: 300,
          description: 'Seconds to wait before killing. If omitted, uses the container stop grace setting, then 20.',
        },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'remove_docker_container',
    description: 'Remove a Docker container. The container must be stopped first.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        force: {
          type: 'boolean',
          description: 'Force removal of a stopped container if Docker requires it (default false)',
        },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:delete',
    invalidateStores: ['containers'],
  },
  {
    name: 'update_docker_container_image',
    description:
      'Update a Docker container to a different image tag. Pulls the new image, then recreates the container with the new image while preserving all other settings (ports, volumes, env, etc.). Use this to upgrade/downgrade container versions.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        imageTag: { type: 'string', description: 'New image tag (e.g. "1.25", "latest", "v2.0.0")' },
      },
      required: ['nodeId', 'containerId', 'imageTag'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers', 'tasks'],
  },
  {
    name: 'rename_docker_container',
    description: 'Rename a Docker container.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        name: { type: 'string', description: 'New container name' },
      },
      required: ['nodeId', 'containerId', 'name'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:edit',
    invalidateStores: ['containers'],
  },
  {
    name: 'duplicate_docker_container',
    description:
      'Clone a Docker container with a new name. Copies config, ports, volumes, env, and secrets. Requires docker:containers:create for the destination plus config, environment, and secrets access on the source container.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        name: { type: 'string', description: 'Name for the new container' },
        folderId: { type: 'string', description: 'Optional authorized destination container folder UUID.' },
      },
      required: ['nodeId', 'containerId', 'name'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:create',
    requiredScopes: ['docker:containers:config', 'docker:containers:environment', 'docker:containers:secrets'],
    invalidateStores: ['containers'],
  },
  {
    name: 'get_docker_container_stats',
    description: 'Get live resource usage stats for a Docker container (CPU%, memory, network I/O, PIDs).',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
  },
  {
    name: 'get_docker_container_logs',
    description: 'Get recent log output from a Docker container.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        tail: { type: 'integer', minimum: 1, maximum: 1000, description: 'Number of lines from the end (default 100)' },
        timestamps: { type: 'boolean', description: 'Include timestamps (default false)' },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
    historyRetention: { mode: 'summary_only' },
  },

  // ── Docker: Images ──
  {
    name: 'list_docker_images',
    description: 'List Docker images on a specific node with their tags, size, and creation date.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID (required)' },
        search: { type: 'string', description: 'Optional search over image ID, tags, and digests' },
      },
      required: ['nodeId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:images:view',
    invalidateStores: [],
  },
  {
    name: 'pull_docker_image',
    description:
      'Pull a Docker image onto a node. Public Docker Hub images such as nginx:alpine are pulled directly with registryId omitted; never create a saved Docker Hub registry just to pull a public image.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        imageRef: { type: 'string', description: 'Image reference (e.g. nginx:latest, ghcr.io/org/app:v2)' },
        registryId: {
          type: 'string',
          description:
            'Optional saved private/custom registry UUID. Omit for public Docker Hub images; never pass an empty string.',
        },
        folderId: { type: 'string', description: 'Optional authorized destination image folder UUID.' },
        wait: {
          type: 'boolean',
          description:
            'Pull synchronously and fail if the image cannot be pulled (default false: queue a background pull task).',
        },
      },
      required: ['nodeId', 'imageRef'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:images:pull',
    invalidateStores: ['images'],
  },

  {
    name: 'remove_docker_image',
    description: 'Remove a Docker image from a node.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        imageId: { type: 'string', description: 'Image ID or reference (e.g. sha256:abc... or nginx:1.25)' },
        force: { type: 'boolean', description: 'Force remove even if in use (default false)' },
      },
      required: ['nodeId', 'imageId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:images:delete',
    invalidateStores: ['images'],
  },
  {
    name: 'prune_docker_images',
    description: 'Remove all unused Docker images from a node to free disk space. Returns reclaimed space.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
      },
      required: ['nodeId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:images:delete',
    invalidateStores: ['images'],
  },

  // ── Docker: Volumes & Networks ──
  {
    name: 'list_docker_volumes',
    description:
      'List Gateway-managed volumes plus legacy volumes still attached to visible Gateway containers on a specific node. Orphaned unmanaged volumes are hidden.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID (required)' },
        search: { type: 'string', description: 'Optional search over volume name, driver, mountpoint, and users' },
      },
      required: ['nodeId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:volumes:view',
    invalidateStores: [],
  },
  {
    name: 'list_docker_networks',
    description: 'List Docker networks on a specific node.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID (required)' },
        search: { type: 'string', description: 'Optional search over network ID, name, driver, and scope' },
      },
      required: ['nodeId'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:networks:view',
    invalidateStores: [],
  },
  {
    name: 'manage_docker_registry',
    description:
      'Manage saved private or custom Docker registries and the Gateway internal build registry. Operations: list, get, create, update, delete, test, test_direct for saved registries; internal_get (state, health, storage, external access), internal_repositories, internal_update_settings (external access hostname, nginx node, certificate), internal_gc (garbage collection, optionally dryRun), and internal_resume_maintenance (resume an interrupted maintenance run) for the internal registry. Do not create a registry for public Docker Hub images; pull those directly without registryId. Mutating operations require the corresponding docker:registries:* scope; internal registry reads need broad docker:registries:view and changes broad docker:registries:edit.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'list',
            'get',
            'create',
            'update',
            'delete',
            'test',
            'test_direct',
            'internal_get',
            'internal_repositories',
            'internal_update_settings',
            'internal_gc',
            'internal_resume_maintenance',
          ],
        },
        registryId: { type: 'string', description: 'Registry UUID for get/update/delete/test' },
        nodeId: { type: 'string', description: 'Optional node filter for list, or node scoped registry owner' },
        name: { type: 'string' },
        url: { type: 'string' },
        username: { type: 'string' },
        password: { type: 'string' },
        trustedAuthRealm: { type: 'string' },
        scope: { type: 'string', enum: ['global', 'node'] },
        externalAccessEnabled: {
          type: 'boolean',
          description: 'internal_update_settings: expose the internal registry through an nginx node.',
        },
        externalHostname: { type: 'string', description: 'internal_update_settings: external registry hostname.' },
        externalNginxNodeId: { type: 'string', description: 'internal_update_settings: nginx node UUID.' },
        externalCertificateId: { type: 'string', description: 'internal_update_settings: TLS certificate UUID.' },
        dryRun: { type: 'boolean', description: 'internal_gc: report what would be removed without deleting.' },
        runId: { type: 'string', description: 'internal_resume_maintenance: maintenance run UUID.' },
      },
      required: ['operation'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:registries:view',
    invalidateStores: [],
  },
  {
    name: 'manage_docker_volume',
    description:
      'Create, inspect, resize, adopt, rename, relabel, delete, and browse files of Docker volumes on a node. create makes a Gateway-managed local volume and accepts no driver setting: storageKind "regular" (default) takes no capacity; storageKind "disk-image" makes a fixed-size volume and requires capacityBytes (at least 268435456), a compatible node, and Personal-or-higher licensing. resize grows an existing Gateway-managed disk-image volume to capacityBytes; it cannot shrink. adopt brings an eligible legacy local volume under Gateway management without copying data. inspect and metrics read the cached detail and usage; managed_options lists volumes selectable as container mounts (docker:containers:mounts). rename (newName) and update_labels (labels) need docker:volumes:create and :delete. File operations (list_files, read_file, write_file, create_file, create_directory, delete_file, move_file, upload_init/upload_chunk/upload_complete/upload_abort) need docker:volumes:files:read or :write; binary content uses contentBase64 and upload chunks carry at most 1 MiB. Archive export uses the MCP-only download_docker_archive tool. delete removes the volume. Compose-owned volumes must be changed through their Compose project. Listing is available via list_docker_volumes.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'create',
            'resize',
            'adopt',
            'delete',
            'inspect',
            'metrics',
            'managed_options',
            'rename',
            'update_labels',
            'list_files',
            'read_file',
            'write_file',
            'create_file',
            'create_directory',
            'delete_file',
            'move_file',
            'upload_init',
            'upload_chunk',
            'upload_complete',
            'upload_abort',
          ],
        },
        nodeId: { type: 'string' },
        name: {
          type: 'string',
          description: 'Volume name. For create, the new volume name. managed_options ignores it.',
        },
        newName: { type: 'string', description: 'rename only. New volume name.' },
        labels: { type: 'object', description: 'update_labels only. Complete volume label map.' },
        path: { type: 'string', description: 'Absolute path inside the volume for file operations. Default: /' },
        fromPath: { type: 'string', description: 'move_file only. Absolute source path.' },
        toPath: { type: 'string', description: 'move_file only. Absolute destination path.' },
        content: { type: 'string', description: 'UTF-8 content for write_file, create_file, or upload_chunk.' },
        contentBase64: {
          type: 'string',
          description: 'Base64 content for binary write_file, create_file, or upload_chunk (chunk at most 1 MiB).',
        },
        encoding: { type: 'string', enum: ['utf8', 'base64'], description: 'read_file output encoding. Default: utf8' },
        offsetBytes: { type: 'integer', minimum: 0, description: 'read_file: first byte to return. Default: 0' },
        limitBytes: { type: 'integer', minimum: 1, description: 'read_file: maximum bytes to return.' },
        uploadId: { type: 'string', description: 'Upload session ID for upload_chunk, upload_complete, upload_abort.' },
        offset: { type: 'integer', minimum: 0, description: 'upload_chunk: byte offset of this chunk.' },
        totalBytes: { type: 'integer', minimum: 0, description: 'upload_init/upload_complete: total file size.' },
        storageKind: {
          type: 'string',
          enum: ['regular', 'disk-image'],
          description: 'create only. Defaults to regular.',
        },
        capacityBytes: {
          type: 'integer',
          minimum: 268435456,
          description:
            'Disk-image capacity in bytes. Required for create with storageKind disk-image, and for resize (new, larger size).',
        },
        folderId: { type: 'string', description: 'create only. Authorized destination volume folder UUID.' },
        force: { type: 'boolean', description: 'delete only.' },
      },
      required: ['operation', 'nodeId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:volumes:create',
    invalidateStores: [],
  },
  {
    name: 'manage_docker_network',
    description:
      'Create, delete, connect, or disconnect Docker networks on a node. Listing is available via list_docker_networks.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['create', 'delete', 'connect', 'disconnect'] },
        nodeId: { type: 'string' },
        networkId: { type: 'string', description: 'Network ID or name for delete/connect/disconnect' },
        name: { type: 'string', description: 'Network name for create' },
        driver: { type: 'string' },
        subnet: { type: 'string' },
        gateway: { type: 'string' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
      },
      required: ['operation', 'nodeId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:networks:create',
    invalidateStores: [],
  },
  {
    name: 'manage_docker_compose',
    description:
      'Inspect and manage first-class single-node Docker Compose Projects. Supports discovery, validation, create/adopt/delete, immutable revisions, lifecycle operations, operation history, project secrets, and recent service logs (logs, optionally one serviceName). Managed mutations require the Compose entitlement and exact docker:compose resource scopes. While a Git-source build rollout owns a project, revision, secret, and lifecycle changes are refused with 409 BUILD_ROLLOUT_IN_PROGRESS until it finishes.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'list',
            'get',
            'validate',
            'create',
            'adopt',
            'delete',
            'revision_list',
            'revision_get',
            'revision_create',
            'revision_delete',
            'operation_list',
            'operation_start',
            'secret_list',
            'secret_create',
            'secret_update',
            'secret_delete',
            'logs',
          ],
        },
        nodeId: { type: 'string', description: 'Docker node UUID.' },
        projectId: { type: 'string', description: 'Compose Project UUID.' },
        projectName: { type: 'string', description: 'Compose project name for validate/create.' },
        folderId: { type: 'string', description: 'Authorized destination Compose folder UUID for creation.' },
        yaml: { type: 'string', description: 'Complete single-file Compose YAML.' },
        variables: { type: 'object', description: 'Compose interpolation variables.' },
        secretKeys: { type: 'array', items: { type: 'string' } },
        revisionId: { type: 'string' },
        cursor: { type: 'string' },
        limit: { type: 'integer', minimum: 1, maximum: 100 },
        action: {
          type: 'string',
          enum: ['apply', 'pull_apply', 'start', 'stop', 'restart', 'down', 'delete_volumes', 'cancel'],
        },
        idempotencyKey: { type: 'string' },
        removeOrphans: { type: 'boolean' },
        volumeNames: { type: 'array', items: { type: 'string' } },
        secretId: { type: 'string' },
        key: { type: 'string' },
        value: { type: 'string' },
        serviceName: { type: 'string', description: 'logs only. Limit logs to one Compose service.' },
        tail: {
          type: 'integer',
          minimum: 1,
          maximum: 1000,
          description: 'logs only. Lines per container (default 100).',
        },
        timestamps: { type: 'boolean', description: 'logs only. Include timestamps (default false).' },
      },
      required: ['operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:compose:view',
    invalidateStores: ['containers'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'list_docker_builds',
    description:
      'List Git-source Docker builds visible to the caller, including exact commit, status, Build Worker, immutable artifact, policy result, and target resource.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Optional Docker runtime node filter' },
        builderNodeId: { type: 'string', description: 'Optional Build Worker node filter' },
        sourceBindingId: { type: 'string', description: 'Optional source binding UUID' },
        status: {
          type: 'string',
          enum: [
            'queued',
            'claimed',
            'checking_out',
            'building',
            'scanning',
            'pushing',
            'deploying',
            'succeeded',
            'failed',
            'cancelled',
            'superseded',
          ],
        },
        provider: { type: 'string', enum: ['gitlab', 'github', 'git'] },
        branch: { type: 'string' },
        search: { type: 'string' },
        limit: { type: 'integer', minimum: 1, maximum: 200, description: 'Default: 20' },
      },
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
  },
  {
    name: 'manage_docker_build',
    description:
      'Inspect one Git-source build, read incremental build logs, request cancellation, or retry a terminal build. Authorization follows the build target: Docker container/deployment, Compose Project, or Pages Project.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['get', 'logs', 'cancel', 'retry'] },
        buildId: { type: 'string' },
        afterSequence: { type: 'integer', minimum: -1, description: 'For logs; default -1.' },
        limit: { type: 'integer', minimum: 1, maximum: 500, description: 'For logs; default 200.' },
      },
      required: ['operation', 'buildId'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: ['containers'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_docker_source',
    description:
      'Inspect, attach, update, remove, resolve, or manually build the Git source bound directly to an existing Docker container, blue/green deployment, or Compose Project, or create a new container, deployment, or Compose Project from a Git source (create). pending reads a container that exists only as a queued first source build. Also lists source repositories and manages source-scoped Build Secrets without exposing secret values. Builds always resolve an exact commit and deploy only approved immutable artifacts; while a build rollout deploys, other changes to its target are refused with 409 BUILD_ROLLOUT_IN_PROGRESS.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'get',
            'pending',
            'create',
            'upsert',
            'remove',
            'resolve',
            'build',
            'admission',
            'repositories',
            'secret_list',
            'secret_upsert',
            'secret_delete',
          ],
        },
        targetType: { type: 'string', enum: ['container', 'deployment', 'compose'] },
        nodeId: { type: 'string', description: 'Docker runtime node ID' },
        containerName: { type: 'string', description: 'Exact stable container name' },
        deploymentId: { type: 'string', description: 'Blue/green deployment UUID' },
        composeProjectId: { type: 'string', description: 'Compose Project UUID' },
        resourceName: { type: 'string', description: 'New container or deployment name for create.' },
        folderId: { type: 'string', description: 'Authorized destination folder UUID for creation.' },
        projectName: { type: 'string', description: 'New Compose Project name for create.' },
        restartPolicy: {
          type: 'string',
          enum: ['no', 'always', 'unless-stopped', 'on-failure'],
        },
        runtimeProfile: { type: 'string', enum: ['default', 'secure'] },
        routes: { type: 'array', items: { type: 'object' } },
        health: { type: 'object' },
        drainSeconds: { type: 'number' },
        routerImage: { type: 'string' },
        connectorId: { type: 'string', description: 'Allowlisted Git integration UUID' },
        projectId: { type: 'string', description: 'Allowlisted repository project UUID' },
        branch: { type: 'string' },
        dockerfilePath: { type: 'string', description: 'Repository-relative Dockerfile path' },
        contextPath: { type: 'string', description: 'Repository-relative build context' },
        composeFilePath: { type: 'string', description: 'Repository-relative Compose file path.' },
        composeVariables: { type: 'object', description: 'Compose interpolation variables.' },
        composeSecretKeys: { type: 'array', items: { type: 'string' } },
        autoBuild: { type: 'boolean', description: 'Automatically build newly detected commits' },
        autoDeploy: { type: 'boolean' },
        buildArgs: { type: 'object', description: 'Non-secret build arguments' },
        buildSecretNames: {
          type: 'array',
          items: { type: 'string' },
          description: 'Write-only Build Secret IDs configured separately on the source binding',
        },
        policy: {
          type: 'object',
          description: 'Artifact policy containing the vulnerability blocking threshold',
        },
        commitSha: { type: 'string', description: 'Optional exact current commit for a manual build' },
        force: { type: 'boolean', description: 'Queue a new attempt even when this commit already has a build' },
        secretName: { type: 'string', description: 'Source-scoped Build Secret name.' },
        secretValue: { type: 'string', description: 'Write-only Build Secret value.' },
      },
      required: ['operation', 'nodeId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: ['containers'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_docker_task',
    description:
      'List or get Docker background tasks for image pulls, container updates, and webhook actions. Callers with node-scoped docker:tasks see tasks of their nodes only. Docker migrations, including needs_attention resolution, use manage_docker_migration.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['list', 'get'] },
        taskId: { type: 'string' },
        nodeId: { type: 'string' },
        status: { type: 'string' },
        type: { type: 'string' },
      },
      required: ['operation'],
    },
    destructive: false,
    category: 'Docker',
    requiredScope: 'docker:tasks',
    invalidateStores: [],
  },
  {
    name: 'manage_docker_container_config',
    description:
      'Manage container env, files, secrets, webhooks, and HTTP health checks. Container file list/read requires docker:containers:files:read; write_file, create_file, create_directory, delete_file, move_file, and resumable upload_init/upload_chunk/upload_complete/upload_abort require docker:containers:files:write. Binary content uses contentBase64 (upload chunks at most 1 MiB); read_file returns UTF-8 unless encoding is base64. Other operation-specific environment/secrets/webhooks/edit/view scopes are enforced.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'get_env',
            'update_env',
            'list_files',
            'read_file',
            'write_file',
            'create_file',
            'create_directory',
            'delete_file',
            'move_file',
            'upload_init',
            'upload_chunk',
            'upload_complete',
            'upload_abort',
            'list_secrets',
            'create_secret',
            'update_secret',
            'delete_secret',
            'get_webhook',
            'upsert_webhook',
            'delete_webhook',
            'regenerate_webhook_token',
            'get_health_check',
            'upsert_health_check',
            'test_health_check',
          ],
        },
        targetType: { type: 'string', enum: ['container', 'deployment'], description: 'Defaults to container' },
        nodeId: { type: 'string' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        containerName: { type: 'string' },
        deploymentId: { type: 'string' },
        secretId: { type: 'string' },
        key: { type: 'string' },
        value: { type: 'string' },
        reveal: { type: 'boolean' },
        env: { type: 'object', description: 'Environment key/value map for update_env' },
        removeEnv: { type: 'array', items: { type: 'string' } },
        path: { type: 'string', description: 'Container file path' },
        fromPath: { type: 'string', description: 'move_file only. Absolute source path.' },
        toPath: { type: 'string', description: 'move_file only. Absolute destination path.' },
        content: { type: 'string', description: 'UTF-8 text content for write_file, create_file, or upload_chunk' },
        contentBase64: {
          type: 'string',
          description: 'Base64 content for binary write_file, create_file, or upload_chunk (chunk at most 1 MiB).',
        },
        encoding: { type: 'string', enum: ['utf8', 'base64'], description: 'read_file output encoding. Default: utf8' },
        offsetBytes: { type: 'integer', minimum: 0, description: 'read_file: first byte to return. Default: 0' },
        limitBytes: { type: 'integer', minimum: 1, description: 'read_file: maximum bytes to return.' },
        uploadId: { type: 'string', description: 'Upload session ID for upload_chunk, upload_complete, upload_abort.' },
        offset: { type: 'integer', minimum: 0, description: 'upload_chunk: byte offset of this chunk.' },
        totalBytes: { type: 'integer', minimum: 0, description: 'upload_init/upload_complete: total file size.' },
        enabled: { type: 'boolean', description: 'Webhook or health check enabled state' },
        healthCheck: { type: 'object', description: 'Docker health check configuration' },
      },
      required: ['operation', 'nodeId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: [],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_docker_deployment',
    description:
      'Create, update, or delete a blue/green Docker deployment. create needs docker:containers:create for the node or folder; update needs docker:containers:edit; delete needs docker:containers:delete and removes both slots and the router. Use deploy_docker_deployment to roll out a new image.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['create', 'update', 'delete'] },
        nodeId: { type: 'string', description: 'Docker node ID' },
        deploymentId: { type: 'string', description: 'Gateway deployment ID for update and delete' },
        payload: {
          type: 'object',
          description:
            'create: { name, image, registryId?, folderId?, routes: [{ hostPort, containerPort, isPrimary? }], health?: { path, statusMin, statusMax, timeoutSeconds, intervalSeconds, successThreshold, startupGraceSeconds, deployTimeoutSeconds }, drainSeconds?, routerImage?, env?, mounts?, command?, entrypoint?, workingDir?, user?, labels?, restartPolicy?, runtimeProfile?, gpu? }. update: { name?, desiredConfig?, routes?, health?, drainSeconds? }.',
        },
      },
      required: ['operation', 'nodeId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:edit',
    invalidateStores: ['containers'],
  },
  {
    name: 'kill_docker_container',
    description:
      'Send a signal (default SIGKILL) to a Docker container. Prefer stop_docker_container unless an immediate kill is explicitly requested. Compose-owned containers must be changed through their Compose project.',
    parameters: {
      type: 'object',
      properties: {
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        signal: { type: 'string', description: 'Signal name, for example SIGKILL or SIGTERM. Defaults to SIGKILL.' },
      },
      required: ['nodeId', 'containerId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:manage',
    invalidateStores: ['containers'],
  },
  {
    name: 'force_cancel_docker_task',
    description:
      'Force-cancel a stuck active Docker background task (image pull, container update, webhook action) found with manage_docker_task. Requires docker:tasks:manage for the task node.',
    parameters: {
      type: 'object',
      properties: {
        taskId: { type: 'string', description: 'Docker task ID' },
      },
      required: ['taskId'],
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:tasks:manage',
    invalidateStores: ['tasks'],
  },
  {
    name: 'manage_docker_container',
    description:
      'Change or inspect an existing standalone Docker container beyond start/stop. recreate applies a new configuration by recreating the container: image, ports, mounts (managed volumes by name; existing host bind mounts must be passed back unchanged), entrypoint, command, workingDir, user, hostname, labels, stopTimeout, restartPolicy, maxRetries, memoryLimit, memorySwap, nanoCPUs, cpuShares, pidsLimit, gpu, and runtimeProfile; omitted fields keep their current value, while ports, mounts, labels, and gpu replace the whole list. recreate needs docker:containers:manage plus edit, and changing image, entrypoint, command, user, or runtimeProfile also needs config, environment, and secrets access; a new image needs docker:images:pull on the node. live_update changes restartPolicy, maxRetries, and resource limits without recreation (docker:containers:edit). update pulls a new tag and/or changes env/removeEnv and redeploys (edit; env changes need environment access). processes lists running processes, stats_history returns recent resource samples, and gpu_usage lists GPU devices with their visible containers on the node. image_cleanup_get and image_cleanup_upsert read or set old-image retention (enabled, retentionCount 1-50) for a container or, with targetType deployment, a blue/green deployment (docker:containers:edit). archive_plan_import resolves an archive manifest summary (archiveManifest) against the node before upload_docker_container_archive. Compose-owned containers must be changed through their Compose project and blue/green slot containers through deployment tools; a running build rollout owns its container and changes are refused with 409.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'recreate',
            'live_update',
            'update',
            'processes',
            'stats_history',
            'gpu_usage',
            'image_cleanup_get',
            'image_cleanup_upsert',
            'archive_plan_import',
          ],
        },
        nodeId: { type: 'string', description: 'Docker node ID' },
        containerId: { type: 'string', description: STABLE_CONTAINER_REFERENCE_DESCRIPTION },
        containerName: {
          type: 'string',
          description: 'image_cleanup_*: exact container name (alternative to containerId).',
        },
        targetType: {
          type: 'string',
          enum: ['container', 'deployment'],
          description: 'image_cleanup_* only. Default: container.',
        },
        deploymentId: { type: 'string', description: 'image_cleanup_* with targetType deployment.' },
        image: { type: 'string', description: 'recreate: full image reference.' },
        ports: {
          type: 'array',
          description: 'recreate: complete published port list.',
          items: {
            type: 'object',
            properties: {
              hostPort: { type: 'integer', minimum: 0, maximum: 65535 },
              containerPort: { type: 'integer', minimum: 1, maximum: 65535 },
              protocol: { type: 'string', enum: ['tcp', 'udp'] },
              hostIp: { type: 'string' },
            },
            required: ['hostPort', 'containerPort'],
            additionalProperties: false,
          },
        },
        mounts: {
          type: 'array',
          description:
            'recreate: complete mount list. Use name for a Gateway-managed volume or hostPath for an existing host bind mount; changing mounts requires docker:containers:mounts.',
          items: {
            type: 'object',
            properties: {
              containerPath: { type: 'string' },
              name: { type: 'string' },
              hostPath: { type: 'string' },
              readOnly: { type: 'boolean' },
            },
            required: ['containerPath'],
            additionalProperties: false,
          },
        },
        entrypoint: { type: 'array', items: { type: 'string' }, description: 'recreate: entrypoint argv.' },
        command: { type: 'array', items: { type: 'string' }, description: 'recreate: command argv.' },
        workingDir: { type: 'string', description: 'recreate: working directory.' },
        user: { type: 'string', description: 'recreate: container user.' },
        hostname: { type: 'string', description: 'recreate: container hostname.' },
        labels: { type: 'object', description: 'recreate: complete container label map.' },
        stopTimeout: { type: 'integer', minimum: 0, maximum: 300, description: 'recreate: stop grace in seconds.' },
        restartPolicy: { type: 'string', enum: ['no', 'always', 'unless-stopped', 'on-failure'] },
        maxRetries: { type: 'integer', minimum: 0, description: 'on-failure restart retries.' },
        memoryLimit: { type: 'integer', minimum: 0, description: 'Memory limit in bytes; 0 removes it.' },
        memorySwap: { type: 'integer', description: 'Memory plus swap in bytes; -1 is unlimited.' },
        nanoCPUs: { type: 'integer', minimum: 0, description: 'CPU limit in 1e-9 CPUs (1000000000 = 1 CPU).' },
        cpuShares: { type: 'integer', minimum: 0, description: 'Relative CPU weight.' },
        pidsLimit: { type: 'integer', minimum: 0, description: 'Maximum process count.' },
        gpu: {
          type: 'object',
          description: 'recreate: GPU device IDs from the node inventory; an empty list detaches all GPUs.',
          properties: { deviceIds: { type: 'array', items: { type: 'string' } } },
          required: ['deviceIds'],
          additionalProperties: false,
        },
        runtimeProfile: { type: 'string', enum: ['default', 'secure'], description: 'recreate: isolation profile.' },
        tag: { type: 'string', description: 'update: new tag for the current image repository.' },
        env: { type: 'object', description: 'update: environment variables to set.' },
        removeEnv: { type: 'array', items: { type: 'string' }, description: 'update: environment keys to remove.' },
        enabled: { type: 'boolean', description: 'image_cleanup_upsert: enable old-image cleanup.' },
        retentionCount: {
          type: 'integer',
          minimum: 1,
          maximum: 50,
          description: 'image_cleanup_upsert: previous images to keep.',
        },
        archiveManifest: {
          type: 'object',
          description:
            'archive_plan_import: the archive manifest summary { networks: [{ name, driver?, subnet?, gateway?, createable, createNew?, requiresMapping? }], mounts: [{ type: bind|volume, source, target, readOnly, driver?, labels?, createNew?, requiresMapping? }], ports: [{ containerPort, hostPort, protocol }] }.',
        },
      },
      required: ['operation', 'nodeId'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:view',
    invalidateStores: ['containers', 'tasks'],
  },
  {
    name: 'manage_docker_availability',
    description:
      'Run a Docker container, blue/green deployment, or Compose Project across several Docker nodes (replicated) or with automatic failover. preflight checks eligibility and candidate nodes for a proposed policy; enable applies it; get and get_by_resource read the policy with placements; list_operations pages rollout history; update changes mode, replicas, node selection, rollout policy, or offline grace; retry_operation retries a failed operation; disable returns the workload to one node and requires survivingPlacementId plus the typed confirmation shown by the UI. Mutations need docker:availability:manage; the workload, candidate nodes, and dependencies are authorized like the Availability routes.',
    parameters: {
      type: 'object',
      properties: {
        operation: {
          type: 'string',
          enum: [
            'preflight',
            'enable',
            'get',
            'get_by_resource',
            'list_operations',
            'update',
            'disable',
            'retry_operation',
          ],
        },
        resource: {
          type: 'object',
          description: 'preflight, enable, get_by_resource: the workload.',
          properties: {
            type: { type: 'string', enum: ['container', 'deployment', 'compose'] },
            nodeId: { type: 'string', description: 'Container node UUID.' },
            containerName: { type: 'string' },
            deploymentId: { type: 'string' },
            composeProjectId: { type: 'string' },
          },
          required: ['type'],
          additionalProperties: false,
        },
        policyId: { type: 'string', description: 'Availability policy UUID.' },
        operationId: { type: 'string', description: 'retry_operation: operation UUID.' },
        mode: { type: 'string', enum: ['replicated', 'failover'] },
        desiredReplicaCount: {
          type: 'integer',
          minimum: 1,
          maximum: 32,
          description: 'replicated: 2-32; failover: exactly 1.',
        },
        nodeSelectionMode: { type: 'string', enum: ['all_compatible', 'selected'] },
        selectedNodeIds: { type: 'array', items: { type: 'string' }, description: 'Required for selected mode.' },
        rolloutPolicy: {
          type: 'object',
          properties: {
            maxUnavailable: { type: 'integer', minimum: 0, maximum: 32 },
            maxSurge: { type: 'integer', minimum: 0, maximum: 32 },
            drainSeconds: { type: 'integer', minimum: 0, maximum: 3600 },
          },
          additionalProperties: false,
        },
        offlineReplacementGraceSeconds: { type: 'integer', minimum: 0, maximum: 3600 },
        survivingPlacementId: { type: 'string', description: 'disable: placement UUID that keeps running.' },
        confirmation: { type: 'string', description: 'disable: typed confirmation text.' },
        page: { type: 'integer', minimum: 1, description: 'list_operations page. Default: 1' },
        limit: { type: 'integer', minimum: 1, maximum: 100, description: 'list_operations page size. Default: 50' },
      },
      required: ['operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:availability:manage',
    invalidateStores: ['containers'],
    historyRetention: { mode: 'summary_only' },
  },
  {
    name: 'manage_docker_runtime',
    description:
      'Check (preflight) or install (install) the gVisor runsc secure container runtime on a Docker node. Installing restarts the Docker daemon on that node. Requires broad admin:update.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['preflight', 'install'] },
        nodeId: { type: 'string', description: 'Docker node ID' },
      },
      required: ['operation', 'nodeId'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'admin:update',
    invalidateStores: ['nodes'],
  },
  {
    name: 'upload_docker_container_archive',
    description:
      'Import a Gateway container archive (.gwca) as a new container on a Docker node through authenticated MCP, using a resumable begin/chunk/status/finalize/abort workflow. begin takes nodeId, the new container name, optional folderId, the resolution returned by manage_docker_container archive_plan_import, the exact archive size, and its lowercase SHA-256; send ordered chunks of at most 1 MiB decoded base64 at the returned offset, then finalize. Requires docker:containers:create for the node or folder and the container archive entitlement; archive environment, secrets, networks, and volumes need the matching node scopes. Authentication comes from the MCP connection; never pass a token.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['begin', 'chunk', 'status', 'finalize', 'abort'] },
        nodeId: { type: 'string', description: 'begin: destination Docker node UUID.' },
        name: { type: 'string', description: 'begin: new container name.' },
        folderId: { type: 'string', description: 'begin: optional authorized destination container folder UUID.' },
        resolution: {
          type: 'object',
          description:
            'begin: network, volume, and port mappings { networks?, createNetworks?, volumes?, createVolumes?, ports? } from archive_plan_import.',
        },
        declaredSizeBytes: { type: 'integer', minimum: 1, description: 'begin: exact archive size in bytes.' },
        sha256: { type: 'string', description: 'begin: lowercase SHA-256 of the complete archive.' },
        uploadId: { type: 'string', description: 'Upload UUID returned by begin.' },
        offset: { type: 'integer', minimum: 0, description: 'chunk: current byte offset.' },
        contentBase64: {
          type: 'string',
          maxLength: 1_398_104,
          description: 'chunk: base64-encoded archive bytes, at most 1 MiB decoded.',
        },
      },
      required: ['operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:create',
    invalidateStores: ['containers'],
    historyRetention: { mode: 'never_full' },
    mcpOnly: true,
  },
  {
    name: 'download_docker_archive',
    description:
      'Export a container archive (.gwca, kind container) or a volume archive (.tar.gz, kind volume) through authenticated MCP. begin prepares the archive on the Gateway and returns a downloadId; poll status until ready (it reports sizeBytes and sha256); read chunk at increasing offsets (at most 1 MiB per call, base64) until eof; then close. Container export needs docker:containers:export, plus files read for the portable image mode, environment access when includeEnvironment (default true), and secrets access when includeSecrets. Volume export needs docker:volumes:export. Prepared archives expire after an hour of inactivity.',
    parameters: {
      type: 'object',
      properties: {
        operation: { type: 'string', enum: ['begin', 'status', 'chunk', 'close'] },
        kind: { type: 'string', enum: ['container', 'volume'], description: 'begin: what to export.' },
        nodeId: { type: 'string', description: 'begin: Docker node ID.' },
        containerId: { type: 'string', description: `begin (container): ${STABLE_CONTAINER_REFERENCE_DESCRIPTION}` },
        volumeName: { type: 'string', description: 'begin (volume): volume name.' },
        imageMode: {
          type: 'string',
          enum: ['portable', 'registry'],
          description: 'begin (container): embed the image (portable, default) or reference its registry digest.',
        },
        includeWritableLayer: { type: 'boolean', description: 'begin (container): include filesystem changes.' },
        includeEnvironment: { type: 'boolean', description: 'begin (container): include environment. Default: true' },
        includeSecrets: {
          type: 'boolean',
          description: 'begin (container): include secret values; requires includeEnvironment. Default: false',
        },
        downloadId: { type: 'string', description: 'Download UUID returned by begin.' },
        offset: { type: 'integer', minimum: 0, description: 'chunk: byte offset. Default: 0' },
        length: {
          type: 'integer',
          minimum: 1,
          maximum: 1_048_576,
          description: 'chunk: bytes to read. Default: 1 MiB',
        },
      },
      required: ['operation'],
      additionalProperties: false,
    },
    destructive: true,
    category: 'Docker',
    requiredScope: 'docker:containers:export',
    invalidateStores: [],
    historyRetention: { mode: 'never_full' },
    mcpOnly: true,
  },
];
