import { ALL_SCOPES } from './scopes-base.js';

export const SYSTEM_ADMIN_SCOPES: readonly string[] = [...ALL_SCOPES];

/** Admin group: curated broad access except system protection and high-risk operational defaults. */
export const ADMIN_SCOPES: readonly string[] = [
  'storage:view',
  'storage:create',
  'storage:edit',
  'storage:delete',
  'storage:credentials:reveal',
  'storage:credentials:use',
  'storage:iam',
  'storage:objects:read',
  'storage:objects:write',
  'storage:objects:admin',
  'storage:folders:manage',
  'databases:backups:view',
  'databases:backups:manage',
  'databases:backups:run',
  'databases:backups:restore',
  'nodes:backups:execute',
  'pki:ca:view',
  'pki:ca:create:root',
  'pki:ca:create:intermediate',
  'pki:ca:edit',
  'pki:ca:export',
  'pki:ca:revoke:root',
  'pki:ca:revoke:intermediate',
  'pki:cert:view',
  'pki:cert:issue',
  'pki:cert:revoke',
  'pki:cert:export',
  'pki:templates:view',
  'pki:templates:create',
  'pki:templates:edit',
  'pki:templates:delete',
  'domains:view',
  'domains:create',
  'domains:edit',
  'domains:delete',
  'domains:folders:manage',
  'proxy:view',
  'proxy:create',
  'proxy:edit',
  'proxy:delete',
  'proxy:raw:read',
  'proxy:raw:write',
  'proxy:advanced',
  'proxy:unrestricted',
  'proxy:maintenance:bypass',
  'proxy:folders:manage',
  'pages:view',
  'pages:create',
  'pages:edit',
  'pages:delete',
  'pages:deploy',
  'pages:deployments:manage',
  'pages:tags:manage',
  'pages:tokens:manage',
  'pages:folders:manage',
  'pages:settings:view',
  'pages:settings:edit',
  'proxy:templates:view',
  'proxy:templates:manage',
  'ssl:cert:view',
  'ssl:cert:issue',
  'ssl:cert:folders:manage',
  'ssl:cert:delete',
  'acl:view',
  'acl:create',
  'acl:edit',
  'acl:delete',
  'nodes:details',
  'nodes:create',
  'nodes:rename',
  'nodes:delete',
  'nodes:manage',
  'nodes:config:view',
  'nodes:logs',
  'nodes:files:read',
  'nodes:files:write',
  'nodes:lock',
  'nodes:folders:manage',
  'admin:users',
  'admin:users:folders:manage',
  'admin:groups',
  'admin:groups:folders:manage',
  'admin:audit',
  'audit:siem:view',
  'audit:siem:manage',
  'admin:details:certificates',
  'admin:update',
  'admin:alerts',
  'settings:gateway:view',
  'integrations:gitlab:view',
  'integrations:gitlab:manage',
  'integrations:gitlab:use',
  'integrations:gitlab:repo:read',
  'integrations:gitlab:repo:write',
  'integrations:gitlab:sandbox:clone',
  'integrations:github:view',
  'integrations:github:manage',
  'integrations:github:use',
  'integrations:github:repo:read',
  'integrations:github:repo:write',
  'integrations:git:view',
  'integrations:git:manage',
  'integrations:git:use',
  'integrations:git:repo:read',
  'integrations:git:repo:write',
  'integrations:ssh:view',
  'integrations:ssh:manage',
  'integrations:ssh:use',
  'integrations:cloudflare:view',
  'integrations:cloudflare:manage',
  'integrations:cloudflare:sync',
  'housekeeping:view',
  'housekeeping:run',
  'license:view',
  'license:manage',
  'ai:workspace:use',
  'feat:ai:use',
  'feat:ai:configure',
  'ai:sandbox:use',
  'ai:sandbox:tier:medium',
  'ai:sandbox:tier:high',
  'ai:sandbox:manage',
  'mcp:use',
  'inference:providers:view',
  'inference:providers:manage',
  'inference:models:manage',
  'inference:limits:manage',
  'inference:usage:view',
  'docker:containers:view',
  'docker:containers:create',
  'docker:containers:edit',
  'docker:containers:manage',
  'docker:containers:environment',
  'docker:containers:delete',
  'docker:containers:console',
  'docker:containers:files:read',
  'docker:containers:files:write',
  'docker:containers:export',
  'docker:containers:secrets',
  'docker:containers:webhooks',
  'docker:containers:mounts',
  'docker:containers:migrate',
  'docker:availability:manage',
  'docker:folders:manage',
  'docker:compose:view',
  'docker:compose:create',
  'docker:compose:manage',
  'docker:compose:delete',
  'docker:images:view',
  'docker:images:pull',
  'docker:images:delete',
  'docker:volumes:view',
  'docker:volumes:create',
  'docker:volumes:edit',
  'docker:volumes:delete',
  'docker:volumes:export',
  'docker:volumes:files:read',
  'docker:volumes:files:write',
  'docker:networks:view',
  'docker:networks:create',
  'docker:networks:edit',
  'docker:networks:delete',
  'docker:registries:view',
  'docker:registries:internal:pull',
  'docker:registries:internal:push',
  'docker:tasks',
  'docker:tasks:manage',
  'databases:view',
  'databases:create',
  'databases:edit',
  'databases:delete',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:credentials:reveal',
  'databases:folders:manage',
  'notifications:alerts:view',
  'notifications:alerts:manage',
  'notifications:webhooks:view',
  'notifications:webhooks:manage',
  'logs:environments:view',
  'logs:environments:create',
  'logs:environments:edit',
  'logs:environments:delete',
  'logs:environments:folders:manage',
  'logs:tokens:view',
  'logs:tokens:create',
  'logs:tokens:delete',
  'logs:schemas:view',
  'logs:schemas:create',
  'logs:schemas:edit',
  'logs:schemas:delete',
  'logs:schemas:folders:manage',
  'logs:read',
  'status-page:view',
  'status-page:manage',
  'status-page:incidents:create',
  'status-page:incidents:update',
  'status-page:incidents:resolve',
  'status-page:incidents:delete',
];

const DEMO_ADMIN_EXCLUDED_SCOPES = new Set([
  'pki:ca:export',
  'pki:cert:export',
  'proxy:raw:read',
  'proxy:raw:write',
  'proxy:unrestricted',
  'proxy:templates:manage',
  'nodes:console',
  'nodes:config:view',
  'nodes:files:read',
  'nodes:files:write',
  'pages:tokens:manage',
  'docker:containers:webhooks',
  'docker:containers:console',
  'docker:containers:files:read',
  'docker:containers:files:write',
  'docker:containers:export',
  'docker:containers:secrets',
  'docker:containers:environment',
  'docker:availability:manage',
  'docker:volumes:export',
  'docker:volumes:files:read',
  'docker:volumes:files:write',
  'docker:registries:internal:pull',
  'docker:registries:internal:push',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:credentials:reveal',
  'admin:audit',
  'audit:siem:view',
  'audit:siem:manage',
  'logs:tokens:view',
  'logs:tokens:create',
  'logs:tokens:delete',
  // Repository read access includes CI/CD variables, which can hold secrets.
  'integrations:gitlab:manage',
  'integrations:gitlab:use',
  'integrations:gitlab:repo:read',
  'integrations:gitlab:repo:write',
  'integrations:gitlab:sandbox:clone',
  'integrations:github:manage',
  'integrations:github:use',
  'integrations:github:repo:read',
  'integrations:github:repo:write',
  'integrations:git:manage',
  'integrations:git:use',
  'integrations:git:repo:read',
  'integrations:git:repo:write',
  'integrations:ssh:manage',
  'integrations:ssh:use',
  'integrations:cloudflare:manage',
  'integrations:cloudflare:sync',
  'notifications:webhooks:view',
  'notifications:webhooks:manage',
]);

/**
 * Demo visitors retain ordinary resource-management scopes so the existing UI
 * remains explorable. DemoModePolicy is the authorization boundary. Remove
 * capabilities that would expose secrets or external execution even while
 * rendering a read-only screen.
 */
export const DEMO_ADMIN_SCOPES: readonly string[] = ADMIN_SCOPES.filter(
  (scope) =>
    !DEMO_ADMIN_EXCLUDED_SCOPES.has(scope) &&
    !scope.startsWith('ai:') &&
    !scope.startsWith('feat:ai:') &&
    !scope.startsWith('mcp:') &&
    !scope.startsWith('inference:')
);

export const DEMO_ADMIN_GROUP = {
  name: 'demo-admin',
  description: 'Public demo administrator — UI access governed by immutable demo restrictions',
  scopes: DEMO_ADMIN_SCOPES,
} as const;

/** Operator group: operational + management scopes */
export const OPERATOR_SCOPES: readonly string[] = [
  'storage:view',
  'storage:create',
  'storage:edit',
  // Lets backups hand the saved credentials to the runner without revealing them.
  'storage:credentials:use',
  'storage:objects:read',
  'storage:objects:write',
  'storage:folders:manage',
  'databases:backups:view',
  'databases:backups:manage',
  'databases:backups:run',
  'nodes:backups:execute',
  'pki:ca:view',
  'pki:cert:view',
  'pki:cert:issue',
  'pki:cert:revoke',
  'pki:cert:export',
  'pki:templates:view',
  'pki:templates:create',
  'pki:templates:edit',
  'pki:templates:delete',
  'domains:view',
  'domains:create',
  'domains:edit',
  'domains:folders:manage',
  'proxy:view',
  'proxy:create',
  'proxy:edit',
  'proxy:maintenance:bypass',
  'proxy:folders:manage',
  'pages:view',
  'pages:create',
  'pages:edit',
  'pages:deploy',
  'pages:deployments:manage',
  'pages:tags:manage',
  'pages:folders:manage',
  'pages:settings:view',
  // Template content is raw nginx configuration, so template management stays with admins.
  'proxy:templates:view',
  'ssl:cert:view',
  'ssl:cert:issue',
  'ssl:cert:folders:manage',
  'acl:view',
  'acl:create',
  'acl:edit',
  'nodes:details',
  'nodes:config:view',
  'nodes:logs',
  'nodes:files:read',
  'nodes:files:write',
  'nodes:rename',
  'nodes:folders:manage',
  'ai:workspace:use',
  'feat:ai:use',
  'ai:sandbox:use',
  'mcp:use',
  'admin:alerts',
  'license:view',
  // Connector metadata and synced projects only: repository files, job logs, and variable keys stay with admins.
  'integrations:gitlab:view',
  'integrations:cloudflare:view',
  'docker:containers:view',
  'docker:containers:edit',
  'docker:containers:manage',
  'docker:containers:environment',
  'docker:containers:webhooks',
  'docker:folders:manage',
  'docker:compose:view',
  'docker:compose:manage',
  'docker:images:view',
  'docker:volumes:view',
  'docker:volumes:files:read',
  'docker:networks:view',
  'docker:registries:view',
  'docker:tasks',
  'docker:tasks:manage',
  'databases:view',
  'databases:create',
  'databases:edit',
  'databases:delete',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:folders:manage',
  'notifications:alerts:view',
  'notifications:alerts:manage',
  'notifications:webhooks:view',
  'notifications:webhooks:manage',
  'logs:environments:view',
  'logs:schemas:view',
  'logs:environments:folders:manage',
  'logs:schemas:folders:manage',
  'logs:tokens:view',
  'logs:tokens:create',
  'logs:tokens:delete',
  'logs:read',
];

/** Viewer group: read-only scopes */
export const VIEWER_SCOPES: readonly string[] = [
  'storage:view',
  'databases:backups:view',
  'pki:ca:view',
  'pki:cert:view',
  'pki:templates:view',
  'domains:view',
  'proxy:view',
  'proxy:templates:view',
  'pages:view',
  'pages:settings:view',
  'ssl:cert:view',
  'acl:view',
  'docker:containers:view',
  'docker:compose:view',
  'docker:images:view',
  'docker:volumes:view',
  'docker:volumes:files:read',
  'docker:networks:view',
  'docker:registries:view',
  'databases:view',
  'notifications:alerts:view',
  'notifications:webhooks:view',
  'logs:environments:view',
  'logs:schemas:view',
  'logs:tokens:view',
  'logs:read',
  'integrations:gitlab:view',
  'integrations:cloudflare:view',
  'ai:workspace:use',
];

/** Guest group: authenticated account access without infrastructure permissions. */
export const GUEST_SCOPES: readonly string[] = [];

/** Built-in group definitions (order matters for display — most privileged first) */
export const BUILTIN_GROUPS = [
  {
    name: 'system-admin',
    description: 'System administrator — full access, protected from non-system-admins',
    scopes: SYSTEM_ADMIN_SCOPES,
  },
  { name: 'admin', description: 'Full access to all features except system protection', scopes: ADMIN_SCOPES },
  {
    name: 'operator',
    description: 'Operational access — manage certificates, proxies, and SSL',
    scopes: OPERATOR_SCOPES,
  },
  { name: 'viewer', description: 'Read-only access to all resources', scopes: VIEWER_SCOPES },
  {
    name: 'guest',
    description: 'Account access only — no infrastructure permissions',
    scopes: GUEST_SCOPES,
  },
] as const;

export const BUILTIN_GROUP_NAMES: string[] = BUILTIN_GROUPS.map((g) => g.name);

export function getBootstrapBuiltinGroups(deploymentMode: 'standard' | 'demo') {
  return deploymentMode === 'demo' ? [...BUILTIN_GROUPS, DEMO_ADMIN_GROUP] : [...BUILTIN_GROUPS];
}

/** Scopes that support resource-level suffixes (e.g., pki:cert:issue:ca-uuid) */
