import { GIT_SCOPABLE } from './scopes-git.js';

export const FOLDER_CREATION_SCOPES = [
  'domains:create',
  'proxy:create',
  'pages:create',
  'nodes:create',
  'databases:create',
  'storage:create',
  'ssl:cert:issue',
  'logs:environments:create',
  'logs:schemas:create',
  'docker:containers:create',
  'docker:compose:create',
  'docker:networks:create',
  'docker:volumes:create',
  'docker:images:pull',
] as const;

export const RESOURCE_SCOPABLE: readonly string[] = [
  'admin:users',
  'admin:groups',
  'admin:users:impersonate',
  ...FOLDER_CREATION_SCOPES,
  // Hosting qualifiers: connector ID for accounts/create/billing, resource ID for VM actions.
  'integrations:hosting:view',
  'integrations:hosting:manage',
  // Git qualifiers: <connectorId>, then GitLab group/<id> or project/<id>, GitHub owner/<id> or repo/<id>
  // (see scopes-git.ts). Connector administration (manage) takes the connector only.
  ...GIT_SCOPABLE,
  'hosting:resources:view',
  'hosting:resources:create',
  'hosting:resources:power',
  'hosting:resources:resize',
  'hosting:snapshots:view',
  'hosting:snapshots:create',
  'hosting:snapshots:delete',
  'hosting:snapshots:restore',
  'hosting:snapshots:folders:manage',
  'hosting:resources:delete',
  'hosting:resources:recover',
  'hosting:billing:view',
  'hosting:billing:topup',
  // PKI (CA qualifiers are CA IDs; certificate qualifiers are issuing CA IDs)
  'pki:ca:view',
  'pki:ca:create:intermediate',
  'pki:ca:edit',
  'pki:ca:export',
  'pki:cert:view',
  'pki:cert:issue',
  'pki:cert:revoke',
  'pki:cert:export',
  // Proxy
  'proxy:view',
  'proxy:edit',
  'proxy:delete',
  'proxy:advanced',
  'proxy:unrestricted',
  'proxy:maintenance:bypass',
  'proxy:raw:read',
  'proxy:raw:write',
  'proxy:templates:view',
  'proxy:templates:manage',
  // Pages (all qualifiers are Page Project IDs)
  'pages:view',
  'pages:edit',
  'pages:delete',
  'pages:deploy',
  'pages:deployments:manage',
  'pages:tags:manage',
  'pages:tokens:manage',
  // Domains
  'domains:view',
  'domains:edit',
  'domains:delete',
  // SSL
  'ssl:cert:view',
  'ssl:cert:delete',
  // ACL
  'acl:view',
  'acl:edit',
  'acl:delete',
  // Nodes
  'nodes:details',
  'nodes:manage',
  'nodes:config:view',
  'nodes:logs',
  'nodes:console',
  'nodes:files:read',
  'nodes:files:write',
  'nodes:rename',
  'nodes:delete',
  'nodes:lock',
  // Docker containers
  'docker:containers:view',
  'docker:containers:edit',
  'docker:containers:manage',
  'docker:containers:environment',
  'docker:containers:delete',
  'docker:containers:console',
  'docker:containers:files:read',
  'docker:containers:files:write',
  'docker:containers:export',
  'docker:containers:secrets',
  'docker:containers:webhooks',
  'docker:containers:mounts',
  'docker:containers:migrate',
  'docker:availability:manage',
  // Docker Compose Projects
  'docker:compose:view',
  'docker:compose:manage',
  'docker:compose:delete',
  'docker:registries:internal:pull',
  'docker:registries:internal:push',
  // Docker images
  'docker:images:view',
  'docker:images:delete',
  // Docker volumes
  'docker:volumes:view',
  'docker:volumes:edit',
  'docker:volumes:delete',
  'docker:volumes:export',
  'docker:volumes:files:read',
  'docker:volumes:files:write',
  // Docker networks
  'docker:networks:view',
  'docker:networks:edit',
  'docker:networks:delete',
  // Docker tasks
  'docker:tasks',
  'docker:tasks:manage',
  // Databases
  'databases:view',
  'storage:view',
  'storage:edit',
  'storage:delete',
  'storage:credentials:reveal',
  'storage:credentials:use',
  'storage:iam',
  'storage:objects:read',
  'storage:objects:write',
  'storage:objects:admin',
  'databases:backups:view',
  'databases:backups:manage',
  'databases:backups:run',
  'databases:backups:restore',
  'nodes:backups:execute',

  'databases:edit',
  'databases:delete',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:credentials:reveal',
  // Logging
  'logs:environments:view',
  'logs:environments:edit',
  'logs:environments:delete',
  'logs:tokens:view',
  'logs:tokens:create',
  'logs:tokens:delete',
  'logs:schemas:view',
  'logs:schemas:edit',
  'logs:schemas:delete',
  'logs:read',
];

/**
 * Resource-scopable permissions that may target a resource folder.
 * Creation targets the destination folder; other actions target its contents.
 * Folder-management permissions remain separate from resource actions.
 */
export const FOLDER_SCOPABLE: readonly string[] = [
  'admin:users',
  'admin:groups',
  'admin:users:impersonate',
  ...FOLDER_CREATION_SCOPES,
  'docker:networks:view',
  'docker:networks:edit',
  'docker:networks:delete',
  'docker:volumes:view',
  'docker:volumes:edit',
  'docker:volumes:delete',
  'docker:volumes:export',
  'docker:volumes:files:read',
  'docker:volumes:files:write',
  'docker:images:view',
  'docker:images:delete',
  'ssl:cert:view',
  'ssl:cert:delete',
  // Domains
  'domains:view',
  'domains:edit',
  'domains:delete',
  // Ingress routes
  'proxy:view',
  'proxy:edit',
  'proxy:delete',
  'proxy:advanced',
  'proxy:unrestricted',
  'proxy:maintenance:bypass',
  'proxy:raw:read',
  'proxy:raw:write',
  // Pages
  'pages:view',
  'pages:edit',
  'pages:delete',
  'pages:deploy',
  'pages:deployments:manage',
  'pages:tags:manage',
  'pages:tokens:manage',
  // Nodes
  'nodes:details',
  'nodes:manage',
  'nodes:config:view',
  'nodes:logs',
  'nodes:console',
  'nodes:files:read',
  'nodes:files:write',
  'nodes:rename',
  'nodes:delete',
  'nodes:lock',
  // Docker containers and deployments
  'docker:containers:view',
  'docker:containers:edit',
  'docker:containers:manage',
  'docker:containers:environment',
  'docker:containers:delete',
  'docker:containers:console',
  'docker:containers:files:read',
  'docker:containers:files:write',
  'docker:containers:export',
  'docker:containers:secrets',
  'docker:containers:webhooks',
  'docker:containers:mounts',
  'docker:containers:migrate',
  'docker:availability:manage',
  // Docker Compose Projects
  'docker:compose:view',
  'docker:compose:manage',
  'docker:compose:delete',
  // Databases
  'databases:view',
  'storage:view',
  'storage:edit',
  'storage:delete',
  'storage:credentials:reveal',
  'storage:credentials:use',
  'storage:iam',
  'storage:objects:read',
  'storage:objects:write',
  'storage:objects:admin',
  'databases:backups:view',
  'databases:backups:manage',
  'databases:backups:run',
  'databases:backups:restore',
  'nodes:backups:execute',

  'databases:edit',
  'databases:delete',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:credentials:reveal',
  // Logging environments and schemas. Ingest tokens and log reading are qualified by the
  // environment ID, so their folder grants resolve through logging environment folders.
  'logs:environments:view',
  'logs:environments:edit',
  'logs:environments:delete',
  'logs:tokens:view',
  'logs:tokens:create',
  'logs:tokens:delete',
  'logs:schemas:view',
  'logs:schemas:edit',
  'logs:schemas:delete',
  'logs:read',
];
