/**
 * Unified scope definitions for group and user-specific permissions.
 * Both session users (via group membership) and API tokens use these scopes.
 *
 * Naming convention: domain:resource:action[:qualifier]
 * Resource-scopable scopes support suffixes: e.g. docker:containers:view:node-uuid
 */

export const ALL_SCOPES = [
  // ── PKI: Certificate Authorities ─────────────────────────────────
  'pki:ca:view:root',
  'pki:ca:view:intermediate',
  'pki:ca:create:root',
  'pki:ca:create:intermediate',
  'pki:ca:revoke:root',
  'pki:ca:revoke:intermediate',
  // ── PKI: Certificates ────────────────────────────────────────────
  'pki:cert:view',
  'pki:cert:issue',
  'pki:cert:revoke',
  'pki:cert:export',
  // ── PKI: Certificate Templates ───────────────────────────────────
  'pki:templates:view',
  'pki:templates:create',
  'pki:templates:edit',
  'pki:templates:delete',
  // ── Domains ──────────────────────────────────────────────────────
  'domains:view',
  'domains:create',
  'domains:edit',
  'domains:delete',
  'domains:folders:manage',
  // ── Ingress Routes (proxy-host API resources) ────────────────────
  'proxy:view',
  'proxy:create',
  'proxy:edit',
  'proxy:delete',
  'proxy:raw:read',
  'proxy:raw:write',
  'proxy:raw:toggle',
  'proxy:raw:bypass',
  'proxy:advanced',
  'proxy:advanced:bypass',
  'proxy:maintenance:bypass',
  'proxy:folders:manage',
  // ── Pages ─────────────────────────────────────────────────────────
  'pages:view',
  'pages:create',
  'pages:edit',
  'pages:delete',
  'pages:deploy',
  'pages:deployments:manage',
  'pages:tags:manage',
  'pages:tokens:manage',
  'pages:folders:manage',
  'pages:settings:view',
  'pages:settings:edit',
  // ── Proxy Templates ──────────────────────────────────────────────
  'proxy:templates:view',
  'proxy:templates:create',
  'proxy:templates:edit',
  'proxy:templates:delete',
  // ── SSL Certificates ─────────────────────────────────────────────
  'ssl:cert:view',
  'ssl:cert:issue',
  'ssl:cert:delete',
  'ssl:cert:revoke',
  'ssl:cert:export',
  // ── Access Control Lists ─────────────────────────────────────────
  'acl:view',
  'acl:create',
  'acl:edit',
  'acl:delete',
  // ── Nodes ────────────────────────────────────────────────────────
  'nodes:details',
  'nodes:create',
  'nodes:rename',
  'nodes:delete',
  'nodes:config:view',
  'nodes:config:edit',
  'nodes:logs',
  'nodes:console',
  'nodes:files:read',
  'nodes:files:write',
  'nodes:lock',
  'nodes:folders:manage',
  // ── Administration ───────────────────────────────────────────────
  'admin:users',
  'admin:users:impersonate',
  'admin:users:folders:manage',
  'admin:groups',
  'admin:groups:folders:manage',
  'admin:audit',
  'audit:siem:view',
  'audit:siem:manage',
  'admin:system',
  'admin:details:certificates',
  'admin:update',
  'admin:alerts',
  // ── Gateway Settings ─────────────────────────────────────────────
  'settings:gateway:view',
  'settings:gateway:edit',
  // ── Integrations: GitLab ─────────────────────────────────────────
  'integrations:gitlab:view',
  'integrations:gitlab:manage',
  'integrations:gitlab:sync',
  'integrations:gitlab:system',
  'integrations:gitlab:projects:view',
  'integrations:gitlab:repo:read',
  'integrations:gitlab:repo:write',
  'integrations:gitlab:ci:view',
  'integrations:gitlab:ci:edit',
  'integrations:gitlab:variables:view',
  'integrations:gitlab:variables:edit',
  'integrations:gitlab:variables:delete',
  'integrations:gitlab:webhooks:manage',
  'integrations:gitlab:registry:manage',
  'integrations:gitlab:sandbox:clone',
  // ── Integrations: GitHub, generic Git, and external SSH ─────────
  'integrations:github:view',
  'integrations:github:manage',
  'integrations:github:system',
  'integrations:git:view',
  'integrations:git:manage',
  'integrations:git:system',
  'integrations:ssh:view',
  'integrations:ssh:manage',
  'integrations:ssh:use',
  // ── Integrations: Cloudflare ─────────────────────────────────────
  'integrations:cloudflare:view',
  'integrations:cloudflare:manage',
  // ── Housekeeping ─────────────────────────────────────────────────
  'housekeeping:view',
  'housekeeping:run',
  'housekeeping:configure',
  // ── Licensing ────────────────────────────────────────────────────
  'license:view',
  'license:manage',
  // ── Features ─────────────────────────────────────────────────────
  'ai:workspace:use',
  'feat:ai:use',
  'feat:ai:configure',
  'ai:skills:manage',
  'ai:sandbox:use',
  'ai:sandbox:tier:medium',
  'ai:sandbox:tier:high',
  'ai:sandbox:manage',
  'mcp:use',
  // ── Inference ────────────────────────────────────────────────────
  'inference:setup',
  'inference:providers:view',
  'inference:providers:manage',
  'inference:models:manage',
  'inference:limits:manage',
  'inference:usage:view',
  // ── Docker: Containers ───────────────────────────────────────────
  'docker:containers:view',
  'docker:containers:create',
  'docker:containers:edit',
  'docker:containers:config',
  'docker:containers:manage',
  'docker:containers:environment',
  'docker:containers:delete',
  'docker:containers:console',
  'docker:containers:files:read',
  'docker:containers:files:write',
  'docker:containers:export',
  'docker:containers:secrets',
  'docker:containers:webhooks',
  'docker:containers:mounts',
  'docker:containers:migrate',
  'docker:containers:folders:manage',
  // ── Docker: Compose Projects ─────────────────────────────────────
  'docker:compose:view',
  'docker:compose:create',
  'docker:compose:manage',
  'docker:compose:delete',
  // ── Docker: Images ───────────────────────────────────────────────
  'docker:images:view',
  'docker:images:pull',
  'docker:images:delete',
  // ── Docker: Volumes ──────────────────────────────────────────────
  'docker:volumes:view',
  'docker:volumes:create',
  'docker:volumes:delete',
  'docker:volumes:export',
  'docker:volumes:files:read',
  'docker:volumes:files:write',
  // ── Docker: Networks ─────────────────────────────────────────────
  'docker:networks:view',
  'docker:networks:create',
  'docker:networks:edit',
  'docker:networks:delete',
  // ── Docker: Registries ───────────────────────────────────────────
  'docker:registries:view',
  'docker:registries:create',
  'docker:registries:edit',
  'docker:registries:delete',
  'docker:registries:internal:pull',
  'docker:registries:internal:push',
  // ── Docker: Tasks ────────────────────────────────────────────────
  'docker:tasks',
  'docker:tasks:manage',
  // ── Databases ────────────────────────────────────────────────────
  'databases:view',
  'databases:create',
  'databases:edit',
  'databases:delete',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:credentials:reveal',
  'databases:folders:manage',
  // ── Notifications ────────────────────────────────────────────────
  'notifications:alerts:view',
  'notifications:alerts:create',
  'notifications:alerts:edit',
  'notifications:alerts:delete',
  'notifications:webhooks:view',
  'notifications:webhooks:create',
  'notifications:webhooks:edit',
  'notifications:webhooks:delete',
  'notifications:deliveries:view',
  'notifications:view',
  'notifications:manage',
  // ── External Logging ─────────────────────────────────────────────
  'logs:environments:view',
  'logs:environments:create',
  'logs:environments:edit',
  'logs:environments:delete',
  'logs:environments:folders:manage',
  'logs:tokens:view',
  'logs:tokens:create',
  'logs:tokens:delete',
  'logs:schemas:view',
  'logs:schemas:create',
  'logs:schemas:edit',
  'logs:schemas:delete',
  'logs:schemas:folders:manage',
  'logs:read',
  'logs:manage',
  // ── Status Page ──────────────────────────────────────────────────
  'status-page:view',
  'status-page:manage',
  'status-page:incidents:create',
  'status-page:incidents:update',
  'status-page:incidents:resolve',
  'status-page:incidents:delete',
] as const;

export type Scope = (typeof ALL_SCOPES)[number];

export const USER_ONLY_SCOPES = [
  'ai:workspace:use',
  'feat:ai:use',
  'feat:ai:configure',
  'ai:skills:manage',
  'ai:sandbox:use',
  'ai:sandbox:tier:medium',
  'ai:sandbox:tier:high',
  'ai:sandbox:manage',
  'mcp:use',
  'inference:setup',
] as const;
export const PROGRAMMATIC_DENIED_BASE_SCOPES = [
  ...USER_ONLY_SCOPES,
  'admin:system',
  'admin:users',
  'admin:users:impersonate',
  'admin:groups',
  'settings:gateway:view',
  'settings:gateway:edit',
  'integrations:gitlab:manage',
  'integrations:gitlab:system',
  'integrations:github:manage',
  'integrations:github:system',
  'integrations:git:manage',
  'integrations:git:system',
  'integrations:ssh:manage',
  'integrations:cloudflare:manage',
  'proxy:raw:read',
  'proxy:raw:write',
  'proxy:raw:toggle',
  'proxy:raw:bypass',
  'proxy:advanced:bypass',
  'proxy:maintenance:bypass',
  'nodes:config:view',
  'nodes:config:edit',
  'inference:providers:view',
  'inference:providers:manage',
  'inference:models:manage',
  'inference:limits:manage',
  'inference:usage:view',
] as const;

export const PROGRAMMATIC_DENIED_SCOPE_SET = new Set<string>(PROGRAMMATIC_DENIED_BASE_SCOPES);

export const API_TOKEN_SCOPES = ALL_SCOPES.filter((scope) => !PROGRAMMATIC_DENIED_SCOPE_SET.has(scope));

export const MCP_EXTERNAL_INTEGRATION_SCOPE_PREFIXES = [
  'integrations:gitlab:',
  'integrations:github:',
  'integrations:git:',
  'integrations:ssh:',
] as const;

export const MCP_TOKEN_SCOPES = API_TOKEN_SCOPES.filter(
  (scope) => !MCP_EXTERNAL_INTEGRATION_SCOPE_PREFIXES.some((prefix) => scope.startsWith(prefix))
);

/** System-admin group: every scope including admin:system (protected) */
