export const RESOURCE_SCOPABLE: readonly string[] = [
  // PKI
  'pki:ca:create:intermediate',
  'pki:cert:view',
  'pki:cert:issue',
  'pki:cert:revoke',
  'pki:cert:export',
  // Proxy
  'proxy:view',
  'proxy:create',
  'proxy:edit',
  'proxy:delete',
  'proxy:advanced',
  'proxy:advanced:bypass',
  'proxy:maintenance:bypass',
  'proxy:raw:read',
  'proxy:raw:write',
  'proxy:raw:toggle',
  'proxy:raw:bypass',
  'proxy:templates:view',
  'proxy:templates:edit',
  'proxy:templates:delete',
  // Pages (all qualifiers are Page Project IDs)
  'pages:view',
  'pages:edit',
  'pages:delete',
  'pages:deploy',
  'pages:deployments:manage',
  'pages:tags:manage',
  'pages:tokens:manage',
  // Domains
  'domains:view',
  'domains:edit',
  'domains:delete',
  // SSL
  'ssl:cert:view',
  'ssl:cert:delete',
  'ssl:cert:revoke',
  'ssl:cert:export',
  // ACL
  'acl:view',
  'acl:edit',
  'acl:delete',
  // Nodes
  'nodes:details',
  'nodes:config:view',
  'nodes:config:edit',
  'nodes:logs',
  'nodes:console',
  'nodes:files:read',
  'nodes:files:write',
  'nodes:rename',
  'nodes:delete',
  'nodes:lock',
  // Docker containers
  'docker:containers:view',
  'docker:containers:create',
  'docker:containers:edit',
  'docker:containers:config',
  'docker:containers:manage',
  'docker:containers:environment',
  'docker:containers:delete',
  'docker:containers:console',
  'docker:containers:files:read',
  'docker:containers:files:write',
  'docker:containers:export',
  'docker:containers:secrets',
  'docker:containers:webhooks',
  'docker:containers:mounts',
  'docker:containers:migrate',
  'docker:availability:manage',
  // Docker Compose Projects
  'docker:compose:view',
  'docker:compose:create',
  'docker:compose:manage',
  'docker:compose:delete',
  'docker:registries:internal:pull',
  'docker:registries:internal:push',
  // Docker images
  'docker:images:view',
  'docker:images:pull',
  'docker:images:delete',
  // Docker volumes
  'docker:volumes:view',
  'docker:volumes:create',
  'docker:volumes:delete',
  'docker:volumes:export',
  'docker:volumes:files:read',
  'docker:volumes:files:write',
  // Docker networks
  'docker:networks:view',
  'docker:networks:create',
  'docker:networks:edit',
  'docker:networks:delete',
  // Docker tasks
  'docker:tasks',
  'docker:tasks:manage',
  // Databases
  'databases:view',
  'databases:edit',
  'databases:delete',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:credentials:reveal',
  // Logging
  'logs:environments:view',
  'logs:environments:edit',
  'logs:environments:delete',
  'logs:tokens:view',
  'logs:tokens:create',
  'logs:tokens:delete',
  'logs:schemas:view',
  'logs:schemas:edit',
  'logs:schemas:delete',
  'logs:read',
];

/**
 * Resource-scopable permissions that may target a resource folder.
 * Creation and folder-management permissions intentionally remain broad or
 * node-scoped because they do not act on an existing resource.
 */
export const FOLDER_SCOPABLE: readonly string[] = [
  // Domains
  'domains:view',
  'domains:edit',
  'domains:delete',
  // Ingress routes
  'proxy:view',
  'proxy:edit',
  'proxy:delete',
  'proxy:advanced',
  'proxy:advanced:bypass',
  'proxy:maintenance:bypass',
  'proxy:raw:read',
  'proxy:raw:write',
  'proxy:raw:toggle',
  'proxy:raw:bypass',
  // Pages
  'pages:view',
  'pages:edit',
  'pages:delete',
  'pages:deploy',
  'pages:deployments:manage',
  'pages:tags:manage',
  'pages:tokens:manage',
  // Nodes
  'nodes:details',
  'nodes:config:view',
  'nodes:config:edit',
  'nodes:logs',
  'nodes:console',
  'nodes:files:read',
  'nodes:files:write',
  'nodes:rename',
  'nodes:delete',
  'nodes:lock',
  // Docker containers and deployments
  'docker:containers:view',
  'docker:containers:edit',
  'docker:containers:config',
  'docker:containers:manage',
  'docker:containers:environment',
  'docker:containers:delete',
  'docker:containers:console',
  'docker:containers:files:read',
  'docker:containers:files:write',
  'docker:containers:export',
  'docker:containers:secrets',
  'docker:containers:webhooks',
  'docker:containers:mounts',
  'docker:containers:migrate',
  'docker:availability:manage',
  // Docker Compose Projects
  'docker:compose:view',
  'docker:compose:manage',
  'docker:compose:delete',
  // Databases
  'databases:view',
  'databases:edit',
  'databases:delete',
  'databases:query:read',
  'databases:query:write',
  'databases:query:admin',
  'databases:credentials:reveal',
  // Logging environments and schemas
  'logs:environments:view',
  'logs:environments:edit',
  'logs:environments:delete',
  'logs:schemas:view',
  'logs:schemas:edit',
  'logs:schemas:delete',
  'logs:read',
];
