import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { analyzeTemplateContent } from "./nginx-template-analysis";

// Built-in template sources, generated by the backend's nginx-template-context test.
const builtins = JSON.parse(
  readFileSync(resolve("src/test/nginx-builtin-templates.json"), "utf8")
) as { templates: Record<string, string> };

const ADDITIONAL_ROUTES =
  "{{{renderAdditionalRoutes additionalRoutes id accessList rateLimitEnabled rateLimitBurst connectionsPerIp}}}";

describe("analyzeTemplateContent", () => {
  it.each(
    Object.entries(builtins.templates)
  )("finds no errors in the built-in %s template", (_, content) => {
    expect(analyzeTemplateContent(content, [])).toEqual({ errorLines: [], errorRanges: [] });
  });

  it("accepts the additional routes placeholder every proxy template carries", () => {
    expect(analyzeTemplateContent(`server {\n  ${ADDITIONAL_ROUTES}\n}`, [])).toEqual({
      errorLines: [],
      errorRanges: [],
    });
  });

  it("accepts the template's own variables", () => {
    expect(analyzeTemplateContent("add_header X-Team {{team}};", ["team"]).errorRanges).toEqual([]);
  });

  it("marks unknown variables and helpers", () => {
    const content = "server_name {{hostName}};\n{{shout serverNames}}";
    expect(analyzeTemplateContent(content, []).errorRanges).toEqual([
      { from: 14, to: 22 },
      { from: 28, to: 33 },
    ]);
  });

  it("marks unbalanced blocks where they open and where they close wrongly", () => {
    const content = "{{#if sslEnabled}}\nlisten 443 ssl;\n{{/unless}}\n{{#each customHeaders}}";
    expect(analyzeTemplateContent(content, []).errorLines).toEqual([1, 3, 4]);
  });
});
