// Generated from packages/backend/src/lib/scopes-implications.ts. Do not edit by hand.
// Regenerate: cd packages/backend && UPDATE_SCOPE_IMPLICATIONS=1 pnpm vitest run src/lib/scopes-implications.test.ts

/** Required base scope -> every base scope that satisfies it (transitive, qualifier-preserving). */
export const IMPLIED_SCOPES_BY_REQUIRED_SCOPE: Readonly<Record<string, readonly string[]>> = {
  "acl:view": ["acl:delete", "acl:edit"],
  "audit:siem:view": ["audit:siem:manage"],
  "databases:backups:view": [
    "databases:backups:manage",
    "databases:backups:restore",
    "databases:backups:run",
  ],
  "databases:query:read": ["databases:query:admin", "databases:query:write"],
  "databases:query:write": ["databases:query:admin"],
  "databases:view": [
    "databases:credentials:reveal",
    "databases:delete",
    "databases:edit",
    "databases:query:admin",
    "databases:query:read",
    "databases:query:write",
  ],
  "docker:compose:view": ["docker:compose:delete", "docker:compose:manage"],
  "docker:containers:view": [
    "docker:availability:manage",
    "docker:containers:console",
    "docker:containers:delete",
    "docker:containers:edit",
    "docker:containers:environment",
    "docker:containers:export",
    "docker:containers:files:read",
    "docker:containers:files:write",
    "docker:containers:manage",
    "docker:containers:migrate",
    "docker:containers:mounts",
    "docker:containers:secrets",
    "docker:containers:webhooks",
  ],
  "docker:images:view": ["docker:images:delete"],
  "docker:networks:view": ["docker:networks:delete", "docker:networks:edit"],
  "docker:registries:view": ["docker:registries:delete", "docker:registries:edit"],
  "docker:tasks": ["docker:tasks:manage"],
  "docker:volumes:view": [
    "docker:volumes:delete",
    "docker:volumes:edit",
    "docker:volumes:export",
    "docker:volumes:files:read",
    "docker:volumes:files:write",
  ],
  "domains:view": ["domains:delete", "domains:edit"],
  "hosting:billing:view": ["hosting:billing:topup"],
  "hosting:resources:view": [
    "hosting:resources:delete",
    "hosting:resources:power",
    "hosting:resources:recover",
    "hosting:resources:resize",
  ],
  "hosting:snapshots:view": [
    "hosting:snapshots:create",
    "hosting:snapshots:delete",
    "hosting:snapshots:folders:manage",
    "hosting:snapshots:restore",
  ],
  "housekeeping:view": ["housekeeping:configure", "housekeeping:run"],
  "inference:providers:view": ["inference:models:manage", "inference:providers:manage"],
  "integrations:cloudflare:view": [
    "integrations:cloudflare:manage",
    "integrations:cloudflare:sync",
  ],
  "integrations:git:view": [
    "integrations:git:manage",
    "integrations:git:repo:read",
    "integrations:git:repo:write",
    "integrations:git:use",
  ],
  "integrations:github:view": [
    "integrations:github:manage",
    "integrations:github:repo:read",
    "integrations:github:repo:write",
    "integrations:github:use",
  ],
  "integrations:gitlab:view": [
    "integrations:gitlab:manage",
    "integrations:gitlab:repo:read",
    "integrations:gitlab:repo:write",
    "integrations:gitlab:sandbox:clone",
    "integrations:gitlab:use",
  ],
  "integrations:hosting:view": ["integrations:hosting:manage"],
  "integrations:ssh:view": ["integrations:ssh:manage", "integrations:ssh:use"],
  "license:view": ["license:manage"],
  "logs:environments:view": [
    "logs:environments:delete",
    "logs:environments:edit",
    "logs:read",
    "logs:tokens:delete",
    "logs:tokens:view",
  ],
  "logs:schemas:view": ["logs:schemas:delete", "logs:schemas:edit"],
  "logs:tokens:view": ["logs:tokens:delete"],
  "nodes:config:view": ["nodes:manage"],
  "nodes:details": [
    "nodes:config:view",
    "nodes:console",
    "nodes:delete",
    "nodes:files:read",
    "nodes:files:write",
    "nodes:lock",
    "nodes:logs",
    "nodes:manage",
    "nodes:rename",
  ],
  "notifications:alerts:view": ["notifications:alerts:manage"],
  "notifications:webhooks:view": ["notifications:webhooks:manage"],
  "pages:settings:view": ["pages:settings:edit"],
  "pages:view": [
    "pages:delete",
    "pages:deploy",
    "pages:deployments:manage",
    "pages:edit",
    "pages:tags:manage",
    "pages:tokens:manage",
  ],
  "pki:ca:view": [
    "pki:ca:edit",
    "pki:ca:export",
    "pki:ca:revoke:intermediate",
    "pki:ca:revoke:root",
  ],
  "pki:cert:view": ["pki:cert:export", "pki:cert:revoke"],
  "pki:templates:view": ["pki:templates:delete", "pki:templates:edit"],
  "proxy:templates:view": ["proxy:templates:manage"],
  "proxy:view": [
    "proxy:advanced",
    "proxy:delete",
    "proxy:edit",
    "proxy:raw:read",
    "proxy:raw:write",
    "proxy:unrestricted",
  ],
  "settings:gateway:view": ["settings:gateway:edit"],
  "ssl:cert:view": ["ssl:cert:delete"],
  "status-page:view": [
    "status-page:incidents:delete",
    "status-page:incidents:resolve",
    "status-page:incidents:update",
    "status-page:manage",
  ],
  "storage:credentials:use": ["storage:credentials:reveal"],
  "storage:objects:read": ["storage:objects:admin", "storage:objects:write"],
  "storage:objects:write": ["storage:objects:admin"],
  "storage:view": [
    "storage:credentials:reveal",
    "storage:credentials:use",
    "storage:delete",
    "storage:edit",
    "storage:iam",
    "storage:objects:admin",
    "storage:objects:read",
    "storage:objects:write",
  ],
};
