export const CORE_TOKEN_SCOPES = [
  // PKI: Certificate Authorities
  {
    value: "pki:ca:view:root",
    label: "View Root CAs",
    desc: "View root certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:view:intermediate",
    label: "View Intermediate CAs",
    desc: "View intermediate certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:create:root",
    label: "Create Root CAs",
    desc: "Create new root certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:create:intermediate",
    label: "Create Intermediate CAs",
    desc: "Create intermediate CAs under a root",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:revoke:root",
    label: "Revoke Root CAs",
    desc: "Revoke root certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  {
    value: "pki:ca:revoke:intermediate",
    label: "Revoke Intermediate CAs",
    desc: "Revoke intermediate certificate authorities",
    group: "PKI: Certificate Authorities",
  },
  // PKI: Certificates
  {
    value: "pki:cert:view",
    label: "View Certificates",
    desc: "View issued certificates",
    group: "PKI: Certificates",
  },
  {
    value: "pki:cert:issue",
    label: "Issue Certificates",
    desc: "Issue new certificates",
    group: "PKI: Certificates",
  },
  {
    value: "pki:cert:revoke",
    label: "Revoke Certificates",
    desc: "Revoke issued certificates",
    group: "PKI: Certificates",
  },
  {
    value: "pki:cert:export",
    label: "Export Certificates",
    desc: "Export certificates and keys",
    group: "PKI: Certificates",
  },
  // PKI: Templates
  {
    value: "pki:templates:view",
    label: "View Templates",
    desc: "View certificate templates",
    group: "PKI: Templates",
  },
  {
    value: "pki:templates:create",
    label: "Create Templates",
    desc: "Create certificate templates",
    group: "PKI: Templates",
  },
  {
    value: "pki:templates:edit",
    label: "Edit Templates",
    desc: "Edit certificate templates",
    group: "PKI: Templates",
  },
  {
    value: "pki:templates:delete",
    label: "Delete Templates",
    desc: "Delete certificate templates",
    group: "PKI: Templates",
  },
  // Domains
  { value: "domains:view", label: "View Domains", desc: "View managed domains", group: "Domains" },
  {
    value: "domains:create",
    label: "Create Domains",
    desc: "Create managed domains",
    group: "Domains",
  },
  { value: "domains:edit", label: "Edit Domains", desc: "Edit managed domains", group: "Domains" },
  {
    value: "domains:delete",
    label: "Delete Domains",
    desc: "Delete managed domains",
    group: "Domains",
  },
  {
    value: "domains:folders:manage",
    label: "Manage Domain Folders",
    desc: "Organize managed domains into folders",
    group: "Domains",
  },
  // Routes
  {
    value: "proxy:view",
    label: "View Routes",
    desc: "View and search ingress routes",
    group: "Routes",
  },
  {
    value: "proxy:create",
    label: "Create Routes",
    desc: "Create new ingress routes",
    group: "Routes",
  },
  {
    value: "proxy:edit",
    label: "Edit Routes",
    desc: "Edit ingress route configuration",
    group: "Routes",
  },
  {
    value: "proxy:delete",
    label: "Delete Routes",
    desc: "Delete ingress routes",
    group: "Routes",
  },
  {
    value: "proxy:advanced",
    label: "Advanced Proxy Config",
    desc: "Use advanced proxy configuration",
    group: "Routes",
  },
  {
    value: "proxy:advanced:bypass",
    label: "Bypass Advanced Config Restrictions",
    desc: "Save unrestricted advanced nginx snippets",
    group: "Routes",
  },
  {
    value: "proxy:maintenance:bypass",
    label: "Issue Maintenance Access",
    desc: "Create temporary access codes for maintained routes",
    group: "Routes",
  },
  {
    value: "proxy:raw:read",
    label: "Read Raw Config",
    desc: "View raw nginx configuration",
    group: "Routes",
  },
  {
    value: "proxy:raw:write",
    label: "Write Raw Config",
    desc: "Edit raw nginx configuration",
    group: "Routes",
  },
  {
    value: "proxy:raw:toggle",
    label: "Toggle Raw Config",
    desc: "Switch between managed and raw config mode",
    group: "Routes",
  },
  {
    value: "proxy:raw:bypass",
    label: "Bypass Raw Config Restrictions",
    desc: "Save raw nginx config without dangerous directive restrictions",
    group: "Routes",
  },
  {
    value: "proxy:folders:manage",
    label: "Manage Route Folders",
    desc: "Create, reorder, and remove route folders",
    group: "Routes",
  },
  // Pages
  {
    value: "pages:view",
    label: "View Pages",
    desc: "View Page Projects, Deployments, Tags, previews, and usage",
    group: "Pages",
  },
  {
    value: "pages:create",
    label: "Create Page Projects",
    desc: "Create static Page Projects",
    group: "Pages",
  },
  {
    value: "pages:edit",
    label: "Edit Page Projects",
    desc: "Rename Page Projects and edit their retention and quota settings",
    group: "Pages",
  },
  {
    value: "pages:delete",
    label: "Delete Page Projects",
    desc: "Delete eligible Page Projects",
    group: "Pages",
  },
  {
    value: "pages:deploy",
    label: "Deploy Pages",
    desc: "Create and upload static Deployments",
    group: "Pages",
  },
  {
    value: "pages:deployments:manage",
    label: "Manage Page Deployments",
    desc: "Pin, unpin, clean up, and delete eligible Deployments",
    group: "Pages",
  },
  {
    value: "pages:tags:manage",
    label: "Manage Page Tags",
    desc: "Create, move, and delete Page Project Tags",
    group: "Pages",
  },
  {
    value: "pages:tokens:manage",
    label: "Manage Page Deploy Tokens",
    desc: "Create, restrict, and revoke Project deploy credentials",
    group: "Pages",
  },
  {
    value: "pages:folders:manage",
    label: "Manage Page Folders",
    desc: "Create, reorder, and remove Page Project folders",
    group: "Pages",
  },
  {
    value: "pages:settings:view",
    label: "View Pages Settings",
    desc: "View wildcard profile and storage defaults",
    group: "Pages",
  },
  {
    value: "pages:settings:edit",
    label: "Edit Pages Settings",
    desc: "Configure and migrate the wildcard Pages profile and storage defaults",
    group: "Pages",
  },
  // Proxy Templates
  {
    value: "proxy:templates:view",
    label: "View Nginx Templates",
    desc: "View nginx templates",
    group: "Proxy Templates",
  },
  {
    value: "proxy:templates:create",
    label: "Create Nginx Templates",
    desc: "Create nginx templates",
    group: "Proxy Templates",
  },
  {
    value: "proxy:templates:edit",
    label: "Edit Nginx Templates",
    desc: "Edit nginx templates",
    group: "Proxy Templates",
  },
  {
    value: "proxy:templates:delete",
    label: "Delete Nginx Templates",
    desc: "Delete nginx templates",
    group: "Proxy Templates",
  },
  // SSL Certificates
  {
    value: "ssl:cert:view",
    label: "View SSL Certificates",
    desc: "View SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:issue",
    label: "Issue SSL Certificates",
    desc: "Provision ACME or upload SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:folders:manage",
    label: "Manage SSL Certificate Folders",
    desc: "Organize SSL certificates into folders",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:delete",
    label: "Delete SSL Certificates",
    desc: "Delete SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:revoke",
    label: "Revoke SSL Certificates",
    desc: "Revoke SSL certificates",
    group: "SSL Certificates",
  },
  {
    value: "ssl:cert:export",
    label: "Export SSL Certificates",
    desc: "Export SSL certificates",
    group: "SSL Certificates",
  },
  // Access Control Lists
  {
    value: "acl:view",
    label: "View Access Lists",
    desc: "View access control lists",
    group: "Access Control",
  },
  {
    value: "acl:create",
    label: "Create Access Lists",
    desc: "Create access control lists",
    group: "Access Control",
  },
  {
    value: "acl:edit",
    label: "Edit Access Lists",
    desc: "Edit access control lists",
    group: "Access Control",
  },
  {
    value: "acl:delete",
    label: "Delete Access Lists",
    desc: "Delete access control lists",
    group: "Access Control",
  },
  // Nodes
  { value: "nodes:details", label: "View Nodes", desc: "View managed nodes", group: "Nodes" },
  { value: "nodes:create", label: "Create Nodes", desc: "Enroll new nodes", group: "Nodes" },
  { value: "nodes:rename", label: "Rename Nodes", desc: "Rename nodes", group: "Nodes" },
  { value: "nodes:delete", label: "Delete Nodes", desc: "Remove nodes", group: "Nodes" },
  {
    value: "nodes:lock",
    label: "Lock Service Creation",
    desc: "Prevent new proxy hosts or containers on selected nodes",
    group: "Nodes",
  },
  {
    value: "nodes:config:view",
    label: "View Node Config",
    desc: "View node nginx configuration",
    group: "Nodes",
  },
  {
    value: "nodes:config:edit",
    label: "Edit Node Config",
    desc: "Edit node nginx configuration",
    group: "Nodes",
  },
  {
    value: "nodes:logs",
    label: "View Node Logs",
    desc: "View node daemon and nginx logs",
    group: "Nodes",
  },
  {
    value: "nodes:console",
    label: "Node Console",
    desc: "Open interactive shell on nodes",
    group: "Nodes",
  },
  {
    value: "nodes:files:read",
    label: "Read Node Files",
    desc: "Browse, open, copy, and download node files",
    group: "Nodes",
  },
  {
    value: "nodes:files:write",
    label: "Write Node Files",
    desc: "Create, edit, upload, move, and delete node files",
    group: "Nodes",
  },
  {
    value: "nodes:folders:manage",
    label: "Manage Node Folders",
    desc: "Create, reorder, and remove node folders",
    group: "Nodes",
  },
  // Administration
  {
    value: "admin:users",
    label: "Manage Users",
    desc: "Create, edit, and delete users",
    group: "Administration",
  },
  {
    value: "admin:users:impersonate",
    label: "Impersonate Users",
    desc: "Temporarily act as another active user",
    group: "Administration",
  },
  {
    value: "admin:users:folders:manage",
    label: "Manage User Folders",
    desc: "Create, reorder, and remove user folders",
    group: "Administration",
  },
  {
    value: "admin:groups",
    label: "Manage Groups",
    desc: "Create, edit, and delete permission groups",
    group: "Administration",
  },
  {
    value: "admin:groups:folders:manage",
    label: "Manage Group Folders",
    desc: "Create, reorder, and remove permission group folders",
    group: "Administration",
  },
  {
    value: "admin:audit",
    label: "View Audit Log",
    desc: "View the audit log",
    group: "Administration",
  },
  {
    value: "audit:siem:view",
    label: "View SIEM Export",
    desc: "View SIEM destinations and audit delivery history",
    group: "Administration",
  },
  {
    value: "audit:siem:manage",
    label: "Manage SIEM Export",
    desc: "Configure SIEM destinations and control audit deliveries",
    group: "Administration",
  },
  {
    value: "admin:system",
    label: "System Admin",
    desc: "System-level administration (protected)",
    group: "Administration",
  },
  {
    value: "admin:details:certificates",
    label: "View System Certificates",
    desc: "View internal system PKI and SSL certificates in read-only mode",
    group: "Administration",
  },
  {
    value: "admin:update",
    label: "Manage Updates",
    desc: "Check for and apply updates",
    group: "Administration",
  },
  {
    value: "admin:alerts",
    label: "Manage Alerts",
    desc: "View and manage alerts",
    group: "Administration",
  },
  // Gateway Settings
  {
    value: "settings:gateway:view",
    label: "View Gateway Settings",
    desc: "View sign-in provisioning and external control-plane settings",
    group: "Gateway Settings",
  },
  {
    value: "settings:gateway:edit",
    label: "Edit Gateway Settings",
    desc: "Edit sign-in provisioning and external control-plane settings",
    group: "Gateway Settings",
  },
  // Integrations: GitLab
  {
    value: "integrations:gitlab:view",
    label: "View GitLab Integrations",
    desc: "View configured GitLab connectors and sync status",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:manage",
    label: "Manage GitLab Integrations",
    desc: "Create, edit, rotate, and delete GitLab connectors",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:sync",
    label: "Sync GitLab Integrations",
    desc: "Refresh projects and registries using the connector credential",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:system",
    label: "Use System GitLab Credential",
    desc: "Use the connector credential for otherwise permitted GitLab operations",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:projects:view",
    label: "View GitLab Projects",
    desc: "Discover allowed GitLab groups and projects",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:repo:read",
    label: "Read GitLab Repositories",
    desc: "Read repository trees and files through GitLab connectors",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:repo:write",
    label: "Write GitLab Repositories",
    desc: "Commit file changes through GitLab connectors",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:ci:view",
    label: "View GitLab CI",
    desc: "View GitLab CI pipelines and configuration",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:ci:edit",
    label: "Edit GitLab CI",
    desc: "Lint and update GitLab CI configuration",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:variables:view",
    label: "View GitLab Variables",
    desc: "View GitLab variable metadata without secret values",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:variables:edit",
    label: "Edit GitLab Variables",
    desc: "Create and update GitLab project variables",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:variables:delete",
    label: "Delete GitLab Variables",
    desc: "Delete GitLab project variables",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:webhooks:manage",
    label: "Manage GitLab Webhooks",
    desc: "Create, update, and delete GitLab project webhooks",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:registry:manage",
    label: "Manage GitLab Registries",
    desc: "Manage GitLab registry integration records and deploy credentials",
    group: "Integrations: GitLab",
  },
  {
    value: "integrations:gitlab:sandbox:clone",
    label: "Clone GitLab Repositories",
    desc: "Clone allowed GitLab repositories into AI sandboxes",
    group: "Integrations: GitLab",
  },
  // Integrations: GitHub
  {
    value: "integrations:github:view",
    label: "View GitHub Integrations",
    desc: "View configured GitHub token connectors",
    group: "Integrations: GitHub",
  },
  {
    value: "integrations:github:manage",
    label: "Manage GitHub Integrations",
    desc: "Create, edit, rotate, and delete GitHub token connectors",
    group: "Integrations: GitHub",
  },
  {
    value: "integrations:github:system",
    label: "Use GitHub System Credential",
    desc: "Use the connector credential instead of a personal GitHub authorization",
    group: "Integrations: GitHub",
  },
  // Integrations: Generic Git
  {
    value: "integrations:git:view",
    label: "View Git Integrations",
    desc: "View configured generic Git connectors",
    group: "Integrations: Git",
  },
  {
    value: "integrations:git:manage",
    label: "Manage Git Integrations",
    desc: "Create, edit, rotate, and delete generic Git connectors",
    group: "Integrations: Git",
  },
  {
    value: "integrations:git:system",
    label: "Use Git System Credential",
    desc: "Use the connector credential instead of a personal Git authorization",
    group: "Integrations: Git",
  },
  // Integrations: External SSH
  {
    value: "integrations:ssh:view",
    label: "View External SSH Integrations",
    desc: "View configured external SSH servers",
    group: "Integrations: SSH",
  },
  {
    value: "integrations:ssh:manage",
    label: "Manage External SSH Integrations",
    desc: "Add and configure external SSH servers and jump hosts",
    group: "Integrations: SSH",
  },
  {
    value: "integrations:ssh:use",
    label: "Use External SSH Integrations",
    desc: "Execute approved commands on configured external SSH servers",
    group: "Integrations: SSH",
  },
  // Integrations: Cloudflare
  {
    value: "integrations:cloudflare:view",
    label: "View Cloudflare Integrations",
    desc: "View configured Cloudflare connectors and synchronization status",
    group: "Integrations: Cloudflare",
  },
  {
    value: "integrations:cloudflare:manage",
    label: "Manage Cloudflare Integrations",
    desc: "Create, edit, test, synchronize, rotate, and delete Cloudflare connectors",
    group: "Integrations: Cloudflare",
  },
] as const;
