export const INFRASTRUCTURE_TOKEN_SCOPES = [
  // Docker: Containers
  {
    value: "docker:containers:view",
    label: "View Containers",
    desc: "View Docker containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:create",
    label: "Create Containers",
    desc: "Create and duplicate containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:edit",
    label: "Edit Containers",
    desc: "Edit container settings and configuration",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:config",
    label: "Container Config",
    desc: "View container recreate/configuration fields",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:manage",
    label: "Manage Containers",
    desc: "Start, stop, restart, kill, and recreate containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:migrate",
    label: "Migrate Containers",
    desc: "Migrate containers and deployments between Docker nodes",
    group: "Docker: Containers",
  },
  {
    value: "docker:availability:manage",
    label: "Manage Availability",
    desc: "Enable, scale, heal, and disable multi-node workload Availability",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:environment",
    label: "Container Environment",
    desc: "Modify container environment variables",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:delete",
    label: "Delete Containers",
    desc: "Remove containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:console",
    label: "Container Console",
    desc: "Open interactive console in containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:files:read",
    label: "Read Container Files",
    desc: "Browse and read files in containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:files:write",
    label: "Write Container Files",
    desc: "Create, edit, move, and delete files in containers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:export",
    label: "Export Containers",
    desc: "Export portable container archives",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:secrets",
    label: "Container Secrets",
    desc: "View and manage encrypted secrets",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:webhooks",
    label: "Container Webhooks",
    desc: "View and manage container webhook update triggers",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:mounts",
    label: "Container Mounts",
    desc: "Add, remove, or change container and deployment mounts",
    group: "Docker: Containers",
  },
  {
    value: "docker:containers:folders:manage",
    label: "Manage Docker Folders",
    desc: "Create, reorder, and remove Docker resource folders",
    group: "Docker: Containers",
  },
  // Docker: Compose Projects
  {
    value: "docker:compose:view",
    label: "View Compose Projects",
    desc: "Discover and inspect Compose projects, services, monitoring, logs, revisions, and activity",
    group: "Docker: Compose",
  },
  {
    value: "docker:compose:create",
    label: "Create Compose Projects",
    desc: "Validate and deploy managed Compose projects; adoption also requires Manage Compose Projects",
    group: "Docker: Compose",
  },
  {
    value: "docker:compose:manage",
    label: "Manage Compose Projects",
    desc: "Adopt projects and manage lifecycle, revisions, secrets, and bindings",
    group: "Docker: Compose",
  },
  {
    value: "docker:compose:delete",
    label: "Delete Compose Projects",
    desc: "Delete Compose projects or run destructive down/delete-volume actions",
    group: "Docker: Compose",
  },
  // Docker: Images
  {
    value: "docker:images:view",
    label: "View Images",
    desc: "View Docker images",
    group: "Docker: Images",
  },
  {
    value: "docker:images:pull",
    label: "Pull Images",
    desc: "Pull Docker images",
    group: "Docker: Images",
  },
  {
    value: "docker:images:delete",
    label: "Delete Images",
    desc: "Remove and prune Docker images",
    group: "Docker: Images",
  },
  // Docker: Volumes
  {
    value: "docker:volumes:view",
    label: "View Volumes",
    desc: "View Docker volumes",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:create",
    label: "Create Volumes",
    desc: "Create Docker volumes",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:delete",
    label: "Delete Volumes",
    desc: "Remove Docker volumes",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:export",
    label: "Export Volumes",
    desc: "Export portable Docker volume archives",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:files:read",
    label: "Read Volume Files",
    desc: "Browse, open, and download Docker volume files",
    group: "Docker: Volumes",
  },
  {
    value: "docker:volumes:files:write",
    label: "Write Volume Files",
    desc: "Create, edit, upload, move, and delete Docker volume files",
    group: "Docker: Volumes",
  },
  // Docker: Networks
  {
    value: "docker:networks:view",
    label: "View Networks",
    desc: "View Docker networks",
    group: "Docker: Networks",
  },
  {
    value: "docker:networks:create",
    label: "Create Networks",
    desc: "Create Docker networks",
    group: "Docker: Networks",
  },
  {
    value: "docker:networks:edit",
    label: "Edit Networks",
    desc: "Connect and disconnect containers",
    group: "Docker: Networks",
  },
  {
    value: "docker:networks:delete",
    label: "Delete Networks",
    desc: "Remove Docker networks",
    group: "Docker: Networks",
  },
  // Docker: Registries
  {
    value: "docker:registries:view",
    label: "View Registries",
    desc: "View Docker registries",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:create",
    label: "Create Registries",
    desc: "Add Docker registries",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:edit",
    label: "Edit Registries",
    desc: "Edit Docker registry settings",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:delete",
    label: "Delete Registries",
    desc: "Remove Docker registries",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:internal:pull",
    label: "Pull Internal Images",
    desc: "Pull from all internal registry repositories or selected repository scopes",
    group: "Docker: Registries",
  },
  {
    value: "docker:registries:internal:push",
    label: "Push Internal Images",
    desc: "Push to all internal registry repositories or selected repository scopes",
    group: "Docker: Registries",
  },
  // Docker: Tasks
  {
    value: "docker:tasks",
    label: "View Tasks",
    desc: "View Docker task progress",
    group: "Docker: Tasks",
  },
  {
    value: "docker:tasks:manage",
    label: "Manage Tasks",
    desc: "Force-cancel active Docker tasks",
    group: "Docker: Tasks",
  },
  // Databases
  {
    value: "databases:view",
    label: "View Databases",
    desc: "View saved database connections",
    group: "Databases",
  },
  {
    value: "databases:create",
    label: "Create Databases",
    desc: "Create saved database connections",
    group: "Databases",
  },
  {
    value: "databases:edit",
    label: "Edit Databases",
    desc: "Edit saved database connections",
    group: "Databases",
  },
  {
    value: "databases:delete",
    label: "Delete Databases",
    desc: "Delete saved database connections",
    group: "Databases",
  },
  {
    value: "databases:query:read",
    label: "Read Database Data",
    desc: "Browse tables, keys, and run read-only database queries",
    group: "Databases",
  },
  {
    value: "databases:query:write",
    label: "Write Database Data",
    desc: "Insert, update, delete, and run write queries against databases",
    group: "Databases",
  },
  {
    value: "databases:query:admin",
    label: "Admin Database Queries",
    desc: "Run administrative or DDL database commands",
    group: "Databases",
  },
  {
    value: "databases:credentials:reveal",
    label: "Reveal Database Credentials",
    desc: "Reveal saved database credentials and connection strings",
    group: "Databases",
  },
  {
    value: "databases:folders:manage",
    label: "Manage Database Folders",
    desc: "Create, reorder, and remove database folders",
    group: "Databases",
  },
  {
    value: "logs:environments:view",
    label: "View Logging Environments",
    desc: "View external logging environments",
    group: "Logging",
  },
  {
    value: "logs:environments:create",
    label: "Create Logging Environments",
    desc: "Create logging environments",
    group: "Logging",
  },
  {
    value: "logs:environments:edit",
    label: "Edit Logging Environments",
    desc: "Edit logging environments and schemas",
    group: "Logging",
  },
  {
    value: "logs:environments:delete",
    label: "Delete Logging Environments",
    desc: "Delete logging environments",
    group: "Logging",
  },
  {
    value: "logs:environments:folders:manage",
    label: "Manage Logging Environment Folders",
    desc: "Create, reorder, and remove logging environment folders",
    group: "Logging",
  },
  {
    value: "logs:tokens:view",
    label: "View Logging Tokens",
    desc: "View logging ingest tokens",
    group: "Logging",
  },
  {
    value: "logs:tokens:create",
    label: "Create Logging Tokens",
    desc: "Create logging ingest tokens",
    group: "Logging",
  },
  {
    value: "logs:tokens:delete",
    label: "Delete Logging Tokens",
    desc: "Revoke logging ingest tokens",
    group: "Logging",
  },
  {
    value: "logs:schemas:view",
    label: "View Logging Schemas",
    desc: "View reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:create",
    label: "Create Logging Schemas",
    desc: "Create reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:edit",
    label: "Edit Logging Schemas",
    desc: "Edit reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:delete",
    label: "Delete Logging Schemas",
    desc: "Delete reusable logging schemas",
    group: "Logging",
  },
  {
    value: "logs:schemas:folders:manage",
    label: "Manage Logging Schema Folders",
    desc: "Create, reorder, and remove logging schema folders",
    group: "Logging",
  },
  {
    value: "logs:read",
    label: "Read Logs",
    desc: "Search and inspect external logs",
    group: "Logging",
  },
  {
    value: "logs:manage",
    label: "Manage Logging",
    desc: "Full access to external logging",
    group: "Logging",
  },
] as const;
